### ISSUE TITLE
Changing the auto-generated kops kubernetes admin password

### ISSUE THREAD

**Issue by rvishwakarma825** [kubernetes/community#1032]
Hi All,
I have been using kops to build the kubernetes cluster which is really easy-to-go tool, however i am unable to find a way-out on how to change the admin password that is auto-generated during the cluster creation by kops.

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close

**Comment by rvishwakarma825** [comment]
https://stackoverflow.com/questions/46277648/changing-the-auto-generated-kops-kubernetes-admin-password 

Hi cblecker,
I have raised it as per your advise. I will be grateful if you can help me on this.


Regards,
Ritesh
