### ISSUE TITLE
SIG docs link to meeting recordings should point to the recorded meeting videos

### ISSUE THREAD

**Issue by countspongebob** [kubernetes/community#1052]
https://github.com/kubernetes/community/blob/master/sig-docs/README.md

Has a self-referential link back to the same page. 

@kubernetes/sig-docs-maintainers

**Comment by xiangpengzhao** [comment]
I can only find two sig docs meeting records on YouTube. Seems like there isn't a channel from SIG Docs currently.

https://www.youtube.com/watch?v=8zEqbHwxE_M
https://www.youtube.com/watch?v=UHRbh27y13M

@zacharysarah since you uploaded the above records, mind create a channel and update https://github.com/kubernetes/community/blob/master/sig-docs/README.md ?

**Comment by xiangpengzhao** [comment]
@kris-nova #wg-cluster-api also has the self-referential link issue. I think it's because the wg hasn't hold a meeting yet :)

**Comment by zacharysarah** [comment]
@xiangpengzhao :wave:

> I can only find two sig docs meeting records on YouTube. Seems like there isn't a channel from SIG Docs currently.

There is! It's just new. :bowtie:

> since you uploaded the above records, mind create a channel and update 

Sure thing! Check out #1071. 🙇
