### ISSUE TITLE
deprecating wiki pages

### ISSUE THREAD

**Issue by philips** [kubernetes/community#116]
Several of the wiki pages are out of date and should go away. Please let me know if these shouldn't go away.

## Out of date

- [x] https://github.com/kubernetes/community/wiki/1.4-Release-Status cc @pwittrock

## Looks abandoned

- [x] https://github.com/kubernetes/community/wiki/WIP:-Proposed-1.5-Release-Milestones-and-Deadlines cc @pwittrock
- [x] https://github.com/kubernetes/community/wiki/Contributor-Guide:-Building-your-Kubernetes-Tool cc @pwittrock
- [x] https://github.com/kubernetes/community/wiki/Release-1.3 cc @goltermann
- [x] https://github.com/kubernetes/community/wiki/Release-1.4 cc @goltermann

## Should move to features repo?

- [x] https://github.com/kubernetes/community/wiki/Roadmap:-ReplicaSet cc @erictune  
- [x] https://github.com/kubernetes/community/wiki/Roadmap:-kubectl cc @pwittrock 
- [x] https://github.com/kubernetes/community/wiki/Roadmap:-Deployment cc @erictune 
- [x] https://github.com/kubernetes/community/wiki/Roadmap:-DaemonSet cc @erictune 

Maybe these just need to be documented I just don't understand what they are for.

## Move to dev guide

- [x] https://github.com/kubernetes/community/wiki/WIP:-Contributor-Guide:-kubectl-new-contributor-onboarding-guide cc @pwittrock
- [x] https://github.com/kubernetes/community/wiki/Release-Guide:-Release-Czar cc @pwittrock
- [x] https://github.com/kubernetes/community/wiki/Life-of-a-Kubernetes-Release cc @david-mcmahon
- [x] https://github.com/kubernetes/community/wiki/Code-Slush cc @david-mcmahon
- [x] https://github.com/kubernetes/community/wiki/Effective-Reviewable cc @thockin 

## Duplicated with community repo 

- [x] https://github.com/kubernetes/community/wiki/SIG-Network cc @thockin @sarahnovotny 

## Move to docs repo

- [x] https://github.com/kubernetes/community/wiki/Roadmap:-Docs @devin-donnelly 

## Consider using Google Docs so people can comment

- [x] https://github.com/kubernetes/community/wiki/Roadmap:-Contributor-Experience cc @grodrigues3 
- [x] https://github.com/kubernetes/community/wiki/Roadmap:-Cluster-Deployment cc @roberthbailey

**Comment by goltermann** [comment]
release-1.3 and release-1.4 can be removed - they've since been migrated to the kubernetes/features repo

**Comment by philips** [comment]
Deleted.

**Comment by bgrant0607** [comment]
@philips Are you trying to eliminate all wiki pages?

As for the Roadmap pages that I created, I'd like to ensure that their content is taken into account by ongoing efforts. How about in documents owned by the relevant SIGs? I do not want to add documentation for the features repo, since that would increase notification and issue activity unrelated to feature tracking.

Wiki page, owner, and relevant SIG:
* Roadmap:-kubectl, @pwittrock, sig-cli
* Roadmap:-Docs, @devin-donnelly, sig-docs
* Roadmap:-Contributor-Experience, @grodrigues3, sig-contribx
* Roadmap:-Cluster-Deployment, @roberthbailey, sig-cluster-lifecycle
* Roadmap:-Deployment, @erictune, sig-apps
* Roadmap:-DaemonSet, @erictune, sig-apps
* Roadmap:-ReplicaSet, @erictune, sig-apps

**Comment by philips** [comment]
@bgrant0607 Heh, well, essentially trying to eliminate them all because it seems like they all have better locations to exist these days.

Overall, you can't send a PR to a wiki page nor can you comment on it so it is sort of an exclusive club to be a wiki editor.

**Comment by bgrant0607** [comment]
@philips I don't disagree that there are mostly better places now (or will be soon).

I want to make it as easy as possible to keep fine-grained information, such as links to open issues, up to date. My intent is to hand out write access to this repo fairly liberally in order to facilitate that. So long as people don't need to create PRs to update any content -- no harder than posting a comment to an issue, I don't have a strong opinion whether the content is in docs or wiki.

**Comment by pigmej** [comment]
So, Roadmap:-DaemonSet for sure needs updates. We could instead link to https://github.com/kubernetes/kubernetes/issues/15310                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          From: Brian GrantSent: wtorek, 22 listopada 2016 02:03To: kubernetes/communityReply To: kubernetes/community‎Subject: Re: [kubernetes/community] deprecating wiki pages (#116)@philips Are you trying to eliminate all wiki pages?
As for the Roadmap pages that I created, I'd like to ensure that their content is taken into account by ongoing efforts. How about in documents owned by the relevant SIGs? I do not want to add documentation for the features repo, since that would increase notification and issue activity unrelated to feature tracking.
Wiki page, owner, and relevant SIG:

Roadmap:-kubectl, @pwittrock, sig-cli
Roadmap:-Docs, @devin-donnelly, sig-docs
Roadmap:-Contributor-Experience, @grodrigues3, sig-contribx
Roadmap:-Cluster-Deployment, @roberthbailey, sig-cluster-lifecycle
Roadmap:-Deployment, @erictune, sig-apps
Roadmap:-DaemonSet, @erictune, sig-apps
Roadmap:-ReplicaSet, @erictune, sig-apps


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kubernetes/community","title":"kubernetes/community","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kubernetes/community"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bgrant0607 in #116: @philips Are you trying to eliminate all wiki pages?\r\n\r\nAs for the Roadmap pages that I created, I'd like to ensure that their content is taken into account by ongoing efforts. How about in documents owned by the relevant SIGs? I do not want to add documentation for the features repo, since that would increase notification and issue activity unrelated to feature tracking.\r\n\r\nWiki page, owner, and relevant SIG:\r\n* Roadmap:-kubectl, @pwittrock, sig-cli\r\n* Roadmap:-Docs, @devin-donnelly, sig-docs\r\n* Roadmap:-Contributor-Experience, @grodrigues3, sig-contribx\r\n* Roadmap:-Cluster-Deployment, @roberthbailey, sig-cluster-lifecycle\r\n* Roadmap:-Deployment, @erictune, sig-apps\r\n* Roadmap:-DaemonSet, @erictune, sig-apps\r\n* Roadmap:-ReplicaSet, @erictune, sig-apps"}],"action":{"name":"View Issue","url":"https://github.com/kubernetes/community/issues/116#issuecomment-262116939"}}}

**Comment by philips** [comment]
@pigmej that link is 404ing

**Comment by abitrolly** [comment]
https://github.com/kubernetes/community/wiki/1.4-Release-Status - doesn't seem valuable.

**Comment by bgrant0607** [comment]
@abitrolly Agreed. Gone

**Comment by abitrolly** [comment]
@bgrant0607 an issue point could be ticked?

https://github.com/kubernetes/community/wiki/WIP:-Proposed-1.5-Release-Milestones-and-Deadlines could be a template for https://github.com/kubernetes/features/tree/master/release-1.5 but the scope is broader than just features. I [couldn't find](https://github.com/search?q=org%3Akubernetes+release+czar+assigned&type=Code) repository with such release template.

**Comment by spiffxp** [comment]
removed https://github.com/kubernetes/community/wiki/WIP:-Proposed-1.5-Release-Milestones-and-Deadlines (we have https://github.com/kubernetes/features/blob/master/release-1.5/release-1.5.md)

**Comment by spiffxp** [comment]
- Edited https://github.com/kubernetes/community/wiki to refer to this issue
- Release managers have been moved https://github.com/kubernetes/sig-release/pull/42

**Comment by spiffxp** [comment]
- Replaced https://github.com/kubernetes/community/wiki/WIP:-Contributor-Guide:-kubectl-new-contributor-onboarding-guide with a link to https://github.com/kubernetes/community/blob/master/sig-cli/CONTRIBUTING.md
- Making an executive decision to delete https://github.com/kubernetes/community/wiki/Release-Guide:-Release-Czar (this can't possibly be up to date; we don't have an adequate replacement in https://github.com/kubernetes/sig-release/tree/master/release-process-documentation/release-team-guides but we should, I suspect there is a google doc or internal wiki floating around, what say you @kubernetes/kubernetes-release-managers?)

**Comment by jdumars** [comment]
A re-write of the release process + roles is somewhere in my backlog.  What's out there does not reflect reality.

**Comment by spiffxp** [comment]
I'm making an executive "I've been on multiple release teams" call and outright deleting some content that seems harmfully incomplete or out of date.  These are not going to be source for a rewrite of the release docs we're forming up over in https://git.k8s.io/sig-release
- deleted https://github.com/kubernetes/community/wiki/Life-of-a-Kubernetes-Release
- deleted https://github.com/kubernetes/community/wiki/OSS-Release-Process-Improvements-Roadmap/_edit

As an active participant in sig-contributor experience, I'm comfortable removing this doc which has been marked obsolete and hasn't been touched in ~11 months, and I haven't seen come up in the meetings I've participated in (FYI @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort)
- deleted https://github.com/kubernetes/community/wiki/Roadmap:-Contributor-Experience

This one seems pretty clear, we've been saying community/sig-foo is the authoritative place to find sig contact info for a while now (FYI @kubernetes/sig-network-misc)
- deleted https://github.com/kubernetes/community/wiki/SIG-Network in favor of https://github.com/kubernetes/community/blob/master/sig-network/README.md

The workload API's have gone stable as a result of 1.9, these pages were just links to issues (FYI @kubernetes/sig-apps-misc)
- deleted https://github.com/kubernetes/community/wiki/Roadmap:-Deployment
- deleted https://github.com/kubernetes/community/wiki/Roadmap:-ReplicaSet

The wiki's a git repo and these deletions can be reverted if anyone's depending on what I've just deleted.

I would have deleted more but my laptop's about to run out of battery.

**Comment by idvoretskyi** [comment]
@spiffxp +1.

PS. Hope you've already recharged your laptop :)

**Comment by abitrolly** [comment]
Who can update checkbox in the top post?

**Comment by mattfarina** [comment]
cc: @kow3ns

**Comment by spiffxp** [comment]
https://github.com/kubernetes/community/pull/1540 moves the last of the existing wiki pages out into `migrated-from-wiki` subdirs in each responsible sig's folder.  I suspect the content in these wiki pages is also obsolete or out of date, but I'll leave that for each SIG to decide.

Once that PR merges, I propose we remove the remaining pages from the wiki, and turn it off.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/community/issues/1511 has restricted the set of people who can actually edit this wiki to a very small list of people

**Comment by spiffxp** [comment]
I've asked kubernetes-dev https://groups.google.com/forum/#!topic/kubernetes-dev/kTFl4Gl7YFw

**Comment by cblecker** [comment]
I support removing/disabling the wiki completely. Can we do this for k/k too? https://github.com/kubernetes/kubernetes/wiki

**Comment by philips** [comment]
I don't have time to work on this. Looks like @spiffxp has point now?

**Comment by spiffxp** [comment]
/assign
sure I'll take point, all that remains to be done for this wiki is to merge kubernetes/release#492 and then disable the wiki

I'd be happy to tackle something similar for kubernetes/kubernetes but I don't have the same access rights there.

**Comment by spiffxp** [comment]
/close
The wiki is now disabled
