### ISSUE TITLE
Add document about how to init --cloud-provider=aws

### ISSUE THREAD

**Issue by wangxinxu411** [kubernetes/community#1237]
Hi Guys.i installed a k8s cluster on aws China.it seems every thing goes fine but when i use ebs volume i got the error of pod ContainerCreating:
Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-08bb02d1e750a3612 /var/lib/kubelet/pods/af9c33b7-b2ea-11e7-8753-06dcce290c54/volumes/kubernetes.io~aws-ebs/couchbase-pv  [bind]
Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-08bb02d1e750a3612 does not exist.

i got information that i should add  --cloud-provider=aws in api-server and kube-let.but i did not find any document about how to config the provider config file...

**Comment by wangxinxu411** [comment]
/sig/contributor-experience

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
