### ISSUE TITLE
Documentation outdated and confusing

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/community#1334]
Many of the docs in contributors/devel are outdated and/or confusing. They should be revised, pruned, and updated.
It is unclear on whether the kubernetes website or these docs are the source of truth. They do not seem to be the same.
Some of these docs are quite relevant and recent, such as development.md, others have not been updated in years.

Proposal:
Remove all docs with conten that can also be found on the website, and instead only provide clear and up-to-date how-to guidance for contributing to kubernetes repo(s).
Outline a clear purpose for this folder/repository.

**Comment by xiangpengzhao** [comment]
Some of the outdated docs seems due to the munger/prow plugins changed but we forgot to change the related docs.

**Comment by cjwagner** [comment]
Most of the docs that reference mungegithub seem up to date to me besides https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md which I'm waiting to update once Prow's approve plugin completely replaces the approval-handler munger.
@xiangpengzhao can you link me to the docs you were reffering to?

**Comment by cblecker** [comment]
@guineveresaenger The overall direction for these docs will be creating a "contributor guide" that will live under kubernetes.io. @parispittman has been spearheading this, and we've discussed it at a couple contribex meetings. If you'd like to provide input or participate, information is available here: https://github.com/kubernetes/community/tree/master/sig-contributor-experience

If there are specific docs that are out of date perhaps we can open separate issues to break them up, rather than a general "the docs are out of date" issue. Documentation lifecycle is always going to be an issue we will have to deal with.. processes are fluidly changing, but the idea of consolidating the docs into a known place so we can update them as part of the process updates themselves is a good idea.

cc: @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort

**Comment by guineveresaenger** [comment]
@cblecker thank you for mentioning this here - I have in fact been in touch with Paris on this. I'm rather new to the community and very interested in making contributing less bumpy for new folks. :)

**Comment by cblecker** [comment]
Fantastic! If you're in touch with Paris, then you're in good hands. We're glad to have you on board!

As we're tracking this in contribex as a goal, I'm going to close this general issue. However if there are specific docs we know are out of date, please feel free to open an issue for them (preferably one issue per doc or type of doc.. that way we can find the right owner and assign it to them for updates).

Thank you!

**Comment by xiangpengzhao** [comment]
>Most of the docs that reference mungegithub seem up to date to me besides https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md which I'm waiting to update once Prow's approve plugin completely replaces the approval-handler munger.
@xiangpengzhao can you link me to the docs you were reffering to?

@cjwagner I updated some docs in https://github.com/kubernetes/community/pull/1016. I guess I should use past tense in my last comment :)
