### ISSUE TITLE
"How to do reviews and PRs" document needed

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#1514]
Part of  #1413 

We have https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#best-practices-for-faster-reviews for the person submitting the reviews, but we are missing a document for people doing reviews. We need to collate some tips and tricks from reviewers from across the project.

**Comment by chrislovecnm** [comment]
/cc @thockin 

We talked about this Tim @ kubecon :)  Dragging you into it kicking a screaming.  NEED your help!!

/cc @justinsb 

Since you are opinionated on PR reviews, need your help.

**Comment by tpepper** [comment]
I like to use the docs like https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#best-practices-for-faster-reviews as a starting point for reviewers.  The reviewer and reviewee docs should be symmetric.

A lot of the existing doc is around mechanical "how" parts.  For the philosophical parts I like to refer people to http://sage.thesharps.us/2014/09/01/the-gentle-art-of-patch-review/ but some of this varies with project and the local k8s culture needs to be documented by local gurus.

I really like this https://www.youtube.com/watch?feature=player_embedded&v=fMeH7wqOwXA#! old talk on reviewer/approver/maintainer issues because it has a senior person describing their review process and workload.   Reviewers need to be skeptical, have a broad view for technical debt and potential collateral damage.  Has the change been sufficiently justified and tested?  I also like that it comes from a time when that project was suddenly experiencing a huge spurt of growth (arm & arm64 and android drivers) and figuring out how to incentivize large out-of-tree code contributors to stay closer to upstream, which parallels @thockin's discussion about the kernel vs distro split concept.

**Comment by chrislovecnm** [comment]
@parispittman mentioned this on slack https://twitter.com/math_rachel/status/939968380202762240

**Comment by parispittman** [comment]
Created this doc - appreciate collaboration. This will be used as a resource when mentoring new reviewers. 

["Code Reviews the Kuberetes Way"](https://docs.google.com/document/d/1vP95I180Lj_e4JT40QZ4vIkbOsiY8pkTtfJcmP5i5Ac/edit#heading=h.qnd9ih5ibazs)

**Comment by tpepper** [comment]
I've dropped some related doc links in the google doc.

**Comment by castrojo** [comment]
More reference material to check out: https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

**Comment by castrojo** [comment]
See also: https://docs.google.com/document/d/1WVobATuodV0T3F22CXhsdYpOk5K7D-uKO9j-0QUuLdU/edit#heading=h.2oi459gj6360

**Comment by guineveresaenger** [comment]
Current status summary of this issue:
- Reviews from the PR author's perspective are covered well as per #1761 .
- "How to review" still deeds doing; this is a gig for an experienced contributor/reviewer. For completion:
     
1.  There is some material in #1645 that should go into the reviewer guidelines
2. A good location for this is either a new subsection of https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md
or quite possibly a doc of its own, in the spirit of https://github.com/kubernetes/community/blob/master/contributors/devel/collab.md but it should live in `contributors/guide` not `contributors/devel`.
3. https://github.com/kubernetes/community/blob/master/contributors/devel/collab.md needs to be moved and possibly renamed or sunsetted - the goal should be that it's in a logical, easy to find place, with a comprehensive title ("Code Review The Kubernetes Way" being a top contender).

**Comment by guineveresaenger** [comment]
/remove-help

Apologies, this should be done by an experienced contributor.
