### ISSUE TITLE
Confusion over states in the KEP-1 proposal

### ISSUE THREAD

**Issue by technosophos** [kubernetes/community#1793]
This issue arises out of a discussion in SIG-Apps today, and applies to 0001-kubernetes-enhancement-proposal-process.md

For background, there has been movement in the community to use the KEP process for more general standards (e.g. CRDs, conventions, or ecosystem tooling), not just changes to Kubernetes core. This is causing confusion.

The states defined in the KEP-1 (implementable, implemented, deferred, etc.) are significantly different than the states define for RFCs, Rust RFCs, PEPs, and similar specification processes. This is causing confusion about how to actually use KEPs.

Specifically, it appears to be a process designed to handle only _one implementation_ of any given proposal. (`implementable`/`implemented`/`deferred`). Thus it seems only useful for one project that admits only one canonical implementation of a KEP. So it becomes generally unusable when trying to define interchange formats, protocols, schemata, etc.

The core confusion comes from conflating _specification_ and _implementation_. First, an implementation can be achieved against a non-existent or poor specification. Whether something is _implementable_ or _implemented_ does not speak to the quality of the specification. Neither should the existence of an implementation foreclose the possibility of writing a good specification. Second, a specification does not necessarily need "an implementation" to be useful. One might "specify" the purpose or meaning of labels or annotations, but without having "an implementation". (KEP-1, for example, does not have "an implementation".)

As a remedial action, I would propose that we do one of two things:

- Agree to not use KEP-1 for anything but proposals to extend the functionality of Kubernetes core, and leave everyone else (SIGs, etc) to figure out their own process
- Supersede KEP-1 with a new KEP that outlines states as they are explained in [the RFC process](https://en.wikipedia.org/wiki/Request_for_Comments) or another standards process that is not strongly tied to just one canonical implementation.

**Comment by cblecker** [comment]
cc: @jbeda @bgrant0607 @calebamiles @jdumars

**Comment by jbeda** [comment]
First off -- SIGs should feel free to use whatever process they need for their own design and communication.  KEPs will probably only be necessary as we start having things that impact the project in a wider way (like new APIs, wide changes across the project, etc).

As for the states -- they started out based on the PEP process but were changed based on feedback from early users of the process.  I'm open to tweaking them some more.  Personally I liked the simpler set of states.

The big question was around when to check in an initial version and what "approval" meant.  My original plan was that `draft` was there so that people could check things in early and not get 100+ comment PRs.  I'd like the PRs to be focused as the discussion moves forward.  However, some felt that we wanted to have *some* screening before the first PR is merged and so `accepted` was introduced as a way to say that the idea of the KEP (general concept) was accepted by a SIG as business to take up.

Would love to have @bgrant0607 and @calebamiles weigh in here.

**Comment by bgrant0607** [comment]
A common, valid complaint about past proposals was regarding the lack of clarity regarding the implementation statuses of the proposals. The vast majority of proposals in this project have resulted in single canonical implementations, or no implementation. These proposals are, for the most part, unlike IETF/ISOC RFCs, which aren't necessarily associated with any specific implementation. So, I think we do need the states to cover implementation status.

Even abstract APIs and Go interfaces have some implementation associated with them, even if not business logic.

**Comment by bgrant0607** [comment]
Alternatives to accepted are being discussed in #1775

**Comment by bgrant0607** [comment]
Regarding 100s of comments: As a practical matter, the Application KEP has so many comments, that it's having trouble loading in the github UI at this point.

**Comment by jbeda** [comment]
(I tried with the application KEP to encourage it to be submitted and iterated on after that.  That is exactly the situation we are trying to avoid with "check in early")

**Comment by jbeda** [comment]
We've decided on `provisional` instead of `accepted`.  Discussion here: https://youtu.be/Os0zQoYL4XA?t=53m54s.  I'll get a PR together today to make that happen.
