### ISSUE TITLE
Support client certificate revocation

### ISSUE THREAD

**Issue by traghave** [kubernetes/community#1902]
Need help regarding revoking a already issued client certificates.

Steps to reproduce:

1. I added the groups information in the idtoken of oidcUser1 and configured the same groups 
using "--oidc-groups-claim" in kubernetes

2. I've created created client certificate and key for use with kubectl.
```
openssl req -newkey rsa:2048  -out oidcuser.csr -nodes -keyout oidcuser.key -subj /CN=oidcUser/O=group1/O=group2
```
which works fine with
kubectl config set-credentials oidcuser --client-certificate=oidcuser.pem --client-key=oidcuser.key

4. Problem is if the user groups for oidcuser changes, then the certificate still have stale group information.

5. Is there any way we can configure apiserver to reject such certificates with assuming we have info related to certificate, key in hand?

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/remove-help
/kind support
/close
