### ISSUE TITLE
Create "good first issue" label

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#1959]
The way it is now:

We have the "help-wanted" label, which according to [its description](https://github.com/kubernetes/community/blob/15b507ad2f38b5943bc03d0362416c6483665c28/contributors/devel/help-wanted.md) should cover issues which are suitable for work by novice contributors. However, that's not how that label is being used; instead, it's being used for issues which are not making progess because they need additional expertise, input, or large time commitments.  Mostly, these issues require quite advanced knowledge of Kubernetes.  Examples:  [60023](https://github.com/kubernetes/kubernetes/issues/60023), [56567](https://github.com/kubernetes/kubernetes/issues/56567).

This means that would-be new contributors, looking for their first place to hack on Kubernetes, can't figure out where to start.  We could try to change member's behavior in using the "help wanted" tag, but that seems unlikely to be successful.

What we should do:

1. Add the "good first issue" label to automation and all repos that want it.  This includes creating the /good-first-issue and /remove-good-first-issue commands for Prow, and writing a description.
2. Amend the description to the "help wanted" label to reflect its actual use.
3. Share the new label, and an explanation of how "help wanted" and "good first issue" are distinct, with kubernetes-dev, the community meeting and the SIG leads.

The choice of "good first issue" here is because Github has public filters for that label.  While other text, such as "for-new-contributors" or "help wanted/easy" might be preferable, I believe that the use of Github's existing label will make things easier for folks who know Github but not Kubernetes.

**Comment by guineveresaenger** [comment]
Is someone working on adding the prow command? I’d like to volunteer for that part if no one’s doing it yet...

**Comment by cblecker** [comment]
Some thoughts:
- "We could try to change member's behavior in using the "help wanted" tag, but that seems unlikely to be successful." - This shouldn't be a driver. I think we need to set clear guidelines on what "help wanted" should be, and then circulate it far and wide. Same with "good first issue", if we add it.
- I'm in favour of a new "good first issue" label, but only in the case that we can clearly define what the difference is between good first issue, and help wanted. Do they compliment each other? Do they compete with each other? The current definition of help wanted is here: https://github.com/kubernetes/community/blob/master/contributors/devel/help-wanted.md
- I'd like to see that documentation and definition *first*, before we put the automation or labels into place. My thinking here, is that when we go and trumpet out to people the change to automation (as required by our charter), we can already show them what the automation will be used for *before* it's turned on.
- Lastly, there's some design decisions around the automation that would need to be made. Should "help wanted" and "good first issue" exist on the same issue? Can you have "good first issue" without "help wanted"? When you remove one, should both go away? Should we use a modifier on the existing /help command.. something like "/help first-issue"?

I'd love to hear thoughts on the above :)

**Comment by cblecker** [comment]
@guineveresaenger As far as the automation piece, I don't think anyone is working on it. Once we get to the point where we're ready to implement, it's all yours!

**Comment by nikhita** [comment]
For the documentation of the `help-wanted` label, we can remove "Tractable for new/casual contributors" from the docs and keep the rest same as it is.

For documenting `good first issue`:

---

**Good First Issue**

Items marked with the `good first issue` label should be tractable for new contributors and need to ensure that they follow the guidelines for `help wanted` labels (link) and _additionally_ include the following information:

- Mentorship: There should be someone ready to mentor and walk a new contributor through solving the issue. The mentor should mention a way to contact them (slack username, email, etc).
- Clear task: The task is agreed upon and does not require further discussions in the community. The recommended solution is clearly described in the issue.
- Recommended readings: If any prior knowledge is required, this should be explicitly mentioned and a list of suggested readings should be included.
- Examples: If something similar has been implemented before, it should be mentioned to act as a reference for the new contributor.
- Files to update: Point out to the parts of the project that would need to be modified for solving the issue.

Make sure that the issue makes a statement that new contributors are welcome, that they are valued, and that they can start on our project! 

---

Example: https://github.com/kubernetes/kubernetes/issues/60538#issuecomment-369182483.

About the automation:

> Do they compliment each other? Do they compete with each other? 

IMO they compliment each other. I see `good first issue` as a subset of the `help wanted` label.

From the above definition, good-first-issue = help-wanted + extra help.

> Should "help wanted" and "good first issue" exist on the same issue? Can you have "good first issue" without "help wanted"?

I think we can have a behaviour like this:

- If you have `good first issue`, you should have `help wanted`.
- You can have `help wanted` without `good first issue`.

> When you remove one, should both go away?

- If you have an issue with `good first issue` and `help wanted` and:
    - you remove `good first issue` => nothing happens, `help wanted` stays.
    - you remove `help wanted` => both get removed.
- Additionally, you should be able to add a `good first issue` label to an issue with an already existing `help wanted` label.

> Should we use a modifier on the existing /help command.. something like "/help first-issue"?

We have two choices here:

1. `/help good-first-issue`: This makes sense because `good first issue` cannot exist without `help wanted`.

However, my only concern is that it is not-so-intuitive. My expectation from the command would be to have a `help wanted/good-first-issue`, which is not the case. This would (and should) add a new label (since Github treats `good first issue` as a "special" label).

In this case, removing would be through `/remove-help good-first-issue`. This is also counter-intuitive. 

2. `/good-first-issue`: I like this one because it is not counterintuitive but I am not sure if it is "logically" correct.

This would mean also mean that the user is surprised that the `help wanted` label is magically removed. But I guess it is reasonable to expect that?

- `/good-first-issue` adds  `good first issue` _and_ `help wanted`.
- `/remove-good-first-issue` removes `good first issue` _and_ `help wanted`.

**Comment by nikhita** [comment]
From https://github.com/kubernetes/community/issues/860,

> Once someone is assigned the issue (either directly or by assigning @k8s-external-contributor), the bot automatically removes the label.

@cblecker Does something like this exists already?

**Comment by parispittman** [comment]
@nikhita I think explicitly requiring mentorship may deter folks from using the label if they don't have time themselves to handle. 

I also see good-first-issue as something that implies help-wanted already so needing both would be duplicate, imo. Help-wanted should imply anyone other than a first time contributor because it may be too complex or would most definitely need guidance from another human.

**Comment by nikhita** [comment]
> I think explicitly requiring mentorship may deter folks from using the label if they don't have time themselves to handle. 

Fair point, @parispittman. :+1:

**Comment by nikhita** [comment]
Just noticed that `kubernetes/kubectl` uses a `good first issue` already - https://github.com/kubernetes/kubectl/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22.

**Comment by jberkus** [comment]
@cblecker 

> "We could try to change member's behavior in using the "help wanted" tag, but that seems unlikely to be successful." - This shouldn't be a driver. I think we need to set clear guidelines on what "help wanted" should be, and then circulate it far and wide. Same with "good first issue", if we add it.

In 20 years of open source development, I've found that you only attempt to change people's habits when there's a large benefit to be delivered thereby.  It's very, very hard to do.

**Comment by jberkus** [comment]
Seems like we have a definitinion for this and no real objections.  Is there anything blocking moving foward (PR and kubernetes-dev discussion)?

**Comment by cblecker** [comment]
@jberkus No, I don't think so!
Suggested path forward:
- PR to k/community updating the help-wanted.md with the proposed definitions
- Send PR to k-dev with a timebox for feedback/consensus
- PR to k/test-infra to add the label
- PR to k/test-infra to add the command

**Comment by cblecker** [comment]
To update this, the label was created as a part of https://github.com/kubernetes/test-infra/pull/8129.
We still need to:
- update our "help wanted" guidelines with what the policy should be
- update the `/help` bot command to allow this label to be applied

@nikhita @guineveresaenger @jberkus: You all had expressed interest in this issue. Does anyone want to tackle one or more of these pieces in, say, the next two weeks? I'd like to move the needle forward on this. I'm happy to provide reviews/mentoring. If you don't have the cycles, that's okay too (although letting me know would be appreciated).

**Comment by carolynvs** [comment]
I would like to contribute to the "help wanted" guidelines! I had pneumonia the past few weeks, but am finally back to work and can share some of what I've been doing with SIG service catalog to bring in new contributors.

**Comment by carolynvs** [comment]
@guineveresaenger @nikhita I would love to collaborate with you both on some guidelines for help-wanted and good-first-pr. What do you say? 😀

**Comment by nikhita** [comment]
@carolynvs the edit is :100: 

> update the /help bot command to allow this label to be applied

I'd like to work on this! I'll get started with it. @cblecker, I'll ping you in case I need help. :)

**Comment by carolynvs** [comment]
I'll work on combining the ideas here and submit a PR with changes to the doc files in this repo for the `help wanted` and `good first pr` labels.

**Comment by guineveresaenger** [comment]
Hi everyone- just woke up and see that everything is being volunteered for. I’ve been swamped lately so I’m happy to review and observe! Thank you all!

**Comment by nikhita** [comment]
@guineveresaenger would love a review of https://github.com/kubernetes/test-infra/pull/8273 :)

**Comment by nikhita** [comment]
Trying out something for checking the labels automation:

/label approved

**Comment by cblecker** [comment]
Last piece: Communicating what we've done! Who would like to send the e-mail to k-dev pointing at the docs as well as the bot commands?

**Comment by nikhita** [comment]
> Who would like to send the e-mail to k-dev pointing at the docs as well as the bot commands?

I'll do it! :tada:

I'll send the email on Monday. I'll sync up with @carolynvs and @guineveresaenger before hitting send. :)

**Comment by nikhita** [comment]
Kubernetes-dev: https://groups.google.com/d/msg/kubernetes-dev/UTkiFncx0YI/jZ45qIB_BQAJ
SIG-contribex: https://groups.google.com/d/msg/kubernetes-sig-contribex/-59Zu7LwBcA/f0lcQfGABQAJ

**Comment by guineveresaenger** [comment]
All work in this has been completed. Thank you everyone!

/close
