### ISSUE TITLE
[hpa] hpa is creating pod > then max size on kube 1.7

### ISSUE THREAD

**Issue by arashadahamad** [kubernetes/community#2038]
hpa is creating pod > max size on kube 1.7.

Observation:
This is due to getting <unknown> metrics from heapster,

Expected:
hpa should not create more pod in case of <unknown> metrics

output
$kubectl get hpa
ghost-api-autoscale             Deployment/ghost-api             199% / 45%        3         20        6          20h
ghost-tags-autoscale            Deployment/ghost-tags            unknown / 45%   3         20        24         20h
ghost-worker-autoscale          Deployment/ghost-worker          6% / 45%          3         20        3          20h

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
