### ISSUE TITLE
github: document repo permissions levels

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#2126]
Create documentation on Github permissions, and draft policies on who needs specific roles and why.

**Comment by jdumars** [comment]
+1

**Comment by nikhita** [comment]
/priority important-longterm

It would be nice to have this "important-soon", but I guess it's realistic to have this as "important-longterm" since we have lots of people who have access to repos as direct collaborators. Cleaning that up is a part of https://github.com/kubernetes/community/issues/3178.

**Comment by nikhita** [comment]
We have https://github.com/kubernetes/community/blob/master/github-management/permissions.md#repository-level-permissions today. What else do we need to document?

**Comment by vishakhanihore** [comment]
@nikhita Can I be of any help in here, if the following is not resolved yet 😄

**Comment by mrbobbytables** [comment]
I think this is safe to close at this point, the section is documented. The other 2 permissions levels (triage and maintain) aren't really used by the project.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
Agree with @mrbobbytables and @nikhita, the docs we have look good to me.  If there are specific questions that remain unanswered, please open a new issue.

/close
