### ISSUE TITLE
Adding a new sigs directory

### ISSUE THREAD

**Issue by whs-dot-hk** [kubernetes/community#2283]
There are several markdown file in the root directory

e.g. 
* `sig-list.md`
* `sig-governance.md`
* `sig-creation-procedure.md`
* `setting-up-cla-check.md`
* `org-owners-guide.md`
* `kubernetes-repositories.md`
* `governance.md`

really related to SIGs

I suggest create a folder call `sigs` and put them there

to minimize the time for comprehend what are they for

and why they are sitting there

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-contributor-experience-bugs @cblecker

**Comment by nikhita** [comment]
Not all files are sig-related though. For example, `setting-up-cla-check.md` is about setting up CLAs rather than about SIGs.

**Comment by cblecker** [comment]
The following files are meant to be at the root because they are critically important documents:
- sig-list.md
- governance.md

The following files will move in a PR I've opened (https://github.com/kubernetes/community/pull/2277):
- org-owners-guide.md
- setting-up-cla-check.md
- kubernetes-repositories.md

The following files need to be reviewed for content accuracy, but could possibly be moved to another part of the repo -- I don't think another top level folder is right for them, but they may be able to be combined with other documents, or relocated:
- sig-governance.md
- sig-creation-procedure.md
