### ISSUE TITLE
Urgent: Just installed Kubernetes on Ubuntu and I see a lot of nodes are getting created in MAAS

### ISSUE THREAD

**Issue by SDAdham** [kubernetes/community#2298]
After installing kubernetes, I see a huge list of nodes and yet still increasing (whats going on?):

aware-code
aware-yak
casual-corgi
casual-whale
casual-mole
clear-hound
close-liger
cool-troll
decent-beetle
divine-bug
driven-drake
easy-cod
equal-frog
equal-swan
exotic-earwig
expert-cow
expert-slug
fair-bee
first-dog
frank-monkey
gentle-racer
good-koi
grown-bunny
guided-eft
handy-wahoo
hip-hornet
holy-bass
holy-hen
intent-bear
large-kit

I can't find that list on Kubernetes, but I can see it in MAAS (since I started setting up Kubernetes, I've been watching MAAS, so I know that this started since installing Kubernetes)

Can anyone please help?

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close

**Comment by SDAdham** [comment]
Hi cbleker,

I posted the question on stackoverflow as well

https://stackoverflow.com/q/50970133/5224768

I did a long research about this but still its not clear why this behaviour, i have a lot of nodes now. If anyone can really help, would be really appreciated.

**Comment by SDAdham** [comment]
@cblecker : please reopen this case, I need to know where those 70+ VMs came from.

**Comment by SDAdham** [comment]
@cblecker I don't really understand why you would really treat a deployment that installs 70+ VMs "a misconfiguration" and not bug! when installing Kubernetes can be as small as 1 VM

Why do you see this as support case and not a bug?
