### ISSUE TITLE
New Contributor Playground

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#2321]
https://kubernetes.slack.com/archives/C1TU9EB9S/p1529008553000790

There was a Slack discussion on setting up a new contributor playground, not in k/community. Opening up an issue to track it so we don't forget.

**Comment by cblecker** [comment]
@guineveresaenger @carolynvs @parispittman Do you know what the "due date" for this is? When will a playground be needed by?

**Comment by carolynvs** [comment]
I am doing an OSS workshop at GopherCon the last week of August that if it were done by then, I would point people towards it. But otherwise I would guess KubeCon Seattle, right @guineveresaenger?

FYI, since this involves setting up a new repo, I'm not sure how I can help move this forward until that's created. Let me know if I'm missing something and I can work on it this week on my vacation!

**Comment by parispittman** [comment]
they will have a new contributor workshop in Shanghai that @jberkus is leading

**Comment by jberkus** [comment]
We definitely need one by Shanghai.  Having one by GopherCon would be even better.

**Comment by cblecker** [comment]
This is done: https://github.com/kubernetes/org/issues/26

/close
