### ISSUE TITLE
EKS and tag k8s.io/cluster-autoscaler/node-template/label is not assigned to worker nodes

### ISSUE THREAD

**Issue by cabrinoob** [kubernetes/community#2405]
Hi,
I'am using an EKS cluster and I'd like to use cluster-autoscaler with it.

cluster-autoscaler version : 1.2.2
EKS kubernetes version : 1.10

So I have a brand new EKS cluster (with existing nodes) and I'd like to add new worker nodes with the CloudFormation script (as explained [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html)).

This script provided 3 new t2.small EC2 into an auto-scaling group. Because I'd like to use nodeSelector, I have tagged the ASG as explained [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0) : 

_If you are using nodeSelector you need to tag the ASG with a node-template key "k8s.io/cluster-autoscaler/node-template/label/"_

In my AWS console I see my tag on my ASGlike that : 

![tag](https://i.imgur.com/wzZltrG.png)

So, my problem is that I see news nodes in kubernetes, but the tag _k8s.io/cluster-autoscaler/node-template/label/project_ has not been assigned to the labels of these nodes .... I don't know what I have missed.

The only tags I see are : 

```
Labels:         beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=t2.small
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1c
                    kubernetes.io/hostname=ip-xxx-xxx-xxx-xxx.ec2.internal
```

Here is the launch command of the cluster-autoscaler pod : 
```json
"command": [
              "./cluster-autoscaler",
              "--v=4",
              "--stderrthreshold=info",
              "--cloud-provider=aws",
              "--skip-nodes-with-local-storage=false",
              "--nodes=1:3:at-eks-worker-nodes-asg2-NodeGroup-1QOBK4RZ42IZI"
            ]
```
What I've missed?

Thank you for your help

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close

**Comment by Jeffwan** [comment]
@cabrinoob  I took some time to look at this issue. Actually, aws manager will retrieve asg information, and then convert ASG tags into Labels and only save in memory. It doesn't run command like `kubectl label` so that's why you can not see labels there.

**Comment by brannondorsey** [comment]
Does that mean that if you apply an tag like `k8s.io/cluster-autoscaler/node-template/label/example.com/some-label-key` to an AWS ASG the K8s cluster-autoscaler will respect this tag for purposes like nodeSelector or node affinity during pod scheduling but it **will not** actually apply the label to the node? Do you have any more info on the subject?

**Comment by thangbn** [comment]
It's still not working on EKS 1.13. AWS EKS is complete garbage, nothing is working properly even this.

**Comment by cblecker** [comment]
@thangbn Please keep things civil. The upstream Kubernetes GitHub project is not the appropriate place for those kinds of comments.

As this issue has already been closed with a redirect to our support channels, I’m going to go ahead and lock this thread.
