### ISSUE TITLE
cloud-provider-foo subprojects should not live under two SIGs at the same time

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#2516]
/kind cleanup
/committee steering
/sig cloud-provider

I'm operating under the premise that a subproject is a solely hierarchical thing: it only has one parent SIG.  There are at least three SIGs/subprojects not following that rule.  Am I wrong?

/sig azure
/sig gcp
/sig openstack
cloud-provider-foo is listed under both sigs

There is inconsistency on which sig owns which subproject, so it's not clear to me which direction things should move:

/sig aws
cloud-provider-foo is listed under sig-foo
/sig vsphere
cloud-provider-foo is listed under sig-cloud-provider

**Comment by spiffxp** [comment]
/sig vmware
right, s/vsphere/vmware

**Comment by justaugustus** [comment]
Cross-posting my [$0.02](https://groups.google.com/a/kubernetes.io/d/msg/steering/Oowl-ajoBh8/us4nvXcIDwAJ):
```
Aaron --

I think this was a side-effect of having existing CP SIGs prior to the ratification of SIG Cloud Provider.
There is an intent / long-term goal to have existing CP SIGs "bend the knee" i.e., converting a CP SIG to a subproject under SIG Cloud Provider:
- https://github.com/kubernetes/community/blob/master/sig-cloud-provider/CHARTER.md#subproject-creation
- https://github.com/kubernetes/community/blob/master/sig-cloud-provider/CHARTER.md#consolidating-existing-cloud-sigs

From a SIG Azure perspective, we're willing to convert and happy to be [a|the] guinea pig for helping to define the conversion process.

Additionally, I think if SIG CP is going to be the ingress point, their README should include the GitHub teams to contact a specific cloud provider e.g., @kubernetes/sig-azure, @kubernetes/cp-azure (or some such).

Best,
Stephen
```

**Comment by frapposelli** [comment]
My 2 cents, from SIG-VMware perspective.

The scope for SIG-VMware has always been broader than just owning the cloud provider, we created the `cloud-provider-vsphere` subproject initially under SIG-VMware only because SIG Cloud Provider was not there at the time.

I personally participated in the definition of SIG Cloud Provider, and SIG-VMware agreed to transfer ownership of the subproject once SIG CP was approved (this was discussed during several meetings of SIG VMware).

With kubernetes/community#2478 we removed the `cloud-provider-vsphere` subproject from SIG-VMware and added a note regarding the transfer of ownership. We still maintain a bi-weekly syncup on cloud-provider-vsphere under SIG-VMware as we didn't feel the need to transfer ownership of the meeting, but happy to comply if deemed necessary.

I'm cc:ing @andrewsykim as co-chair of SIG Cloud Provider to chime in on this, I believe what SIG-VMware has done (w.r.t. transfer of subproject ownership) was what we collectively agreed to do when the interested parties gave their thumbs up to SIG-CP.

**Comment by andrewsykim** [comment]
Cross posting from https://github.com/kubernetes/steering/issues/65: 

> I think Stephen & Fabio summarized it pretty well :).

As mentioned in our charter, we have a tentative goal to consolidate all the cloud provider SIGs in the next 3 releases (quarters). We understand that a lot of important discussions/development happens within the current SIG structure so we're trying our best to do this in a way that is as least disruptive as possible.

To be honest & transparent with the steering committee though; we have not yet had a discussion around this in any of our meetings since we've been focusing our efforts on documentation + conformance testing from cloud providers. I think we'll make more progress on this front in the next 3 - 6months and I'm happy to give the steering committee more frequent updates on this effort if there is interest!

**Comment by spiffxp** [comment]
At present I don't care about whether SIG's merge or split or spawn or retire etc.  That discussion can happen over in kubernetes/steering#65 (as I explicitly said in my e-mail, my intent was not to kick that discussion off).

Today, in this issue, I just want to ensure that code is owned by a single SIG.  My point about lack of consistency was that I didn't have a pattern to suggest that you follow. You can either hold the subproject in your SIG (and remove it from sig-cloud-provider) until the aforementioned conversation is resolved, or go ahead and transfer it over to sig-cloud-provider now.  

For the three duplicate cloud-provider subprojects, which SIG would you like to own it?

- `cloud-provider-gcp`: I've gotten an offline OK from SIG GCP to assign the `cloud-provider-gcp` subproject to to sig-cloud-provider.
- `cloud-provider-azure`: @justaugustus @shubheksha does this belong to sig-azure or sig-cloud-provider?
- `cloud-provider-openstack`: @hogepodge @dklyle @rjmorse does this belong to sig-openstack or sig-cloud-provider?

I'm happy to do the PR(s) that accomplish this, just need a decision

**Comment by justaugustus** [comment]
@spiffxp -- Any Azure subprojects, including `cloud-provider-azure` will continue to be owned by SIG Azure.

**Comment by hogepodge** [comment]
To mirror what other have said, it is my understanding that the creation of sig-cloud-provider was meant to eventually lead to the eventual shutdown of all sig-<provider> sigs. This wouldn't take code away from the members of those sigs, as individual working groups within sig-cloud-provider would be created that would be the owners of their respective code bases. 

Making repository creation, documentation, testing, and common provider code management easier is the goal of sig-cloud-provider, and rather than take away something from the existing small set of provider sigs it is meant to create a level playing field and empower all of the existing and future providers.

**Comment by hogepodge** [comment]
To add to this, with my /sig openstack hat on, we're committed to this plan.
