### ISSUE TITLE
nslookup resolve issue

### ISSUE THREAD

**Issue by talktolanka** [kubernetes/community#2611]
I am trying to learn DNS in kubernetes with https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

1. I deployed the busybox

2. **kubectl get po busybox -o wide**
NAME      READY     STATUS    RESTARTS   AGE       IP           NODE
busybox   1/1       Running   0          16m       10.200.1.5   worker-1

3. **kubectl exec -ti busybox -- nslookup kubernetes.default**
Server:    10.32.0.10
Address 1: 10.32.0.10 kube-dns.kube-system.svc.cluster.local

**nslookup: can't resolve 'kubernetes.default'
command terminated with exit code 1**

4. Do I need to modify the /etc/resolv.conf file of the worker-1 node. currently the /etc/resolv.conf content is below
**nameserver 169.254.169.254
search c.k8s-project-193906.internal google.internal**

5. Also the version of the worker-1
>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Please help on which configuration cause to  blocking resolve.  Do I need to change resolve.conf file and based on what!!!

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
