### ISSUE TITLE
"how to" for meet our contributors

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2660]
- [x] create a 'how to' put on a meet our contributors episode, including a script, for scaling purposes and to un-bus me.

**Comment by shrasool** [comment]
@parispittman I was going through the December video and did felt the need for the last point 'need a transcript per episode or at least a document of questions and the times of their answers' and since I would be viewing the previous versions I can do that. A format reference would be helpful!

Is there any doc on website or in this repo which is set up for this purpose or do we add this in the descriptions in the YouTube recordings?

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale

With mentoring kicking back up this should come into play soon.

**Comment by markyjackson-taulia** [comment]
I took notes from today's meeting and this I have a way to box this up for someone to pick it up in a uniformed fashion

**Comment by onlydole** [comment]
+1 to this, and @castrojo's comments from this morning 😆

**Comment by parispittman** [comment]
https://github.com/kubernetes/community/pull/4435

**Comment by parispittman** [comment]
#4440 
/close
