### ISSUE TITLE
kubectl giving certificate signed by unknown authority on one client where working fine on other

### ISSUE THREAD

**Issue by ahsannaseem** [kubernetes/community#2689]
hey all :slightly_smiling_face:

so somehow my kubectl start rejecting ssl certificate its giving error on my mac:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: x509: certificate signed by unknown authority

kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority
```

however with same config file its working fine on centos7 machine.

i did following to resolve but didn’t succeeded:
1) uninstall and reinstall latest kubectl version
2) remove .kube dir and recreate it with config file
3) tried --insecure-skip-tls-verify=true (but again got same certificate error)

was wondering if anybody else faced same thing as its really confusing why its happening on mac and everything is fine on Linux instance.

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
