### ISSUE TITLE
404 report for k/community

### ISSUE THREAD

**Issue by castrojo** [kubernetes/community#2696]
I followed @jonasrosland 's recommendation for figuring out all the broken links in the k/community repo: https://gist.github.com/jonasrosland/7975b096fedef60c16e909e53fc79647 

There are the 4xx errors on the site. I have removed obvious note/meeting archives that don't need to be updated. 

As discussed in a contribex meeting, we'd like to group these in a way that new contributors can send in contributions, but we don't want one PR per broken link because that's too noisy, but we also don't want more than 5 fixes per PR because that's too chunky. 

We could do this multiple ways, like grouping them together and then adding them as individual issues? Or we could do it checklist style. Anyone have recommendations? 

We could probably run this once a quarter or something for maintenance. 

FILE: ./contributors/devel/cherry-picks.md
[✖] https://github.com/kubernetes/kubernetes.git&quot; → Status: 404
[✖] http://cherrypick.k8s.io/#/queue → Status: 0 Error: ETIMEDOUT

FILE: ./contributors/devel/e2e-tests.md
[✖] https://git.k8s.io/test-infra/mungegithub/mungers/submit-queue.go → Status: 404
[✖] http://ci-test.k8s.io/kubernetes-e2e-gce/10594 → Status: 404

FILE: ./contributors/devel/e2e-node-tests.md
[✖] https://git.k8s.io/kubernetes/test/e2e_node/jenkins/jenkins-pull.properties → Status: 404
[✖] https://git.k8s.io/kubernetes/test/e2e_node/jenkins/jenkins-ci.properties → Status: 404

FILE: ./contributors/devel/gubernator.md
[✖] https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/11721 → Status: 404
[✖] https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/5535/nodelog?pod=pod-configmaps-b5b876cb-3e1e-11e6-8956-42010af0001d&junit=junit_03.xml&wrap=on&logfiles=%2Fkubernetes-jenkins%2Flogs%2Fkubelet-gce-e2e-ci%2F5535%2Fartifacts%2Ftmp-node-e2e-7a5a3b40-e2e-node-coreos-stable20160622-image%2Fkube-apiserver.log&logfiles=%2Fkubernetes-jenkins%2Flogs%2Fkubelet-gce-e2e-ci%2F5535%2Fartifacts%2Ftmp-node-e2e-7a5a3b40-e2e-node-coreos-stable20160622-image%2Fkubelet.log&UID=on&poduid=b5b8a59e-3e1e-11e6-b358-42010af0001d&ns=e2e-tests-configmap-oi12h&cID=tmp-node-e2e-7a5a3b40-e2e-node-coreos-stable20160622-image → Status: 404
[✖] https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/11721/nodelog?pod=client-containers-a53f813c-503e-11e6-88dd-0242ac110003&junit=junit_19.xml&wrap=on → Status: 404

FILE: ./contributors/devel/writing-a-getting-started-guide.md
[✖] ../../docs/getting-started-guides/README.md → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/docs/getting-started-guides/README.md'

FILE: ./contributors/devel/on-call-federation-build-cop.md
[✖] https://git.k8s.io/test-infra/testgrid/config/config.yaml → Status: 404

FILE: ./contributors/devel/automation.md
[✖] https://git.k8s.io/test-infra/mungegithub/submit-queue → Status: 404
[✖] https://git.k8s.io/test-infra/mungegithub → Status: 404

FILE: ./contributors/devel/development.md
[✖] https://git.k8s.io/test-infra/jenkins/e2e-image → Status: 404
[✖] https://git.k8s.io/test-infra/jenkins/test-image → Status: 404

FILE: ./contributors/guide/github-workflow.md
[✖] https://github.com/$user/kubernetes → Status: 404
[✖] https://reviewable.k8s.io → Status: 0 Error: getaddrinfo ENOTFOUND reviewable.k8s.io reviewable.k8s.io:443

FILE: ./contributors/guide/pull-requests.md
[✖] https://git.k8s.io/test-infra/mungegithub → Status: 404

FILE: ./contributors/guide/contributor-cheatsheet.md
[✖] https://gcsweb.k8s.io/gcs/kubernetes-release/ → Status: 0 Error: ETIMEDOUT
[✖] https://cherrypick.k8s.io/#/queue → Status: 0 Error: ETIMEDOUT

FILE: ./contributors/guide/owners.md
[✖] https://git.k8s.io/test-infra/mungegithub → Status: 404
[✖] https://git.k8s.io/test-infra/mungegithub/mungers/blunderbuss.go → Status: 404
[✖] https://git.k8s.io/test-infra/mungegithub/mungers/submit-queue.go → Status: 404

FILE: ./sig-service-catalog/charter.md
[✖] https://service-catalog-jenkins.appspot.com/ → Status: 404

FILE: ./sig-multicluster/CONTRIBUTING.md
[✖] http://github.com/kubernetes/community/blob/master/contributors/design-proposals/sig-multicluster → Status: 404
[✖] http://github.com/kubernetes/community/blob/master/contributors/design-proposals/sig-multicluster/template.md → Status: 404

FILE: ./committee-steering/governance/sig-charter-template.md
[✖] https://github.com/kubernetes/community/blob/master/sig-YOURSIG/README.md#subprojects → Status: 404

FILE: ./committee-steering/governance/sig-governance-requirements.md
[✖] https://kubernetes.io/docs/imported/community/keps/ → Status: 404

FILE: ./sig-storage/contributing.md
[✖] https://git.k8s.io/kubernetes/examples/volumes/flexvolume → Status: 404

FILE: ./sig-autoscaling/README.md
[✖] https://raw.githubusercontent.com/kubernetes/client-go/master/scale/OWNERS → Status: 404

FILE: ./sig-azure/charter.md
[✖] contributors/devel/owners.md → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-azure/contributors/devel/owners.md'

FILE: ./sig-cloud-provider/CHARTER.md
[✖] https://github.com/kubernetes/community/blob/master/keps/0002-controller-manager.md → Status: 404
[✖] https://github.com/kubernetes/community/blob/master/keps/0002-controller-manager.md#repository-requirements → Status: 404

FILE: ./github-management/setting-up-cla-check.md
[✖] https://identity.linuxfoundation.org/lfcla/github/postreceive?group=284&amp;comment=no&amp;target=https://identity.linuxfoundation.org/projects/cncf → Status: 404

FILE: ./sig-scalability/processes/formal-scalability-processes.md
[✖] https://github.com/kubernetes/community/blob/master/sig-scalability/blogs/scalability-regressions-case-studies.md → Status: 404

FILE: ./sig-scalability/blogs/k8s-services-scalability-issues.md
[✖] https://cilium.io/blog/2018/04/17/why-is-the-kernel-community-replacing-iptables) → Status: 404

FILE: ./sig-scalability/goals.md
[✖] provider-configs.md → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-scalability/provider-configs.md'

FILE: ./sig-cli/migrated-from-wiki/roadmap-kubectl.md
[✖] https://git.k8s.io/kubernetes/examples/kubectl-container → Status: 404
[✖] http://kubernetes.sh/kploy/ → Status: 404

FILE: ./sig-docs/migrated-from-wiki/roadmap-docs.md
[✖] https://git.k8s.io/kubernetes/examples/guidelines.md → Status: 404

FILE: ./keps/sig-azure/0018-20180711-azure-availability-zones.md
[✖] https://azure.microsoft.com/en-us/global-infrastructure/availability-zones/ → Status: 0 Error: ESOCKETTIMEDOUT

FILE: ./keps/sig-cloud-provider/0019-cloud-provider-documentation.md
[✖] https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers/aws/docs/ → Status: 404
[✖] https://github.com/kubernetes/cloud-provider-aws/docs/ → Status: 404

FILE: ./keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md
[✖] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0003-testgrid-conformance-e2e.md → Status: 404

FILE: ./keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
[✖] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0003-testgrid-conformance-e2e.md → Status: 404
[✖] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0004-cloud-provider-documentation.md → Status: 404

FILE: ./keps/sig-node/0008-20180430-promote-sysctl-annotations-to-fields.md
[✖] https://kubernetes.io/docs/reference/feature-gates/ → Status: 404

FILE: ./keps/sig-cli/0024-kubectl-plugins.md
[✖] https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cli/kubectl-extension.md&quot; → Status: 404
[✖] https://github.com/kubernetes/community/pull/481&quot; → Status: 404
[✖] https://github.com/kubernetes/community/pull/2340) → Status: 404

FILE: ./keps/sig-cluster-lifecycle/0003-cluster-api.md
[✖] https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go → Status: 404

FILE: ./keps/sig-auth/0014-dynamic-audit-configuration.md
[✖] http://github.com/kubernetes/community/blob/master/Users/patrick/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go → Status: 404

FILE: ./sig-contributor-experience/charter.md
[✖] http://en.osswiki.info/concepts/lazy_consensus → Status: 503

FILE: ./sig-apps/agenda.md
[✖] www.github.com/kubernetes/helm → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-apps/www.github.com/kubernetes/helm'
[✖] https://deis.com/ → Status: 0 Error: ETIMEDOUT

FILE: ./sig-apps/README.md
[✖] https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/api/core/v1/OWNERS → Status: 404

FILE: ./sig-cluster-lifecycle/migrated-from-wiki/roadmap-cluster-deployment.md
[✖] http://kubernetes.io/docs/getting-started-guides/docker/ → Status: 404
[✖] https://git.k8s.io/kubernetes/docs/proposals/cluster-deployment.md → Status: 404
[✖] https://github.com/digitalrebar/kompos8 → Status: 404
[✖] https://github.com/vmware/photon-controller/tree/master/java/cluster-manager → Status: 404

FILE: ./sig-cluster-lifecycle/charter.md
[✖] ../sig-apimachinery → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-apimachinery'

FILE: ./sig-network/README.md
[✖] https://raw.githubusercontent.com/kubernetes/pkg/kubernetes/master/controller/endpoint/OWNERS → Status: 404
[✖] https://raw.githubusercontent.com/kubernetes/pkg/kubernetes/master/controller/service/OWNERS → Status: 404
[✖] https://github.com/issues?utf8=%E2%9C%93&q=team%3Akubernetes%2Fsig-network+is%3Aopen+is%3Apr+ → Status: 404
[✖] https://github.com/issues?utf8=%E2%9C%93&q=team%3A%22kubernetes%2Fsig-network%22+is%3Aopen+is%3Aissue → Status: 404

**Comment by jonasrosland** [comment]
I would personally like the checklist style for this, where contributors can pick off a group of up to 5 errors, then reference this issue and once merged it can then get updated.

**Comment by ameukam** [comment]
Can we use this issue as an exercise for the New Contributor WorkShop ?

**Comment by castrojo** [comment]
Yes, absolutely, part of the reason for doing this was to ensure that new contributors have something that would be useful to fix instead of just going after typos.

**Comment by nikhita** [comment]
Not a 404 but always catches my eye whenever I view the community-meeting doc. In the archives section - https://github.com/kubernetes/community/blob/master/events/community-meeting.md#archives - it says `2014-1016` whereas it should be `2014-2016`. :upside_down_face: 

A small change to fix this can be a good first issue for someone who wants to get familiar with our github process (prow, etc).

**Comment by soltysh** [comment]
> FILE: ./keps/sig-cli/0024-kubectl-plugins.md
> [✖] https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cli/kubectl-extension.md" → Status: 404
> [✖] #481" → Status: 404
> [✖] #2340) → Status: 404

This is working just fine, just checked.

> FILE: ./sig-cli/migrated-from-wiki/roadmap-kubectl.md
> [✖] https://git.k8s.io/kubernetes/examples/kubectl-container → Status: 404
> [✖] http://kubernetes.sh/kploy/ → Status: 404

Seems reasonable to remove for both.

**Comment by mohammedfakhar** [comment]
hi, I was looking at this issue, would also like to work on it if it's not already taken, but another even smaller issue/typo was mentioned, so I sent a PR.

**Comment by mohammedfakhar** [comment]
is it ok if I work on it? since it's a good starter issue, I won't mind if someone else picks up a file and send fix.

let me have a checklist:

 - [ ] FILE: ./contributors/devel/cherry-picks.md
   - [ ] https://github.com/kubernetes/kubernetes.git" → Status: 404
   - [ ] http://cherrypick.k8s.io/#/queue → Status: 0 Error: ETIMEDOUT

 - [ ] FILE: ./contributors/devel/e2e-tests.md
   - [ ] https://git.k8s.io/test-infra/mungegithub/mungers/submit-queue.go → Status: 404
   - [ ] http://ci-test.k8s.io/kubernetes-e2e-gce/10594 → Status: 404

 - [ ] FILE: ./contributors/devel/e2e-node-tests.md
   - [ ] https://git.k8s.io/kubernetes/test/e2e_node/jenkins/jenkins-pull.properties → Status: 404
   - [ ] https://git.k8s.io/kubernetes/test/e2e_node/jenkins/jenkins-ci.properties → Status: 404

 - [ ] FILE: ./contributors/devel/gubernator.md
   - [ ] https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/11721 → Status: 404
   - [ ] https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/5535/nodelog?pod=pod-configmaps-b5b876cb-3e1e-11e6-8956-42010af0001d&junit=junit_03.xml&wrap=on&logfiles=%2Fkubernetes-jenkins%2Flogs%2Fkubelet-gce-e2e-ci%2F5535%2Fartifacts%2Ftmp-node-e2e-7a5a3b40-e2e-node-coreos-stable20160622-image%2Fkube-apiserver.log&logfiles=%2Fkubernetes-jenkins%2Flogs%2Fkubelet-gce-e2e-ci%2F5535%2Fartifacts%2Ftmp-node-e2e-7a5a3b40-e2e-node-coreos-stable20160622-image%2Fkubelet.log&UID=on&poduid=b5b8a59e-3e1e-11e6-b358-42010af0001d&ns=e2e-tests-configmap-oi12h&cID=tmp-node-e2e-7a5a3b40-e2e-node-coreos-stable20160622-image → Status: 404
   - [ ] https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/11721/nodelog?pod=client-containers-a53f813c-503e-11e6-88dd-0242ac110003&junit=junit_19.xml&wrap=on → Status: 404

 - [ ] FILE: ./contributors/devel/writing-a-getting-started-guide.md
   - [ ] ../../docs/getting-started-guides/README.md → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/docs/getting-started-guides/README.md'

 - [ ] FILE: ./contributors/devel/on-call-federation-build-cop.md
   - [ ] https://git.k8s.io/test-infra/testgrid/config/config.yaml → Status: 404

 - [ ] FILE: ./contributors/devel/automation.md
   - [ ] https://git.k8s.io/test-infra/mungegithub/submit-queue → Status: 404
   - [ ] https://git.k8s.io/test-infra/mungegithub → Status: 404

 - [ ] FILE: ./contributors/devel/development.md
   - [ ] https://git.k8s.io/test-infra/jenkins/e2e-image → Status: 404
   - [ ] https://git.k8s.io/test-infra/jenkins/test-image → Status: 404

 - [ ] FILE: ./contributors/guide/github-workflow.md
   - [ ] https://github.com/$user/kubernetes → Status: 404
   - [ ] https://reviewable.k8s.io → Status: 0 Error: getaddrinfo ENOTFOUND reviewable.k8s.io reviewable.k8s.io:443

 - [ ] FILE: ./contributors/guide/pull-requests.md
   - [ ] https://git.k8s.io/test-infra/mungegithub → Status: 404

 - [ ] FILE: ./contributors/guide/contributor-cheatsheet.md
   - [ ] https://gcsweb.k8s.io/gcs/kubernetes-release/ → Status: 0 Error: ETIMEDOUT
   - [ ] https://cherrypick.k8s.io/#/queue → Status: 0 Error: ETIMEDOUT

 - [ ] FILE: ./contributors/guide/owners.md
   - [ ] https://git.k8s.io/test-infra/mungegithub → Status: 404
   - [ ] https://git.k8s.io/test-infra/mungegithub/mungers/blunderbuss.go → Status: 404
   - [ ] https://git.k8s.io/test-infra/mungegithub/mungers/submit-queue.go → Status: 404

 - [ ] FILE: ./sig-service-catalog/charter.md
   - [ ] https://service-catalog-jenkins.appspot.com/ → Status: 404

 - [ ] FILE: ./sig-multicluster/CONTRIBUTING.md
   - [ ] http://github.com/kubernetes/community/blob/master/contributors/design-proposals/sig-multicluster → Status: 404
   - [ ] http://github.com/kubernetes/community/blob/master/contributors/design-proposals/sig-multicluster/template.md → Status: 404

 - [ ] FILE: ./committee-steering/governance/sig-charter-template.md
   - [ ] https://github.com/kubernetes/community/blob/master/sig-YOURSIG/README.md#subprojects → Status: 404

 - [ ] FILE: ./committee-steering/governance/sig-governance-requirements.md
   - [ ] https://kubernetes.io/docs/imported/community/keps/ → Status: 404

 - [ ] FILE: ./sig-storage/contributing.md
   - [ ] https://git.k8s.io/kubernetes/examples/volumes/flexvolume → Status: 404

 - [ ] FILE: ./sig-autoscaling/README.md
   - [ ] https://raw.githubusercontent.com/kubernetes/client-go/master/scale/OWNERS → Status: 404

 - [ ] FILE: ./sig-azure/charter.md
   - [ ] contributors/devel/owners.md → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-azure/contributors/devel/owners.md'

 - [ ] FILE: ./sig-cloud-provider/CHARTER.md
   - [ ] https://github.com/kubernetes/community/blob/master/keps/0002-controller-manager.md → Status: 404
   - [ ] https://github.com/kubernetes/community/blob/master/keps/0002-controller-manager.md#repository-requirements → Status: 404

 - [ ] FILE: ./github-management/setting-up-cla-check.md
   - [ ] https://identity.linuxfoundation.org/lfcla/github/postreceive?group=284&amp;comment=no&amp;target=https://identity.linuxfoundation.org/projects/cncf → Status: 404

 - [ ] FILE: ./sig-scalability/processes/formal-scalability-processes.md
   - [ ] https://github.com/kubernetes/community/blob/master/sig-scalability/blogs/scalability-regressions-case-studies.md → Status: 404

 - [ ] FILE: ./sig-scalability/blogs/k8s-services-scalability-issues.md
   - [ ] https://cilium.io/blog/2018/04/17/why-is-the-kernel-community-replacing-iptables) → Status: 404

 - [ ] FILE: ./sig-scalability/goals.md
   - [ ] provider-configs.md → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-scalability/provider-configs.md'

 - [ ] FILE: ./sig-cli/migrated-from-wiki/roadmap-kubectl.md
   - [ ] https://git.k8s.io/kubernetes/examples/kubectl-container → Status: 404
   - [ ] http://kubernetes.sh/kploy/ → Status: 404

 - [ ] FILE: ./sig-docs/migrated-from-wiki/roadmap-docs.md
   - [ ] https://git.k8s.io/kubernetes/examples/guidelines.md → Status: 404

 - [ ] FILE: ./keps/sig-azure/0018-20180711-azure-availability-zones.md
   - [ ] https://azure.microsoft.com/en-us/global-infrastructure/availability-zones/ → Status: 0 Error: ESOCKETTIMEDOUT

 - [ ] FILE: ./keps/sig-cloud-provider/0019-cloud-provider-documentation.md
   - [ ] https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers/aws/docs/ → Status: 404
   - [ ] https://github.com/kubernetes/cloud-provider-aws/docs/ → Status: 404

 - [ ] FILE: ./keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md
   - [ ] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0003-testgrid-conformance-e2e.md → Status: 404

 - [ ] FILE: ./keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
   - [ ] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0003-testgrid-conformance-e2e.md → Status: 404
   - [ ] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0004-cloud-provider-documentation.md → Status: 404

 - [ ] FILE: ./keps/sig-node/0008-20180430-promote-sysctl-annotations-to-fields.md
   - [ ] https://kubernetes.io/docs/reference/feature-gates/ → Status: 404

 - [ ] FILE: ./keps/sig-cli/0024-kubectl-plugins.md
   - [ ] https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cli/kubectl-extension.md" → Status: 404
   - [ ] #481" → Status: 404
   - [ ] #2340) → Status: 404

 - [ ] FILE: ./keps/sig-cluster-lifecycle/0003-cluster-api.md
   - [ ] https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go → Status: 404

 - [ ] FILE: ./keps/sig-auth/0014-dynamic-audit-configuration.md
   - [ ] http://github.com/kubernetes/community/blob/master/Users/patrick/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go → Status: 404

 - [ ] FILE: ./sig-contributor-experience/charter.md
   - [ ] http://en.osswiki.info/concepts/lazy_consensus → Status: 503

 - [ ] FILE: ./sig-apps/agenda.md
   - [ ] www.github.com/kubernetes/helm → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-apps/www.github.com/kubernetes/helm'
   - [ ] https://deis.com/ → Status: 0 Error: ETIMEDOUT

 - [ ] FILE: ./sig-apps/README.md
   - [ ] https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/api/core/v1/OWNERS → Status: 404

 - [ ] FILE: ./sig-cluster-lifecycle/migrated-from-wiki/roadmap-cluster-deployment.md
   - [ ] http://kubernetes.io/docs/getting-started-guides/docker/ → Status: 404
   - [ ] https://git.k8s.io/kubernetes/docs/proposals/cluster-deployment.md → Status: 404
   - [ ] https://github.com/digitalrebar/kompos8 → Status: 404
   - [ ] https://github.com/vmware/photon-controller/tree/master/java/cluster-manager → Status: 404

 - [ ] FILE: ./sig-cluster-lifecycle/charter.md
   - [ ] ../sig-apimachinery → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-apimachinery'

 - [ ] FILE: ./sig-network/README.md
   - [ ] https://raw.githubusercontent.com/kubernetes/pkg/kubernetes/master/controller/endpoint/OWNERS → Status: 404
   - [ ] https://raw.githubusercontent.com/kubernetes/pkg/kubernetes/master/controller/service/OWNERS → Status: 404
   - [ ] https://github.com/issues?utf8=%E2%9C%93&q=team%3Akubernetes%2Fsig-network+is%3Aopen+is%3Apr+ → Status: 404
   - [ ] https://github.com/issues?utf8=%E2%9C%93&q=team%3A%22kubernetes%2Fsig-network%22+is%3Aopen+is%3Aissue → Status: 404

**Comment by maheshmahadevan** [comment]
Is there still any room for additional contributors , if yes I will like to pitch in.

**Comment by vishakhanihore** [comment]
@nikhita Is the issue up for contributions ?
