### ISSUE TITLE
Finding seconds/alternates to less active reviewers/approvers

### ISSUE THREAD

**Issue by dims** [kubernetes/community#2873]
Follow up to https://github.com/kubernetes/community/issues/1808

Here we just look at how to identify folks who are not very active and request seconds/alternates to add to OWNERS files, so PR(s) do not go stale. Making sure we add more active folks to OWNERS will help reduce burden on existing folks as well.

Find out who are listed in the OWNERS files and how many files does their id appear: (we should probably write a python script that does this better!)
`find . -name OWNERS -exec grep "\- " {} \; | grep -v "sig/" | grep -v "sig-" | grep -v "area/" | cut -f 1 -d '#' | cut -f 2 -d '-' | sort | uniq -c | sort -r | head -50`

Then I took the devstats dash board specifically the developer activity count for last year and the number of references in OWNERS files to those folks. We can download the CSV using the "Export CSV" option. The contents of this CSV is in the "Sheet 2"

See Sheet 1 for list of folks with the number of times they show up in owners files and the data about their developer activity.
https://docs.google.com/spreadsheets/d/1I6s-5Lq7Sp0ZPaqUE__ALRp7SdUDVBgC-_OuVX57-lQ/edit#gid=978045923

So now that we know we can grab some data like this. what do we do next?

- We need to do this exercise every release cycle
- We need to figure out who we need to target to ping about updating OWNERS files with additional help (and they may choose to leave themselves in or out for sure)
- We could run this by sig leads to see if they spot someone who are no longer active?
- Who should be reaching out to these folks? (A quick poll in steering indicated that we should do this kind of exercise as part of sig-contribex)
- What kind of message should be sent to those who are no longer active? 

Do we want to do this? Do we try this once and write down the process so it can be repeated?

/sig contribex
cc @parispittman @cblecker

**Comment by mml** [comment]
Hi @dims.  It seems like we have two distinct issues here.  (1) Managing review latency, and (2) ensuring the set of reviewers/owners in each file is basically correct: trustworthy or otherwise considered "worthy" by the community (with the standards outline in the community-membership doc as a low bar).

With respect to (1), I wonder if it might be better to focus the analysis on PRs rather than people.  That is, can we have a look at review latency as a function of subdirectory and determine which subdirs tend to have high levels of PRs going stale?

If we're managing contributor experience, we should probably start with the subdirectories that have the largest number of PRs or the largest number of **contributors** affected by slow reviews.  We might even preference PRs from **new contributors** in our analysis.

Starting from this angle makes the process less about people and more about fixing review latency.

For (2), I think a totally different kind of process is needed.  I have a specific idea for this, but wanted to narrow the focus to (1), since that seems to be the main goal.  (Please correct me if I'm wrong.)

**Comment by mml** [comment]
#2878 is my idea for (2).

**Comment by dims** [comment]
related to https://github.com/kubernetes/community/issues/3700
