### ISSUE TITLE
Broken link in Kubernetes Architectural Roadmap

### ISSUE THREAD

**Issue by vboctor** [kubernetes/community#2937]
The [Kubernetes Architectural Roadmap](https://docs.google.com/document/d/1VEzP20JvIKckPrGSs_R-D4vlwFzMAaqJd-9Lvfyi3jw/edit) has broken link to Kubernetes architecture overview doc in the Background section.

This document is linked to from [Kubernetes SIG Architecture meeting notes](https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit#) header via link http://bit.ly/k8sarch 

Apologies if this is not the right location to report this issue.

**Comment by nikhita** [comment]
@vboctor The google doc has since been converted to markdown. The [markdown document](https://github.com/kubernetes/community/blob/master/contributors/devel/architectural-roadmap.md#background) has the correct [link](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/architecture.md) to the architecture overview.

**Comment by vboctor** [comment]
Thanks @nikhita for the ack.  Maybe it is also worth updating the Google Doc to indicate in the header that it is now maintained in a different location and point to the markdown.  This would address cases where there are direct links to the old document.

**Comment by nikhita** [comment]
@jdumars bump about updating the link. :)

**Comment by bgrant0607** [comment]
Fixed
