### ISSUE TITLE
Create a URL shortener

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/community#2959]
...that isn't nginx.
We currently use nginx configs [here](https://github.com/kubernetes/k8s.io/tree/master/k8s.io) to create vanity URLs for kubernetes web properties, but it would be great to have something more robust, self-service, **inserts more descriptors**.

I don't have specific parameters for what we'd want this to look like, just capturing, so it doesn't get lost in [Slack history](https://kubernetes.slack.com/archives/C1TU9EB9S/p1542834583511200).

/good-first-issue
/sig contributor-experience
/cc @tpepper @BenTheElder @mrbobbytables

**Comment by ameukam** [comment]
Do we want to build something from scratch or _kubernetize_ open source tools like [polr](https://demo.polr.me/) ?

**Comment by cblecker** [comment]
/remove-good-first-issue
Definitely a help wanted, but it's not a defined enough request for gfi. There will need to be some back and forth.

**Comment by BenTheElder** [comment]
I'd actually suggest implementing it ourselves, since probably the interesting part is having a very minimal config.

A hypothetical home-grown service would just need to read the inbound URL and respond with an HTTP 301 redirect matching the config, or a 404 if there's no entry.
This could be written in a _very_ tiny bit of go and deployed to the existing k8s.io cluster, reading the config from a configmap. It doesn't need to be complex, we're not serving at crazy scales and redirects are cheap.

Most of the third party tools are going to be very nice when you want to allow creating redirects from a UI, but I think we might not want to do that since there's no easy way to track or review it. We don't want k8s.io serving redirects to malware etc, so it probably needs to be reviewable.


Ideally we'd basically never need to touch the go code or deployment, and just automate pushing the new configmap contents from the in-repo config (which prow / peribolos already have tooling for).

We'd need agreement on such a design, but if we did go this route it probably would be a good first issue at that point, it should be very simple to implement.

**Comment by cblecker** [comment]
I'm also not opposed to a commercial saas offering though, if branding/marketing wanted to be able to track the use of redirects. Find which short links are being used, and which ones aren't, stuff like that.

**Comment by BenTheElder** [comment]
Interesting. 

We do have another project with [dns management](https://github.com/kubernetes/k8s.io/tree/master/dns) in the works, which will allow similar ownership and management of the domains at some point IIRC, sounds like you might be able to lend a hand with that :-)

----

@cblecker A commercial service seems like overkill for serving some 301s / 404s imho, but perhaps not :^)

**Comment by thockin** [comment]
I'd rather kubernetize an OSS project, if we can.  We should not be
reinventing everything just for fun.

**Comment by BenTheElder** [comment]
I would agree, but I am not seeing something particularly suitable
currently.

https://polrproject.org/ (previously mentioned) seems to be the most
popular OSS one, but it's based around a PHP web UI / REST API, and
requires a SQL database.
Other projects seem very similar.

imho the ideal solution would just read declarative config from a
configmap, rather than a database, I haven't spotted anything easily
adapted to that.
We could of course write a controller to talk to one of these REST APIs,
but I suspect that's going to be more complex than serving redirects.

If we don't want the declarative config then probably we could probably
just deploy Polr somewhere today, though we probably need to think about
moderation.

**Comment by thockin** [comment]
If we *really* can't find one, then making one is fine, I guess.  It's not
like it is a complicated program.

**Comment by stp-ip** [comment]
As a sidenote the current hosted instance and the underlying git -> DNS stuff is running in K8s.

Basically:
git-sync (sidecar) pulling in a git repository with bind files + CoreDNS serving the DNS <-- our own DNS records
CoreDNS sends notifies to our DNS provider on new commits
DNS provider is fronting our CoreDNS instance for reliability and speed
TXTDirect (caddy) with autoTLS (besides the TLS certs stateless) + CoreDNS cache (sidecar) <-- txtd.io stack

Not sure, if that counts as kubernetize. Definitely happy to help.

Sidenote: We just merged our first iteration of docker vanity urls.
`docker pull c.txtdirect.org/txtdirect:dev-3fd9be`

Configuration: 
```c                  86400 IN CNAME   txtd.io.
_redirect.c.txtdirect.org.        86400 IN TXT     "v=txtv0;to=https://gcr.io/txtdirect-223710/txtdirect;root=https://about.txtdirect.org;type=dockerv2"
```

**Comment by BenTheElder** [comment]
I completely ran out of bandwidth to look into options for this further.

Totally agree we should try to find / select one to re-use first and get that setup.

We do at least have DNS managed by config now.. perhaps the TXT record redirector could be integrated with that.

Pretty sure ContribEx still wants this.
/remove-lifecycle stale

**Comment by misterikkit** [comment]
Mind if I help with this?

https://github.com/shlinkio/shlink has an MIT license, but more importantly, they have the best name and logo of any open source URL shortener.

I was able to figure out serving a "static" set of short URLs defined in the deployment yaml. Assuming the deployment yaml is checked in somewhere, we can code review new short links.

**Comment by BenTheElder** [comment]
/assign @misterikkit 
:tada:

**Comment by thockin** [comment]
Can we talk pull config from a file, so we can use configmap?  Or maybe we
can give it a helper that watches the file and send SIGHUP or something?

**Comment by misterikkit** [comment]
@thockin that's actually what I ended up doing. (https://github.com/kubernetes/k8s.io/pull/211). It currently will exit(0) on configmap change, causing a container restart within the pod. (is that an antipattern?) Causes global downtime no matter how many replicas, but it's good enough for now.


I'll subscribe to https://github.com/kubernetes/kubernetes/issues/22368 ...

**Comment by stp-ip** [comment]
Would have loved to see the now managed DNS config to be used via the TXT records, but happy to have a solution \o/.
If the decision ever comes back to do it via TXT records and TXTDirect, let me know. I'll also be at Next to discuss this in detail.

@misterikkit I definitely oppose the viewpoint on best name and logo :smiling_imp:

**Comment by misterikkit** [comment]
@stp-ip Could you explain why using DNS TXT records is a preferable solution? Is it easier to manage?

**Comment by stp-ip** [comment]
Not specifically preferable or easier. It depends on the viewpoint, but it can work with the new DNS setup and review process in k8s. The application is mostly stateless.

Additionally it might open up the avenue to not just use it for redirects but also container image urls, go pkg urls and git repos later on, if that ever wants to be controlled at the endpoint level.

It also has support for various dynamic redirects using placeholders such as splitting up redirects depending on http method, cookie or more: https://about.txtdirect.org/docs/placeholders/

A feature interesting is that DNS comes automatically with delegation. So a subdomain or subpath could be easily delegated to a sig, which controls their own DNS repo etc.

Sidepoint is that the current PoC is written in Go and based on Caddy, which enables autoTLS and additional configuration out of the box. So upstreaming changes might be easier for contributors.

**Comment by misterikkit** [comment]
Copying some of @thockin's feedback here:
> I don't know how shlink or its DB works
>
> we'd need a plan (scripted) for how to test changes before going live. We'll want a static IP assigned and in the YAML, and probably some monitoring/alerting. We'll need resource request (cpu) and limit (memory). If we want HA we'll need 2 replicas and a random backoff before terminating and restarting
>
>  It might even be better to make our own Docker image here, so we can push it to GCR and get vulnerability scans on it, which means you could un-embed the script.

Now that I have a better understanding of txtdirect, I think it does a good job of addressing these points.

- simple to understand
- simple to have a canary
  - new versions of the redirector can be run before deploying to prod
  - dns changes can be evaluated on a different domain or subdomain (presumably we already have a dns canary process?)
- easy to deploy HA because of how stateless it is

**Comment by cblecker** [comment]
Having a cursory look myself, I'm +1 on txtdirect. DNS as a database 👍

**Comment by thockin** [comment]
My grumble with txtdirect is taking a dep on a free service.

**Comment by cblecker** [comment]
As I mentioned on the PR, it's an OSS project that we can host ourselves.

**Comment by stp-ip** [comment]
As mentioned on the PR and a few additions to give more context:

OSS: github.com/txtdirect/txtdirect
OSS docs: github.com/txtdirect/website
OSS builds using the plain makefile: https://gcr.io/v2/txtdirect-223710/txtdirect/tags/list
Built on a caddy webserver: github.com/mholt/caddy

Incorporates prometheus metrics, does autoTLS and has k8s config files available on request including a sidecar DNS cache (coredns).

**Comment by thockin** [comment]
Ooops.  Sorry.  The only link I clicked took me to a hosted service.

**Comment by stp-ip** [comment]
What's the current canary process?

Happy to work with @misterikkit to get the self-hosted part setup.

So plan of action?:
* [ ] merge specific tmp subdomain go2.k8s.io to test out general/canary process using txtd.io
* [ ] get TXTDirect setup in our k8s cluster
* [ ] move tmp subdomain to self-hosted version
* [ ] test all the things \o/
* [ ] switch go.k8s.io

**Comment by thockin** [comment]
DNS Canary process is to push changes to zones "canary.k8s.io" and "
canary.kubernetes.io" and then verify that all the records we expect to
find are present.

If we add a "go.k8s.io" delegation and zone files, we'll want a similar
process.  Even if we don't do a delegation, really.

We'll also want to make sure the test covers these TXT records.

**Comment by cblecker** [comment]
The other thing we'll need is the manifests to install on our cluster.

Similar to the nginx redirector (https://github.com/kubernetes/k8s.io/tree/master/k8s.io), we'll need a deployment, service, ingress, certificate, and optionally a config map if there is any config that needs to be passed. We should have a canary and prod one, just like the current nginx redirector.

**Comment by stp-ip** [comment]
This PR is planned for next weekish.
Still trying to understand the canary.sh and if that is necessary.
Subdirectory suggested would be /redirect.k8s.io, which also serves as the DNS for the service. That way we can CNAME this on go.k8s.io first and other redirect later, if necessary. Don't wanna move things multiple times.

I'll get these PRs ready.

**Comment by stp-ip** [comment]
* /redirect.k8s.io doesn't work as it's taken.
Suggestion redirector.k8s.io instead.

**Comment by mrbobbytables** [comment]
@stp-ip do you know if there has been any traction with this by chance? :x

**Comment by stp-ip** [comment]
Slow progress especially due to us having the nginx in place.

**Comment by mrbobbytables** [comment]
kk, no worries - I just wanted to double check 👍
