### ISSUE TITLE
CreateContainerConfigError

### ISSUE THREAD

**Issue by yogipat2006** [kubernetes/community#2964]
Hi

I am using kubernetes version- GitVersion:"v1.11.2"
While deleting pod it says pod deleted successfully, but its not deleted. Pod status is -CreateContainerConfigError
Have tried below commands, but still pod is in same state-
kubectl delete pod <pod> --grace-period=0 --force --wait=false
kubectl patch pod <pod> -p '{"metadata":{"finalizers":null}}'

Can someone suggest how to fix this problem

**Comment by nikhita** [comment]
@yogipat2006 One of the common causes of this is usually an error in mounting volumes. https://stackoverflow.com/questions/50424754/pod-status-as-createcontainerconfigerror-in-minikube-cluster has some more details on how you can debug.

If the above link does not answer your questions, can you please repost your question to [StackOverflow](http://stackoverflow.com/questions/tagged/kubernetes) with more details about how you created the pod, what is the output of `kubectl describe pod pod-name`, etc? 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use StackOverflow to field support requests so your question should get answered there.

Closing this issue in favour of moving to StackOverflow.
/close
