### ISSUE TITLE
content strategy for the contributor site 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#2987]
Update: Jan 21st - I'll update this as an umbrella issue. The content strategy kick off happened on the 18th.  [Planning doc has been updated](https://docs.google.com/document/d/1_4qnfu5kNCxfO3yjaoBO6LM9KfqxGC4HnAvVakIQM-I/edit?usp=sharing) [sig contribex permissions] 

tl;dr - we are getting a small working group together (no, not official kubernetes working group on the sigs list) of folks who want to help out with a content strategy for the contributor site. Is this you?

Current state -
[KEP](https://github.com/kubernetes/community/blob/master/keps/sig-contributor-experience/0005-contributor-site.md) that is being reworked; we know that the site needs to display KEPs and events - that's a given. 
However, current KEP lists that we should surface docs from the community repo but doesn't include what-where-how-etc. After the initial development, we realized that not all of this needs to be surfaced, docs need work, and/or needs to be shaped as web content vs technical documentation (example: a blurb about our governance with a link to our entire governance doc set vs the showing the entire governance doc set). 

This content strategy piece will help us determine what content is most important, how it should be laid out, and the information goals for the site. Current team: @castrojo @mattfarina + me. Looking for ~2 more to do the following activities:
-we have lots of survey data - let's dig in and use it
-focus groups
-doc sprint to clean up key docs
-style guide (@mrbobbytables has already started on this) #2850

**Comment by chris-short** [comment]
I feel like this is something I can help with.

**Comment by markyjackson-taulia** [comment]
I can help here

**Comment by mrbobbytables** [comment]
Would be happy to help as well.

**Comment by geekygirldawn** [comment]
I'd be happy to help out. In particular, I'd love to help dig into the survey data, but I'm also happy to do any of these other items :)

**Comment by jberkus** [comment]
I can help with this starting in January, particularly funneling content both out of the NCW and the Release Team.

**Comment by parispittman** [comment]
sent a doodle poll out to folks on this list for a kick off. 

[gdoc here shared with contribex members](https://docs.google.com/document/d/1_4qnfu5kNCxfO3yjaoBO6LM9KfqxGC4HnAvVakIQM-I/edit?usp=sharing)

**Comment by markyjackson-taulia** [comment]
I didn't get the doodle poll but can help when needed

**Comment by jberkus** [comment]
So, here's a list of comparable Contributor "sites" across other OSS projects so we can look at them:

* [Mozilla](https://www.mozilla.org/en-US/contribute/) - goodness included multiple paths for engagement *including* things like "follow us on twitter" which (AFAIC) are a lovely "stepping up" to contribution pathway; up-to-date events list; the "easy" interface here (https://www.mozilla.org/en-US/contribute/signup/); this page https://www.mozilla.org/en-US/firefox/channel/desktop/#beta (so friendly).  The bad: this page (https://firefox-dev.tools/) is, I think, where the hardcore coders would start for instructions and it isn't as easy to find 
* [Fedora](https://whatcanidoforfedora.org/en#designexclamation) -- they loved this!  For a while it was impossible to find, but now it's linked nicely from the main getfedora page (yah!)
OpenMRS has a different approach in that the have a "How to contribute" book (http://devmanual.openmrs.org/en/) but I like it because it covers a lot of the non-dev-specific things like how they work and the project history *in one place* (this info is avail for many projects, but it's all spread out, so it is hard to know what things you should know before you start)
* [Ansible](https://docs.ansible.com/ansible/latest/community/index.html) Pretty dense, but we've built up a fair amount of process over the
years. Getting the right people the right info can be a challenge;
this is our best attempt, and it's pretty much ever-evolving.  [New draft version](https://docs.ansible.com/ansible/devel/community/index.html)
* Gentoo has a 'Get involved' section which itself leads to https://gentoo.org/get-involved/contribute/ that explains how one can contribute to the project. Note that we don't actually have a ton of core committers but receive significant contribution on our wiki and through our proxy maintainers project and the contribution web site is meant to detail different ways folks can get involved with the project besides just writing ebuilds.
* At libreoffice.org take a look at the "Improve it" menu on the top navigation bar. We've recently revamped this section of the web site, which acts as an entry point to all the various places people can engage, including the DevCentral portal https://devcentral.libreoffice.org/ and the Developers area of our wiki https://wiki.documentfoundation.org/Development
* FSFE has a page at https://fsfe.org/contribute/contribute.en.html which
we have overhauled just recently. Actually we've received quite positive
feedback about it, so it might help.

Some projects that have "contributor profile" pages.  This isn't something we've discussed before; is it something we'd want to do?  There is a bit of a scale problem, of course:

* [Drupal](https://www.drupal.org/u/dries)
  * Including "[people mentored](https://www.drupal.org/user/128537/people-mentored)", which is a way to encourage mentorship
* Eclipse: https://projects.eclipse.org/projects/eclipse.jdt/who
* Microprofile: https://microprofile.io/contributors/
* PostgreSQL: https://www.postgresql.org/community/contributors/

**Comment by parispittman** [comment]
also node -> https://nodejs.org/en/get-involved/contribute/

**Comment by parispittman** [comment]
oops thought this was closed 

all activities lead to the issues that are drawn out here -> https://github.com/kubernetes-sigs/contributor-site/issues

/close
