### ISSUE TITLE
question : How to configure global settings for k8s pods deployment

### ISSUE THREAD

**Issue by ankitpateledu** [kubernetes/community#3043]
Hi All

I am debugging certain behavior from my application pods; i am launching on K8s cluster. In order to do that I am increasing logging by increasing verbosity of deployment by adding ` --v=N ` flag to` Kubectl create deployment ` command.

my question is : how can i configure increased verbosity globally so all pods start reporting increased verbosity; including pods in kube-system name space.

i would prefer if it can be done without re-starting k8s cluster; but if there is no other way I can re-start.

thanks Ankit

**Comment by ankitpateledu** [comment]
@k8s-ci-robot  how do i apply label here; i dont see an option

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
