### ISSUE TITLE
Getting error when deploying container through Kubectl

### ISSUE THREAD

**Issue by amjadkhoja** [kubernetes/community#3091]
Getting below error when we deploy a container from Kubernetes.
Window Worker Node is Windows server 2019 build 1809 
Container image is mcr.microsoft.com/windows/nanoserver:1809  or any other image (tried with different images still same error)

Error response from daemon: CreateComputeSystem 94d1c5e13d7201f47af54f676d0a6c3220f4cdc70a02cb9398b11cc5dc189ae5:
The container operating system does not match the host operating system.

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
