### ISSUE TITLE
sig-aws meeting info out of date

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3111]
I showed up to what I thought was the weekly Friday meeting of sig-aws at 9am PT Friday, and was told it was the kops office hours.  This isn't documented in https://github.com/kubernetes/community/tree/master/sig-aws

Kops office hours are documented in https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle, so it seems like sig-aws is where the docs update needs to occur

/kind documentation
/sig aws
/assign @justinsb @kris-nova @d-nishi 
SIG AWS chairs

**Comment by d-nishi** [comment]
@spiffxp -- the confusion is because the same zoom meeting link is used for KOPS office hours.

Otherwise KOPS currently is a SIG Cluster Lifecycle subproject.

Did you want us to specifically add a date in the documentation starting Jan 2019? This is not a consistent model for all the SIGs hence the question. Also, we do have a calendar for SIG AWS that adds a meeting invite for anyone who is part of the google groups. Do you have a different suggestion that I am missing?

**Comment by spiffxp** [comment]
Guess what, I can't read.  You absolutely did call out the sig-aws meeting as biweekly, not weekly, and I was totally in the wrong.

But the PR is helpful, since I try to avoid being subscribed to literally all sig calendars.

**Comment by spiffxp** [comment]
It would have helped me, yes.  If you want to push back a hard no I will understand

**Comment by d-nishi** [comment]
Done!

**Comment by nikhita** [comment]
Looks like this is done.

> Kops office hours are documented in https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle, so it seems like sig-aws is where the docs update needs to occur

Regarding this, kops is a subproject for SCL so I guess it makes sense to have it there. If not, please open a follow-up issue to move it from SCL to sig aws.

Closing. Please reopen if needed.
/close
