### ISSUE TITLE
Waiting for federation control plane to come up............ is been running for the past 17h 

### ISSUE THREAD

**Issue by armin-arcules** [kubernetes/community#3150]
Very much new to federation, I have a local kubernetes cluster and a GCP kubernetes cluster, I've been following the  https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/#before-you-begin for setting up the host federation on my GCP cluster. 
After running the following command kubefed init fellowship     --host-cluster-context=gke_sandbox-***_**-***_***-cluster     --dns-provider="google-clouddns"     --dns-zone-name="****.tech."

Creating a namespace federation-system for federation system components... done
Creating federation control plane service............... done
Creating federation control plane objects (credentials, persistent volume claim)... done
Creating federation component deployments... done
Updating kubeconfig... done
Waiting for federation control plane to come up............................................

never ends. 
I have no idea what I should be looking into in terms of what might have been faild or what is not running.
Any guide would be useful (USING V2)
Thanks 

/wg k8s-infra
/sig contributor-experience

**Comment by armin-arcules** [comment]
federation-system   apiserver-7bfd59c99b-s4vkj                          1/2     ImagePullBackOff   0          30m   10.32.0.30   gke-armin  <none>
federation-system   controller-manager-754d5945b6-674v9                 0/1     ImagePullBackOff   0          30m   10.32.0.31   gke-armin-cluster   <none>

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
