### ISSUE TITLE
Kubernetes Slack admin policy on User Groups feature

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/community#3155]
I am interested in using Slack's User Group's feature:
- https://slackhq.com/introducing-user-groups
- https://get.slack.help/hc/en-us/articles/212906697-Create-a-user-group
- https://get.slack.help/hc/en-us/articles/115004952926-Manage-permissions-for-user-groups

Use cases that would help me:
- I am the release team lead, and I want to ping `@k8s-release-team` rather than have to copy paste a list of names.  I would rather not use a separate channel "#release-team" because that could confuse contributors over which channel they should go to talk about release related stuff.
- I am a contributor and would like to ping `@k8s-testinfra-oncall` when prow seems down instead of having to look at go.k8s.io/oncall and figure out what slack username corresponds to that github user and ping them directly

Currently the [Slack Admin Guidelines](https://github.com/kubernetes/community/blob/5060a2e50c8cbe052dff5cdd0bfb48334be39b07/communication/slack-guidelines.md) say nothing about whether this feature is supported or not.  The Kubernetes Slack admin team would like to have a broader discussion about whether this is something the Kubernetes Slack admin team wants to support.

Concerns that were raised in the [#slack-admin thread where I asked about this](https://kubernetes.slack.com/archives/C4M06S5HS/p1548440343116000?thread_ts=1547831577.065000&cid=C4M06S5HS):
- This would increase admin burden (suddenly everyone wants a user group)
- This would increase notification noise (I'll just spam the release team constantly)

/sig contributor-experience
/area community-management
/assign @castrojo @parispittman @jdumars

**Comment by justaugustus** [comment]
FWIW, I'm a +1 for user groups as well. I had asked about it a while back here for SIG Chairs/TLs. Being able to do things like `@sig-azure-leads`, "Hey `@rt-114`, are still on track for x date?" would be super useful.

You can address the intended audience without having to go figure out who that might be in k/community or somewhere else.

**Comment by parispittman** [comment]
I asked CNCF to set up a call with slack. We are very conservative with slack because of past bad experiences with bots and automation. My main concern is the members of the user groups high volume notifications since they are treated the same way as mentions.  (my empathy is showing)

re: dims - we have the github bot enabled that will allow us to get notifications in a slack channel when someone files and issue or a PR is merged so we can get the membership info. The slack API has a create user groups method but I can't find anything that is already pre-built that we can use so this would most likely need to be custom made. 

I'm ok with treating release as a test case for this. Based on my research, doesn't seem to have any net negatives on the community as a whole like some bots do and I'd happily turn it off if the test group thinks the notifications are out of control and hard to keep up with. I'd like to see two other admins weigh in with +1 since this is a new feature we are putting into a test playground.

**Comment by spiffxp** [comment]
@dims 
>is it possible for this to be automated like our github org membership

This is the dream.  My cursory glance when I suggesting this for an oncall alias was... there's nothing off the shelf out there, so it'd have to be homegrown.  

We do have prow posting manual-merge notifications, but I'm willing to be sensitive and understanding around any more intrusive API access as its maybe not as well understood as GitHub.

**Comment by nikhita** [comment]
We use this for `test-infra-oncall` today. We also have some automation around that: https://github.com/kubernetes/test-infra/tree/master/experiment/slack-oncall-updater.

Are we ok with allowing others (not just test-infra-oncall) to use this feature as well? In that case, what else needs to be done? Right now I see:

- improve automation so that we can have a yaml config as the source of truth for who is a part of the slack user groups
- add policy and process documentation around this

/kind feature
/priority important-longterm

**Comment by Katharine** [comment]
We now have automation driving this, controlled by configuration in [communication/slack-config](https://github.com/kubernetes/community/tree/master/communication/slack-config). This configuration is now the only valid way to manage channels or usergroups. The automation also opens the door to enabling groups outside the slack admins to manage a subset of slack resources without admin involvement (such as, for instance, letting sig-release manage `release-team-*` usergroups but nothing else, or letting sig-docs manage arbitrary `#kubernetes-docs-*` channels, etc.).

Policy remains an open question here. Personally, I generally lean strongly towards flexibility.

**Comment by castrojo** [comment]
I'm in favor of keeping an open/loose policy while we figure out the best way it will work in practice.

**Comment by parispittman** [comment]
i know the slack team does user groups now so i think this issue can be closed. 

@spiffxp - are you good?

**Comment by Katharine** [comment]
Pretty sure our policy on this is "user groups are cool, PR them if you want them."

/close
