### ISSUE TITLE
Audit wiki permissions

### ISSUE THREAD

**Issue by cblecker** [kubernetes/community#3301]
Ensure all repos that have a wiki enabled, have it locked down to those with write access.

/cc @kubernetes/owners
/area github-management
/sig contributor-experience

**Comment by nikhita** [comment]
Using queries like https://github.com/search?p=1&q=org%3Akubernetes&type=Wikis to search wikis, these are the repos which have Wikis enabled.

For the repos that had public access, I have flipped the setting and locked it down to those with write access.

**Kubernetes**:
- website
- client-go
- kubectl
- dashboard
- kubernetes-anywhere

Out of these, dashboard had public access.
cc @maciaszczykm @floreks @jeefy @danielromlein 

**Kubernetes-SIGs**:
- cri-o
- node-feature-discovery
- aws-ebs-csi-driver
- kubespray
- kube-batch
- cluster-api-provider-azure

Out of the following, the following repos had public access.
- node-feature-discovery
   - cc @balajismaniam @ConnorDoyle @flyingcougar @marquiz 
- kubespray
   - cc @ant31 

**Kubernetes CSI**:
- docs

**Kubernetes Incubator**:
- service-catalog

Kubernetes Client does not have any wikis.

---

Ideally, we should not be using wikis since it isn't contribution-friendly but that's another issue...

Closing this as all repos with wikis have been audited and those with public access have been locked down.
/close
