### ISSUE TITLE
Need full access to Project for entire Shanghai Team

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#3339]
@parispittman @mrbobbytables @nikhita 

The whole Shanghai team needs to have full edit rights for the SCN Project.  That includes:

@chenrui333 @idealhack @chris-short @xiangpengzhao, and Puja, whose GH handle I can't find at the moment.  Thanks!

**Comment by nikhita** [comment]
All the contributor summit project boards are repo-level project boards scoped to the community repo. To give access to the project board, members would need to be given write access to the repo (which we'd like to limit in general).

I had discussed about migrating this to an org-level project board in #3272. I'm happy to do the migration too, if that helps.

I'd like to get an ack from @parispittman that we can move all boards from the community repo to an org-level board so that other members can be given write access, before I make any changes.

**Comment by idealhack** [comment]
Puja's handle is @puja108.

@nikhita Thanks for your help, I think we can use an org-level project board and migrate the existing one.

**Comment by idvoretskyi** [comment]
Org-wide board is created - https://github.com/orgs/kubernetes/projects/20.

**Comment by idvoretskyi** [comment]
@jberkus FYI - every member of the Kubernetes org is able to edit the [project](https://github.com/orgs/kubernetes/projects/20).

@chenrui333 @idealhack @chris-short @xiangpengzhao, and @puja108 are already the members, so they should have access. Please, let me know if you have any questions.

/close
