### ISSUE TITLE
barcelona contrib summit content proposal

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3342]
send steering committee and chairs the content proposal for barcelona contributor summit and ask for buy-in and suggestions

**Comment by geekygirldawn** [comment]
I think this might be a partial duplicate of Issue #3273. That issue says to do a PR to add the content proposal to https://github.com/kubernetes/community/tree/master/events/2019/05-contributor-summit Should I do the PR first, and then we can send that link out for feedback, instead of the Google Doc?

**Comment by parispittman** [comment]
dup; closing

/close
