### ISSUE TITLE
Autoscaler Daemonsets List error Forbiden

### ISSUE THREAD

**Issue by rlinstorres** [kubernetes/community#3611]
Hi, all!

My provider is AWS and I installed autoscaler version v1.14.0 with helm and the service with error:

`E0417 20:31:09.515269       1 reflector.go:126] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:319: Failed to list *v1.DaemonSet: daemonsets.apps is forbidden: User "system:serviceaccount:kube-system:aws-cluster-autoscaler" cannot list daemonsets.apps at the cluster scope`

What's the problem?

Thanks!

/help
/sig contributor-experience

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum or Stack Overflow to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/triage support
/close
