### ISSUE TITLE
CPU is always 100 % on Kubernetes cluster

### ISSUE THREAD

**Issue by charuni2018** [kubernetes/community#3712]
Hello,

We are performing some PoC and trying to running some batch jobs concurrently but what I am noticing that CPU of 3 nodes cluster is always close to 100 % How I can I dig down further to see what is causing the CPU to reach its 100% CPU. Memory seems to be good .

$ kubectl top nodes
NAME                                   CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
0fd259ac-694b-483b-a50a-956a4c475c1e   1997m        99%       4748Mi          60%
16d4cb78-5b5b-4eb2-8999-694a7d4e53a9   2002m        100%      3978Mi          50%
811b2e20-5b45-43c0-b470-a65f8559ac29   2001m        100%      3945Mi          50%

**Comment by spzala** [comment]
@charuni2018 for a quicker response and help, please ask such questions on Stack Overflow as described below or on kubernetes-user slack or mailing list. 

Please re-post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
