### ISSUE TITLE
Pay for, or move away from Slack

### ISSUE THREAD

**Issue by colemickens** [kubernetes/community#372]
Would it be possible for the CNCF to pay for Slack?

If not, has there been consideration of using another platform? I'm repeatedly finding that rooms or private messages have little-to-no history from even just a few days ago because of the volume in Slack.

Or maybe I should try to find an alternative client that stores extra scrollback locally?

I realize this is huge can of worms and it would probably be a huge pain to move away from Slack for a lot of reasons, but I thought it might be worth discussion.

**Comment by resouer** [comment]
Just my two cents: I love slack >_<

**Comment by k82cn** [comment]
How about email group or google group? But it need member to simplify the conversation :).

**Comment by feiskyer** [comment]
@colemickens All public channels are archived at http://kubernetes.slackarchive.io/

**Comment by sarahnovotny** [comment]
hi!  we have approached slack about paying for the service.   We were unable to negotiate the non profit rate.  there has been a pricing change since that earlier conversation which led to a prohibitively expensive rack rate conclusion, but even with that change slack for the k8s organization would be ~$225k per year for our current active user base.  I'll reach out to the CNCF again to see if there is another solution.

**Comment by caniszczyk** [comment]
From a CNCF/LF POV, we tried to negotiate with Slack multiple times but haven't been successful and are definitely open to other services depending what the k8s community desires.

On a related note, one of the other LF foundations with a fairly large and active Slack recently moved to RocketChat (https://rocket.chat/), Hyperledger.org: https://chat.hyperledger.org/

**Comment by stp-ip** [comment]
There is also Mattermost (https://about.mattermost.com/), which might be technologically more aligned (using go) and might even look into k8s deployments due to their gitlab involvement. cc @coreyhulen

**Comment by kris-nova** [comment]
IRC +1

**Comment by Miyurz** [comment]
IRC +1 I know even the ansible guys are there

**Comment by mindfulmonk** [comment]
IRC +1

**Comment by tazjin** [comment]
IRC +1

**Comment by timothysc** [comment]
kind of a +1 on matter most, and we can force dog-food it as a kube service ;-)

**Comment by davidchua** [comment]
+1 for Mattermost as get to support another opensource project and at the same time get similar functionality to Slack.

**Comment by mgoodness** [comment]
There's https://riot.im/ as well.

**Comment by derekwaynecarr** [comment]
I am going to defend Slack and say i have been able to get responses in
more timely fashion since we adopted it, and integration with mobile is
easy enough that it helps me engage when away from desk.

On Sat, Feb 18, 2017 at 10:19 AM, Michael Goodness <notifications@github.com

**Comment by liggitt** [comment]
> I am going to defend Slack and say i have been able to get responses in more timely fashion since we adopted it, and integration with mobile is easy enough that it helps me engage when away from desk.

Agree. Notifications and cross-machine access "just works".

**Comment by rothgar** [comment]
I support moving away from slack. While I love IRC it doesn't have a lot of the modern features expected for a public chat of this size.
Mobile access, alerts, and on the fly group private messages are difficult for users to set up and would greatly limit the amount of support available.
I don't think paying for slack would be worth the features it provides over the other chat options.

We can do a comparison of the different options to see which we prefer. A transition would be very hard but better in the long run IMO.

**Comment by tazjin** [comment]
IRC gives users the ability to take care of those things on their own, using for example tools like [IRCCloud](http://irccloud.com/). This would provide all the same benefits as Slack without locking users in to it.

More advanced users (which I'm sure we have many of) can use their normal tools that they already use with _most other open-source projects_.

**Comment by mrhillsman** [comment]
https://rocket.chat/

**Comment by phenomenes** [comment]
IRC +1

**Comment by kmbannerman** [comment]
I would donate $ personally for a paid slack. The reach is much better vs. an older client like IRC (haven't used IRC in 8-9 years). 

Another option: Companies contributing to K8s pitch in

Agree 100% with Joe Beda's tweet re: IRC is a barrier for new users, as well. I have loads of feels and reasons, but his thoughts sum mine up.

**Comment by caniszczyk** [comment]
@kmbannerman the problem is cost and lock in, the money could be better going towards an open protocol + community that is willing to work with us. At the Linux Foundation we've had success with RocketChat (or just vanilla IRC) and at the Eclipse Foundation Mattermost works well.

I echo @rothgar and whatever is done we should make sure a solid comparison is done and that the community is involved each step of the way. Lets use something that will be good for the long run.

**Comment by liggitt** [comment]
> IRC gives users the ability to take care of those things on their own, using for example tools like IRCCloud. This would provide all the same benefits as Slack without locking users in to it.

I have no allegiance to slack, but requiring users to wire up additional services on their own to get basic function like omnipresent notifications seems is less than ideal. 

> More advanced users (which I'm sure we have many of) can use their normal tools that they already use with most other open-source projects.

Doesn't slack have an IRC gateway for users that want to use only IRC?

**Comment by dgoodwin** [comment]
+1 for mattermost or rocket. 

I'd be personally completely happy with IRC as I'm there anyhow, but I can't argue it's an equivalent experience and it hasn't aged particularly well.

**Comment by viglesiasce** [comment]
Folks,

This thread will be unproductive until we break out other issues that define the issues that people are having with slack. Otherwise we will boil the ocean. 

I believe that one of the main ones is persistence of channel history. That can be solved much more easily and with less disruption than switching away from slack.

**Comment by it33** [comment]
Mattermost team here, thanks for the mentions. Just some thoughts: 

1. You can use IRC with Mattermost using https://github.com/42wim/matterbridge, use #matterbridge on IRC to try it out. 
2. Eclipse, Mozilla, Cern, Redhat, Penn Manor, University of British Columbia, and many other open source and non-profit orgs run Mattermost and we have lots of orgs contributing back in different ways 
3. You can see how Mattermost works managing its own open source community at https://pre-release.mattermost.com/. Note: This is out nightly builds server, for a stable version you can check out https://demo.mattermost.com/ (though it's less active. 

Also, on Monday, there's a soft launch of a Bitnamni Mattermost stack, which will make deploying Mattermost even easier.

**Comment by rdodev** [comment]
I've had lengthy arguments about FOSS communities in Slack, in general, before (completely orthogonal to this issue at hand). I dislike the idea of walled FOSS communities (and the crazy proliferation of community-specif slacks). So my vote would go to IRC in this instance.

Another aspect I see here is cost, which as said above is, as of now, $225K/yr. And I would posit that money could be better used for outreach, scholarships and financial aid to attend community events for those who can't afford it and minority/marginalized folks.

However -- and this is a HUGE however -- I put community before of any one's thoughts or opinions, including my own. So if the K8s community, at the end of the day, decided to stay in Slack or move it makes no difference to me.

**Comment by vmtyler** [comment]
I echo others that say just straight IRC is a huge barrier to entry to FOSS communities. I do get the annoyances of slack proliferation, and obviously cost is a big issue here. It's worth checking out solutions (both with slack and others) but I'd be against a move to IRC.

**Comment by jbeda** [comment]
Breaking news here: https://twitter.com/stewart/status/833031230161637379

It looks like Slack opened up their non-profit offer to 503(c)(6)s and so the LF/CNCF/k8s slack should hopefully be covered.

As for the larger discussion -- when we switched from IRC to Slack (I'm the one that made the call) it was in an effort to make the community more accessible to more people that weren't steeped in the OSS culture.

IRC has a lot going for it but, IMO, you to commit to learning it (and picking a client, and figuring out nicks, and understanding federation and...) before you can participate.  Even then it takes a while to feel natural.  While there are some good clients out there that smooth over these issues, many of them are commercial and put the cost on the user.  (IRCCloud was the hotness when we switched over).

When we picked Slack, there weren't a lot of slack-like alternatives out there.  Not sure what we would pick if we were going to do the same evaluation today.

So -- given the fact that it looks like we can get a "full" version of Slack and remove the immediate pain points, I'm hopeful that we can put this issue to bed.  If someone does want to propose moving to something else we should look at it on a point by point basis and figure out if it is worth the disruption.  IMO, IRC fails on multiple dimensions but we should debate that separately.

**Comment by davidopp** [comment]
If we switch (which it now sounds like we won't) we should at least start with a list of requirements as Vic alluded to. Must-have, vs. nice-to-have, vs. don't-care. Mobile and notifications are the killer features for me for Slack (and a few people mentioned this also upthread). I tried various IRC client software back when we were using IRC and never found anything remotely usable.

**Comment by brendandburns** [comment]
https://xkcd.com/1782/

(someone had to do it...)

**Comment by rektide** [comment]
I'm hugely in favor of IRC, but it definitely requires more than "here's our IRC" to make that happen. Kubernetes, if it does want to move way, should run some web clients that people can use, and it needs to run some of the logging services available. Otherwise it's not an upgrade imo, it's just a new color for the bikeshed- a more classic color but one that wont work for everyone. I think we can meet those people easily by supporting a Kubernetes webclient for accessing Kubernetes channels.

> This thread will be unproductive until we break out other issues that define the issues that people are having with slack. Otherwise we will boil the ocean.

> I believe that one of the main ones is persistence of channel history. That can be solved much more easily and with less disruption than switching away from slack.

https://github.com/kubernetes/community/issues/372#issuecomment-280865186

Ok. I'll bite. How? I've never seen Slack do any kind of 1/10000th way decent historical archive. It's always scrolling up and up and up as far as I've seen. No way to run regex expressions against history, no way to go back to a month. Slack seems like it's for throw-away communication.

I also loath that Slack is a massive hit on memory to keep a tab of it open. I run almost two hundred channels of IRC on the same box that my mailserver is on, and that box has 256MB of memory, while giving me history I can grep through. And I have to page through different slack tabs, versus irc where I can have one client connect to many services.

**Comment by v1k0d3n** [comment]
i admit, i didn't read through most of the comments...

why are people forgetting about the IRC and XMPP features in slack? right, so it's not exactly ideal...but i use an IRC client with slack, and it works just fine.

- [x] manage the logs yourself
- [x] use your same IRC client (hexchat, pidgin IRCCloud)

not sure what the fuss is about here.

**Comment by rdodev** [comment]
@v1k0d3n the $225K/yr bill was a big motivator for this thread -- it's what started it, actually.

**Comment by JpMaxMan** [comment]
+1 IRC and for the modern interface irccloud.com

**Comment by lattwood** [comment]
2¢: If the k8s slack didn't exist I wouldn't have contributed to the k8s ecosystem. https://github.com/NickelMedia/efs2sky

**Comment by Philmod** [comment]
What about creating a collective on https://opencollective.com, and finance Slack cost from the community?

**Comment by timoreimann** [comment]
@Philmod Please read https://github.com/kubernetes/community/issues/372#issuecomment-280870270 -- it looks price is not going to be an issue anymore.

**Comment by ashb** [comment]
I don't think this has been mentioned yet, but the signup barrier to Slack is non-zero: You have to use the hack to get an invite , go through an email confirmation etc. With a web-based IRC client you can click and get an (anon) session and start chatting if that's your thing.

**Comment by nhlfr** [comment]
IRCCloud in free version has an unlimited history log and possibility of using a mobile app. Creating IRCCloud account isn't very different for creating an account on any website. At the same time, IRCCloud brings a feature we're mostly concerned about - an access to history.

What @ashb wrote is so true. The most of people interested in k8s discussions are sysadmins and developers who already use IRC and instead of joining the channel, they need to click through web interfaces.

And if somebody is not using IRC at all, then well, I think that using IRCCloud needs **exactly the same effort** as installing Slack and clicking through it, IMO it's not really harder.

Also, with IRC it's very easy to create some website with logs and give a possibility to search in them in the more comfortable way that in Slack.

**Comment by tazjin** [comment]
> Also, with IRC it's very easy to create some website with logs and give a possibility to search in them in the more comfortable way that in Slack.

Technically I believe we could use the Slack IRC bridge to do the same (and I think there has been an effort to do that?), but it may violate the Slack EULA.

**Comment by davidopp** [comment]
I used IRCCloud back when the project used IRC (I even got the pay-monthly version) and I find that Slack is a lot more usable.

But as @timoreimann pointed out, it sounds like the money issue may be solved now, in which case this discussion presumably is too. Maybe we should suspend the discussion until we hear whether the money issue is actually resolved.

**Comment by bgrant0607** [comment]
As jbeda mentioned, we originally used IRC, and moved away from it. It had many downsides: diverse and inconsistent client experience, email notifications and other features were DIY, frequent connectivity problems, difficulty in managing channels, discoverability problems, archives at least as obscure as our current slack archives, and more. I can't envision moving back to IRC.

We did evaluate alternatives, including mattermost and gitter.im, and slack appeared to be simplest and have the most uptake.

Hopefully, the $$$ issue for Slack archives will truly be resolved (their per-team-member pricing model is simply prohibitive for a large open-source project). Failing that, mattermost appears to be the most likely alternative.

**Comment by colemickens** [comment]
Thanks for the update @jbeda. I'm going to close this with the presumption that Slack will grant the non-profit plan for https://kubernetes.slack.com.

**Comment by mindfulmonk** [comment]
Is there an update on this?

**Comment by caniszczyk** [comment]
https://www.cncf.io/blog/2017/03/01/slack-gives-back-k8s-cncf-community
