### ISSUE TITLE
[doc update] speed mentoring

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3744]
update the speed mentoring doc in /community/mentoring

include:
- [ ] where and how people can sign up to be a mentor or mentee at a future event
- [ ] explain "pod mentoring" vs 1:1
- [ ] talk about expectations
- [ ] delete past information and make this doc about the process and less about specific upcoming events

**Comment by celanthe** [comment]
@parispittman If you need help with writing this, I am happy to take a crack at writing some of this for you if you can get me the building blocks/background information!

**Comment by scottilee** [comment]
@parispittman should [community/mentoring/mentoring-events.md](https://github.com/kubernetes/community/blob/master/mentoring/mentoring-events.md) be renamed to `speed-mentoring.md` or should it be deleted and a "Speed Mentoring" section be added to [community/mentoring/mentor-guide.md](https://github.com/kubernetes/community/blob/master/mentoring/mentor-guide.md)?

Could you also provide resources on "pod mentoring"? I did a search of `/community` and couldn't find reference to it in the repo or issues except this ticket. I'm assuming it's group mentoring (2+ people instead of 1:1).

Additionally, are there any other resources that have already been started or even outdated that can be referenced to get started on this doc?

**Comment by parispittman** [comment]
hey scott - so sorry this fell off my radar. 
for the checklist above:
1- lets let folks know that they will have to register for kubecon/cloudnativecon in $city in order to attend and that links to registration will be posted 1-2 months before the event on the co-located events page. 
2- correct on the pod mentoring assumption. i wanted to outline that we do this for a few reasons:
- no one person knows everything, having it in a group means that at least one will know at minimum a resource to go to for more information
- 1:1s can get awkward for folks
- we will always have an anchor in the pod - meaning someone that is has signed up to be a mentor specifically who can help guide the conversations

here is the language that we used on the form for "anchors":
Are you part of a SIG? An ambassador of a cloud native project and want to help others with using or contributing to your project? An expert consumer of a cloud native project? Code committer? A documentation writer? We’re looking for mentors of all backgrounds and experience levels (including new folks!) across the entire ecosystem with technical, community, and career experience to sign up for one or both sessions. We will provide you with FAQs of attendees upfront so you know what to expect.
Pease complete the information below to sign up to be a mentor for the Networking + Mentoring Session(s) during KubeCon + CloudNativeCon Europe.  

You'll sit in a small group vs 1:1 so that awkwardness is reduced and because you don't know everything. 🙂 We tried the small pod (pun intended) approach in Seattle and Barcelona with success. Saying "I don't know but let's figure it out together.." is a fine response. Four survey responses from the Seattle event included mentors describing that they learned more than their mentees and it was a great experience!
