### ISSUE TITLE
Formulate a process/plan for a "Travel Support Program"

### ISSUE THREAD

**Issue by dims** [kubernetes/community#3783]
CNCF has a "Diversity Scholarship" program. This program has been very successful. However there are some folks who were not able to take advantage of the program either because of budget limitations or unable to qualify for some other reason. Some of these folks are active contributors for example with sig-release or some other SIGs or working groups. It would be in our community's interest to ensure we have a way to fund travel for active contributor(s) who cannot get backing from their employers for some reason or another. This program should be an adjunct to and not a replacement for the CNCF led program. We should aspire to make the process as transparent as possible. We should look to other projects like nodejs[1] and OpenStack[2] who run such programs as templates but ensure that it works for us here.

We need a process, a plan and a budget to start with. I'd request sig-contribex to start thinking about this and hopefully come up with something for the upcoming Kubecon

[1] https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md
[2] https://wiki.openstack.org/wiki/Travel_Support_Program

**Comment by dims** [comment]
Things to think about:
- How do we make sure folks who are applying for Diversity scholarship and various SIGs in kubernetes in general are made aware of this program?
- How do we work in concert with the folks running the Diversity scholarship program especially around privacy thats needed for that program?
- Would it make sense for a contribex member to be part of the Diversity scholarship program to make it happen?

Here is the current questionnaire for the Diversity Scholarship program:
https://www.surveymonkey.com/r/GYMV3PV

**Comment by nikhita** [comment]
xref - https://github.com/kubernetes/steering/issues/46 (Funding and Budgeting)

**Comment by dims** [comment]
Important detail about current process for exceptions from @dankohn in the email thread.

```
CNCF has a diversity scholarship committee made up of a rotating group of several volunteer community members. However, we have many more applications than we do scholarships, despite running (what we believe to be) the largest diversity scholarship program of any conference.

In addition, we have travel funding available for speakers and other key community members when their companies do not provide funding. In the past, community leaders have made requests to me, Chris Anisczcyk, or events AT cncf.io and we have generally been able to accommodate them.

Also, note that diversity scholars are not identified on their badge or anywhere else and that participating in any programs (like the on-stage picture) is completely optional.
```

**Comment by parispittman** [comment]
when we initially discussed this in contribex, i had forked nodejs's travel funds and started playing around with it in notepad to change some things for us. https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md

putting a copy of that here so i can delete it from mine:)

node does reimbursements and i think i heard some comments that folks didn't have money to float upfront so copy here is reflecting upfront. if we had a private repo with the info and a 2nd issue only repo we could do something like this:

# Kubernetes Contributor Travel Fund

## Purpose

To establish and administer a fund for members of the Kubernetes upstream contributor community to travel and particiate in KubeCon/CloudNativeCon.

## Requirements

* Candidates must be a member of the Kubernetes GitHub or or working towards it. [link to community-membership.md]
Exceptions: TODO

* Those requesting funds must indicate that they do not have funding available from another source, such as an employer or 
the event itself that might cover costs for presenters.

## Process

Submit an issue to a Kubernetes Travel Fund Issue-Only repository. Your issue will go into a private repository where only $certain_group can see your information due to privacy. 

Requests must be made three months before the event. Requests submitted after that will not be approved. 

It is strongly recommended that you submit your request far enough in advance to get approval before making relevant expenditures. 
Review of requests will take at least 72 hours and may take considerably longer. Note, with limited funds available, approval is not 
guaranteed. 

## Visa Tips

For all events, it is recommended to apply for a visa at least 6 months prior. 


## Requesting Travel Funds 

* Open an issue template, the results go to a private repo that only a $certain_group of people can see. 
  * You'll be asked:
    * Your Name
    * The name of the event you plan to attend.
    * The location, dates of the event and where you will be traveling from.
    * The presentation you intend to give, if applicable.
    * The size of the stipend you wish to receive.

## Approval

A request is approved when all of the following criteria are met:

* The request has approval from at least two members of the $certain_group 
* No members of $certain_group objected to the request.
* The issue has been closed. 

An appointed treasurer from the $certain_group will liaise with a member of CNCF on a regular basis to review the status of the travel fund. In the event that any pending 
requests might not be approved because of available funds, a separate issue will be raised. Generally speaking, however, 
members shouldn't need to worry about the status of the fund itself.

### Considerations for approval of a request

If there are too many requests for the limited funds, we will measure the following:

#### Impact  

* Preference is given to speakers, panelists, and those volunteering onsite at the conference.
* How much you contribute to the project. 

#### Outreach
* Preference is given to underserved communities. 

#### Cost
* The larger the stipend the more critically the travel fund admins will consider the request and application. 
The budget for this program is a finite resource.

#### Equity
* Preference is given to individuals who cannot receive travel funding from their employers or individuals who have not 
previously received a stipend.

## Blog post

After the trip, write a blog post about your experience! (this is optional)


## 2019 Allocation

The request from Technical Steering Committee and the Community Committee for a 2019 joint travel fund 
was approved in the amount of $xx

Please direct any questions or concerns about the travel fund to [contributors@](mailto:email)

**Comment by nikhita** [comment]
@parispittman This is AMAZING! Thank you so much! :heart_eyes: 

> Review of requests will take at least 72 hours and may take considerably longer. 

What would happen if someone "more deserving" applied later, but before the three month mark? Instead, would having a deadline + reviewing all requests together (like the diversity scholarship) help in that case?

> For all events, it is recommended to apply for a visa at least 6 months prior.

To apply for a visa, one needs to have the conference ticket + flights + accommodation bookings. Unfortunately, this won't work if we announced the results ~2-3 months in advance. :(

I think if we change the "apply for visa" deadline to 3 months _and_ announce the results 3 months in advance, that would work. Visas can be procured within 3 months as well (6 months is nicer, but not necessary). :+1:

**Comment by dims** [comment]
Paris,

This looks good! Can you please open a PR against kubernetes/steering (and an email there) so we can may be word smith it a bit more and get it approved?

Thanks,
Dims

**Comment by castrojo** [comment]
https://github.com/kubernetes/steering/pull/114

**Comment by nikhita** [comment]
Freezing this one since I don't know when we'd be able to travel again :cry: 
/lifecycle frozen
/milestone clear

**Comment by parispittman** [comment]
/remove-lifecycle stale

lets figure out how to get a process in place for this now that in person events are a thing again. ill put on a steering agenda.

**Comment by mrbobbytables** [comment]
I think this is good now - the scholarship program was amended to include community members:
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/attend/scholarships/

"Applicants should be active community members who are not being assisted or sponsored by a company or organization, and are unable to attend for financial reasons. (Virtual or In-Person)"

**Comment by eddiezane** [comment]
What I've been asking for is some KubeCon tickets for leads to give out to contributors that need them. Scholarships for travel and lodging are nice but even if we can help cover one of the expenses for attending it can go a long way.

**Comment by dims** [comment]
@eddiezane i think if the leads in question can submit that form and indicate that they have the support of k8s chairs/steering, we can make it work by vouching for them. (we've done similar things in the past)

cc @idvoretskyi

**Comment by dims** [comment]
also we can do different things like full travel vs just tickets too

**Comment by dims** [comment]
/close

CNCF has a "maintainer" option now
