### ISSUE TITLE
Nextcloud docker image untrusted domain

### ISSUE THREAD

**Issue by Mehrez27** [kubernetes/community#3811]
Hi!
I tried to deploy nextcloud in a cluster kubernetes I used this helm chart: "https://gitlab.com/kanzari.1993/nextcloud.git" with ingress controllers enabled that I have set it with the necessary configurations (DNS update, hostname and the certificate provider https) but when I access through the hostname that I indicated in the ingress.yaml file I receive this warning:
![e626995e76969bd14c9c1530fc696f616bc5a231](https://user-images.githubusercontent.com/36052172/59672005-96b48880-91b6-11e9-845f-72ecfd7ad44a.jpeg)
Does anyone have an idea about how to solve this issue?
Thanks in advance!

**Comment by nikhita** [comment]
@Mehrez27 Hi, please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/close
