### ISSUE TITLE
Contributor Summit SD Transparency & AV

### ISSUE THREAD

**Issue by JamieRachel** [kubernetes/community#3868]
Make the content from the contributor summit available for people who could not attend. Will collect all the AV needs as well. 

- [x] Video Recording: Arrange to have both NCW rooms recorded.

- [ ] Video Recording: Identify what other rooms and tracts need to be recorded 

- [x] Transcriptions: Arrange to have transcriptions of video (inclusivity). _(Check with team- is this happening?)_
 
- [x] Video Editing: Detail out the process for workshops 

- [x]   Uploads: Upload video, transcripts, and slides. (Who, What, When, and Where??)

- [x]  Mics - identify what rooms and needed equipment 

- [x] AV needs ( projectors, screens etc.) identify what is needed per room

**Comment by debgiles** [comment]
I've added notes to all of your tasks in the above, although I can't figure out how to check the boxes in the original text.  Let me know if there are questions based on this information.

- [ ] Video Recording: Arrange to have both NCW rooms recorded.
COMPLETED

- [ ] Video Recording: Identify what other rooms and tracts need to be recorded.
Sustainability and Welcome/Wrap Up Room will be recorded.  Still to be determined - Tech Discussion and Current Contributor Workshop.

- [ ] Transcriptions: Arrange to have transcriptions of video (inclusivity). (Check with team- is this happening?)
This is currently slated into the budget.  It will take 2 weeks to turn this around post-event.

- [ ] Video Editing: Detail out the process for workshops
We will breakup the videos according to how they are broken up in Sched, unless requested otherwise.

- [ ] Uploads: Upload video, transcripts, and slides. (Who, What, When, and Where??)
I will save them to Google Drive and then share the link in the Summit Staff Slack channel to be uploaded to the Kubernetes YouTube.  I'll share the videos without the subtitles within a week, and the videos with subtitles in 2 weeks once they're completed.

- [ ] Mics - identify what rooms and needed equipment.
COMPLETED - Can be referenced and updated by commenting in the doc if needed: https://docs.google.com/spreadsheets/d/1vBbuAT7IZ6lOaPOkbZlEejGULfqAnpOl1BwYxxKxDO8/edit#gid=1207731845

- [ ] AV needs ( projectors, screens etc.) identify what is needed per room
COMPLETED - Can be referenced and updated by commenting in the doc if needed: https://docs.google.com/spreadsheets/d/1vBbuAT7IZ6lOaPOkbZlEejGULfqAnpOl1BwYxxKxDO8/edit#gid=1207731845

**Comment by hpandeycodeit** [comment]
@JamieRachel we can mark above tasks completed as per the update from Deb.

**Comment by jeefy** [comment]
Looks like we're done! 

/close
