### ISSUE TITLE
Custom Scheduler Policy

### ISSUE THREAD

**Issue by eroiborges** [kubernetes/community#3891]
Goal: Try define a custom scheduler policy

Config: 
add the parameters to kube-scheduler manifest 
    - --use-legacy-policy-config=true
    - --policy-config-file=/etc/kubernetes/custom-policy-scheduler.json

content of /etc/kubernetes/custom-policy-scheduler.json
{
  "kind": "Policy",
  "apiVersion": "v1",
  "predicates": [
      {"name": "PodFitsPorts"},
      {"name": "PodFitsHostPorts"},
      {"name": "PodFitsResources"},
      {"name": "HostName"},
      {"name": "MatchNodeSelector"},
      {"name": "NoVolumeZoneConflict"},
      {"name": "MaxEBSVolumeCount"},
      {"name": "MaxGCEPDVolumeCount"},
      {"name": "MaxAzureDiskVolumeCount"},
      {"name": "MatchInterPodAffinity"},
      {"name": "NoDiskConflict"},
      {"name": "GeneralPredicates"},
      {"name": "CheckNodeMemoryPressure"},
      {"name": "CheckNodeDiskPressure"},
      {"name": "PodToleratesNodeTaints"},
      {"name": "CheckVolumeBinding"}
        ],
  "priorities": [
      {"name": "ServiceSpreadingPriority","weight": 1},
      {"name": "EqualPriority","weight": 1},
      {"name": "ImageLocalityPriority","weight": 1},
      {"name": "SelectorSpreadPriority","weight": 1},
      {"name": "InterPodAffinityPriority","weight": 1},
      {"name": "LeastRequestedPriority","weight": 9500},
      {"name": "BalancedResourceAllocation","weight": 5000},
      {"name": "NodePreferAvoidPodsPriority","weight": 10000},
      {"name": "NodeAffinityPriority","weight": 1},
      {"name": "TaintTolerationPriority","weight": 1},
      {"name": "GPUAllocationPriority","weight": 10}
      ],
  "hardPodAffinitySymmetricWeight": 10
}

Issue:  plugins.go:241] Invalid configuration: Predicate type not found for CheckNodeMemoryPressure

Also, if I remove the CheckNodeMemoryPressure from json file, will get error on CheckNodeDiskPressure.  Removing both, there no error on custom policy.

Expected behavir: Running the custom policy as described on Json File.

Kubernetes version 
 - 1.13.5 and 1.14.3

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
