### ISSUE TITLE
Markdown linter for all of K8s org

### ISSUE THREAD

**Issue by jonasrosland** [kubernetes/community#3899]
This is a suggestion based on some of the great work was done last week by @akutz with regards to making sure Markdown docs are properly linted. This could help the project's more Markdown heavy locations become more standardized, and also help drive and apply parts of the [style guide](https://github.com/kubernetes/community/blob/master/contributors/guide/style-guide.md#markdown-formatting).

The first PR that went into effect is here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/425
And then it was added as a pre-submit here: https://github.com/kubernetes/test-infra/pull/13363

Perhaps this could see wider use in the K8s org?

/assign @cblecker 
/sig contribex
/kind documentation

**Comment by akutz** [comment]
Thank you @jonasrosland. For those reading this, here is some additional information regarding the linting process:

* [`.markdownlintrc`](https://github.com/igorshubovych/markdownlint-cli#configuration) - A file at the root of a repository that influences the linter
* [Linter rules](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md) - The rules that may be enabled/disabled with the rc file

It's possible to run the linter manually on existing k/k projects. For example, here's a [gist](https://gist.github.com/akutz/d5c29a20df56b2623d0d181de3804ca6) where the linter is executed against the `client-go` repository with:

```shell
cd $(mktemp -d -p /tmp) && \
git clone https://www.github.com/kubernetes/client-go . && \
docker run --rm -v "$(pwd)":/build:ro gcr.io/cluster-api-provider-vsphere/extra/mdlint
```

**Comment by tao12345666333** [comment]
Thank you. I have tried adding markdown lint to kubernetes-sigs/kind https://github.com/kubernetes-sigs/kind/pull/1122

**Comment by BenTheElder** [comment]
Personally I appreciate the work on this but I'm concerned about potentially adding another barrier to successfully PRing changes that blocks on things that don't really affect the content rendering or readability.

Also cc @zacharysarah @jimangel to tag in some
/sig docs

Apologies for the long winded comment, but I'd like to be specific and clear on this one:

---

Linters are kinda awful for new contributors because they have to figure out how to tell what is failing and why from our CI (which they've probably never seen before, or this tool)... which is actually not so easy with the log highlighting etc... and then how to run it locally....

I'm willing to accept that barrier when we're doing static analysis to help catch breaking bugs that we'd ideally catch in human review anyhow (but frequently don't because humans get tired and bugs can be subtle) like:
```go
for i := range foo {
    // whoops forgot to capture i, linter will catch this, hopefully a reviewer would have too!
    go func() {
        fmt.Println(i)
    }
}
```
But not as much when we're doing:
```markdown
* a 
* b 
```
versus:
```markdown
- a
- b
```

Which IMO are both equally readable and produce the same rendered content, I.E. neither form contains "bugs" (Not a complete markdown expert, I could be wrong ...)

Automated formatters are not **so** bad but still a hurdle to jump through, especially for e.g. contributors on Windows when we use bash all over ...

kind frequently sees totally new contributors (sometimes their first use of github!) sending drive-by PRs to fixup documentation that tripped them up, I'd hate to see their PRs blocked on stray end of-line spaces that don't really affect rendering or readability :(

Looking at https://github.com/kubernetes-sigs/kind/pull/1122, almost none of the changes affect the content at all and the original content is equally readable imho.

Having good style is certainly nice, but for kind at least I'd much prefer helpful content that is readable enough and a smooth contributing experience over fighting with robots that bikeshed every last character, if that makes sense ...

**Comment by mrbobbytables** [comment]
I'm inclined to agree with @BenTheElder. I'm a stickler for markdown formatting and conforming with the style guide where it has been used, but I'd rather not force it on folk ESPECIALLY org wide when it'd likely just be a burden for folk when attempting to improve documentation. We'd also likely have a slew of things we'd have to add to the whitelist like the various retro notes that are converted to markdown from gdoc. 

We could potentially enable it selectively for things like our contributor docs, but that would very much be targeted and limited to things that generally break markdown formatting (e.g.  [MD032 - Lists should be surrounded by a blank line](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md032---lists-should-be-surrounded-by-blank-lines)).

**Comment by qq843700497** [comment]
I  want to be a new contributor, I agree with @BenTheElder

**Comment by mrbobbytables** [comment]
Following up on this item, we did come to the conclusion that we should not move forward with an org wide linter. 👍 
I'm going to go ahead and close it out, but If you have any questions or concerns please feel free to reopen :)

/close
