### ISSUE TITLE
youtube channel needs a new owner

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#3985]
I'm the current owner on the community channel for youtube. I'd like to pass the torch to another youtube admin. 

A) how should someone be selected for this role?
B) let's document it.
C) can contributors@kubernetes.io own it and then multiple people have access? unsure. need to investigate. [update: yes, this address can be the primary owner. i will remove myself as the primary owner and add this account.]
D) if not contributors@, who? [update: see 'C']

**Comment by mrbobbytables** [comment]
At least for C, it should be possible for contributors@kubernetes.io to own it. A shared owner account will certainly help with the current bus-factor aspect. 😬 

Better management (ref: https://github.com/kubernetes/community/issues/3938) of the credentials shouldn't necessarily be a blocker for changing ownership...but we should probably pursue sorting that out sooner rather than later.

**Comment by xiexiaojing** [comment]
A shared owner account is an excellent idea.😀

**Comment by castrojo** [comment]
Feel free to move primary ownership to me, I can at at least assign a new moderator and start documenting the process.

**Comment by parispittman** [comment]
update - contributors@ will be the primary. next step is figuring out who should get access to contributors@. i think it should be everyone in the owners file at the root for the community-management subproject. thoughts? we need to update docs, too.

**Comment by cblecker** [comment]
/assign castrojo
I think this is done, isn't it?

**Comment by mrbobbytables** [comment]
It is done \o/
/close
