### ISSUE TITLE
call for outreachy interns

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4043]
outreachy internship requests are due sept 5th. we have two funding opportunities from red hat. 
ideas:
1) developer guide content 
2) front end and tech writer for the contributor site

thoughts?

**Comment by tashimi** [comment]
Hi - the working group for multi-tenancy has some cool projects going on: Tenancy CRD, Hierarchical Namespaces, RBAC, and Quotas. We think an intern could jump in and work on these projects, working on end to end testing, new user tutorials, and implementing small features and providing code review to other community members. We will identify some issues as "Good First Issues."

**Comment by parispittman** [comment]
@tashimi sounds great! would you be the point of contact/mentor?

**Comment by tashimi** [comment]
@parispittman I can definitely be the point of contact, I've got several volunteers who are more involved in the coding efforts that will help mentor, @rjbez17 @srampal

**Comment by tashimi** [comment]
At the ClusterAPI community in person meeting, we discussed having an intern take the automated API notation being done and creating automated documentation with it. This could be a great way to have a good starter project and learn a ton about how ClusterAPI works.

**Comment by parispittman** [comment]
@tashimi this is what we will need to go live on the outreachy site tomorrow:
- short title
- Description of the internship project
- system requirements
- examples of possible tasks
- skills needed

notes from outreachy folks:
Please do not place educational restrictions (such as needing a degree) on this project. Outreachy applicants are judged on their demonstrated skills, not on their educational background. If your project requires knowledge that would normally be learned during a degree, your project contribution tasks should test applicants for that knowledge.

You should also exclude discussion of internship tasks, internship benefits, repository URLs, issue tracker URLs, newcomer tags, or application period contribution tasks. Those are collected in the optional fields below.

**Comment by tashimi** [comment]
@parispittman sorry for the slow response on this: 
 
- short title: multi-tenancy working group internship
- Description of the internship project: The multi-tenancy working group has several projects underway, developing a Tenancy CRD, Hierarchical Namespaces, and extending role-based access control (RBAC) and quotas to extend multi-tenancy management to Kubernetes. This project is for an intern to join our working group, learn about these projects, work on end to end testing, new user tutorials, and implement a few small features. We have several mentors from different organizations who will provide mentorship as you get started.
- system requirements: computer you can install kubectl, create a go development environment on
- examples of possible tasks: create an end to end test for a Tenancy CRD, create documentation on how to install and use the Tenancy CRD, automate documentation end points so that docs are auto-updated 
- skills needed: go and a willingness to dig in and learn with us

**Comment by tashimi** [comment]
- short title: ClusterAPI internship project
- Description of the internship project: ClusterAPI is an opensource project that seeks to automate the lifecycle of Kubernetes clusters. In this internship, you will be automating the documentation of this project, using the automated API notation that the maintainers have included as they build out ClusterAPI! Your work will enable other developers to more easily understand how to use ClusterAPI and use it to automate their own projects, and you will learn a ton about ClusterAPI along the way.
- system requirements: a computer capable of installing kubectl, kind, docker, kubernetes, and a go development environment
- examples of possible tasks: Take an API endpoint's API notation, and create a documentation page that describes what that API endpoint does and pull in the API notation programmatically so that the documentation is updated whenever the API endpoint is updated. Think of a new user, and explaining to them what that API endpoint does, and create a doc that does that.
- skills needed: go, good writing skills, an interest in learning and explaining tech in an easy to understand way, and a willingness to learn with us!

**Comment by nikhita** [comment]
Kubernetes projects are live on the Outreachy website: https://www.outreachy.org/apply/project-selection/#kubernetes :tada: 

We'll need to update mentor info as a follow-up.

**Comment by parispittman** [comment]
/close

next step is picking the interns!
