### ISSUE TITLE
@kubernetes/sig-Network-network    External Ip Pending in kuberntes for Load Balancer 

### ISSUE THREAD

**Issue by jedidiahjrp** [kubernetes/community#4139]
Hi I have installed Kubernetes in centos using kubeadm i created Deployment using type Load Balancer the external ip is always in pending state !

NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1       <none>        443/TCP        13m
service
![Pending1](https://user-images.githubusercontent.com/44153581/66102773-200a9200-e5d1-11e9-97c3-599bceda6962.jpg)
    LoadBalancer   10.101.168.76   <pending>     80:32225/TCP   4m52s

**Comment by jedidiahjrp** [comment]
@kubernetes/sig-Network-network

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close

**Comment by jedidiahjrp** [comment]
> Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).
> 
> We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.
> 
> We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.
> 
> The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.
> 
> Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:
> 
> * [user documentation](https://kubernetes.io/docs/)
> * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
> 
> Again, thanks for using Kubernetes.
> 
> The Kubernetes Team
> 
> /triage support
> /close



> Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).
> 
> We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.
> 
> We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.
> 
> The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.
> 
> Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:
> 
> * [user documentation](https://kubernetes.io/docs/)
> * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
> 
> Again, thanks for using Kubernetes.
> 
> The Kubernetes Team
> 
> /triage support
> /close
hi @cblecker I posted Stack Overflow also unable find the solution please Help me out! Thank You
