### ISSUE TITLE
All documented times for meetings and meeting invites should be in UTC

### ISSUE THREAD

**Issue by dims** [kubernetes/community#4174]
Pretty please?

This is the first step to reduce time zone burdens on people who are not based in US.

**Comment by dims** [comment]
Inspired by https://github.com/kubernetes/community/pull/4169

**Comment by parispittman** [comment]
i think we had this discussion when we talked about the style guide. cc/ @mrbobbytables

**Comment by mrbobbytables** [comment]
It did -- The problem is with Daylight Savings Time :|  things would have to be updated multiple times per year to stay on 'track', not to mention different parts of the world have different DST rules. It was generally decided to use a timezone that 'follows' DST -- something like 'PT' or 'ET'. Instead of PST / PDT | EST / EDT. 

It's super frustrating, but still the best solution we came up with =/

**Comment by cblecker** [comment]
We actually moved *away* from enforcing UTC specifically for DST considerations. We leave it up to the SIG to decide if they will follow DST or not, and schedule the meeting accordingly. The time zone conversion links and google calendar invites should move automatically if you choose a timezone that follows DST (and most sigs do choose to follow DST, because of the high amount of North American participation).

For these reasons, I’m -1 to this change.

**Comment by geekygirldawn** [comment]
Actually, UTC creates issues for many of us outside of North America, too (not just DST). Here in the UK, we have British Summer Time (BST) and Central Europe has CEST, which are the equivalent of DST, except that the switch to these summer time zones is offset by a few weeks from when the US switches (sigh).

Using UTC means that we either change the time of the meeting twice a year, or that the meeting occurs at a different time for each half of the year. This makes it impossible to schedule other work meetings around k8s meetings. 

I'm a fan of picking a time zone that isn't UTC. US Pacific time is fine with me.

**Comment by devaips** [comment]
Seems like there is no way to make it work for everyone. The argument for sticking with a DST timezone is reasonable to me. Consistency across all the sigs and docs is the most important aspect.

**Comment by cblecker** [comment]
SIGs themselves decide on meeting times, and for some, meeting with a non-North American time zone is preferable. We can't really enforce an across the board standard here.

If a SIGs meeting time is inaccurate in sigs.yaml, or you'd like to suggest a different meeting time for the sig, please contact the sig on their mailing list or Slack.

Closing as WONTFIX :)
