### ISSUE TITLE
kubectl describe pod not found

### ISSUE THREAD

**Issue by dddd45** [kubernetes/community#4250]
k8s@k8s-master:~$ kubectl get pod --all-namespaces
NAMESPACE              NAME                                         READY   STATUS             RESTARTS   AGE
kube-system            coredns-5644d7b6d9-9qhnd                     1/1     Running            4          4d1h
kube-system            coredns-5644d7b6d9-vh9wc                     1/1     Running            4          4d1h
kube-system            etcd-k8s-master                              1/1     Running            58         4d1h
kube-system            kube-apiserver-k8s-master                    1/1     Running            56         4d1h
kube-system            kube-controller-manager-k8s-master           1/1     Running            7          4d1h
kube-system            kube-flannel-ds-amd64-6b2xh                  1/1     Running            0          2d3h
kube-system            kube-flannel-ds-amd64-9xq7d                  1/1     Running            4          2d4h
kube-system            kube-proxy-6q8v6                             1/1     Running            5          4d1h
kube-system            kube-proxy-xw9db                             1/1     Running            0          2d3h
kube-system            kube-scheduler-k8s-master                    1/1     Running            7          4d1h
kube-system            kubernetes-dashboard-7c54d59f66-8zwcx        1/1     Running            4          2d4h
kubernetes-dashboard   dashboard-metrics-scraper-566cddb686-thvjf   1/1     Running            4          4d
kubernetes-dashboard   dashboard-metrics-scraper-76585494d8-bgsr2   0/1     ImagePullBackOff   0          4h36m
kubernetes-dashboard   kubernetes-dashboard-7b5bf5d559-8rbdz        1/1     Running            2          4d
kubernetes-dashboard   kubernetes-dashboard-b65488c4-wfqgx          0/1     ImagePullBackOff   0          4h36m
k8s@k8s-master:~$ kubectl describe pod kubernetes-dashboard-b65488c4-wfqgx
Error from server (NotFound): pods "kubernetes-dashboard-b65488c4-wfqgx" not found

I have an issue that I tried to debug the kubernetes dashboard problem but when I used "kubectl describe pod <pod_name>", it threw Error from server (NotFound).  In fact, I tried the same command to all pods and the results were all not found.

Please help.

**Comment by Vageesha17** [comment]
@dddd45  try with the command  kubectl describe pod kubernetes-dashboard-b65488c4-wfqgx --namespace <namespace_of_pod>

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum or Stack Overflow to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/triage support
/close
