### ISSUE TITLE
Options other than just relying on cncf jobs board for careers

### ISSUE THREAD

**Issue by underrun** [kubernetes/community#4350]
Based on Jorge Castro's suggestion in slack:
https://kubernetes.slack.com/archives/C25QWBR71/p1576611073059000

The purpose of this issue is to collect ideas on alternatives to just shutting down #kubernetes-caeers channel in slack and relying on cncf's job board for kubernetes and cloud native related job postings, and to consider these alternative paths.

From the slack channel people have suggested that there is value in community engagement beyond just having a place for jobs to be posted and we would like to explore alternatives like:

* don't deprecate the channel
  * just leave it as an independent thing
  * mirror cncf job posts to the channel
    * possibly without discussion enabled
* deprecate channel but open other lines of communication
  * discuss.kubernetes.io for better moderation

For me personally, I like the fact that job seekers occasionally post in there and whatever we do I'd love to see our community get stronger by furthering the connection between recruiters / hiring managers and between engineers looking for work and across those lines. 

When we get together at conferences our companies talk to other companies about what we are looking for and what skills are in demand. we talk to each other about the roles we want and the skills we would love to work on.

Maybe it seems like we don't need #kubernetes-caereers because we haven't advanced the idea of a place where everyone can come and talk about caereers in kubernetes to its fullest?

But I'm an ideallist :-) I'd love to find some practical solution to increasing connection in the community rather than reducing it by just dropping the channel and relying on the one-sided / one-way communication of the cncf jobs board.

**Comment by phumberdroz** [comment]
I have not done this in this slack but a couple of years ago I used to just post my profile (what I do, who I am and CV) into the slack channels of slacks that I was active in. Sometimes companies are not actively looking but still might be interested if they spot your profile.

**Comment by JoelSpeed** [comment]
Not sure if people are aware of this or not, but the CNCF board does have a "job seekers" section too. You can create your own profile, upload details etc and then companies can browse those profiles as they would have done in slack

**Comment by mrbobbytables** [comment]
> Maybe it seems like we don't need #kubernetes-caereers because we haven't advanced the idea of a place where everyone can come and talk about caereers in kubernetes to its fullest?

I'm open to the idea of turning the channel into more of something for career-advice, but I'd discourage posting positions/cvs there and push that to the job board. 

The other thing that could be done in job postings from groups that have had a presence in slack, would be to reference it in the job posting / seeker profile -- along the lines of:
`Have a question? feel free to ping @herpderp on the kubernetes or cncf slack`

> Not sure if people are aware of this or not, but the CNCF board does have a "job seekers" section too. You can create your own profile, upload details etc and then companies can browse those profiles as they would have done in slack

I do agree that the job seeker portion isn't quite as obvious unless you create a profile. 
/cc @idvoretskyi @caniszczyk
Looping in for feedback, not sure who else to let know about it^^;;;;

**Comment by elisiano** [comment]
@mrbobbytables personally I would prefer the opposite: having a post on the board and a link shared in the channel from the recruiter. I feel this enables better engagement. 

If the intent is to have the channel read only, then there could be some sort of automation (webhook or otherwise) that would post the link in the channel followed by “for further info ping @herpderp”

**Comment by mrbobbytables** [comment]
@elisiano We can't make the channel read only.

**Comment by idvoretskyi** [comment]
> I do agree that the job seeker portion isn't quite as obvious unless you create a profile.

Becoming a job seeker is so easy as signing up with a few clicks; for the individuals with LinkedIn accounts it's even easier as the LinkedIn SSO is supported.

**Comment by castrojo** [comment]
/sig contributor-experience
/assign

> having a post on the board and a link shared in the channel from the recruiter. I feel this enables better engagement.

I wonder if we could automate this, perhaps having a bot paste in new jobs from the board so individuals could discuss the positions in real time. I feel like we also need to keep the hallway track vibe that real time comms give us, which is what I believe @underrun's gist is here. 

Extra point - the moderator load of the jobs channel vs. the rest of the slack is really lopsided, it wouldn't hurt to bring in some protempore moderators, one in the EU, one on the east coast US, and a west coaster. Oh hey look @underrun @phumberdroz @elisiano - what are the geographical chances that you all line up perfectly? 😄 All three of you seem to be doing this professionally anyway, so if you're in slack all day as it is and you want to start your k8s journey by helping us out here, then I'd be happy to sponsor your membership. (No pressure if you don't want to do so, this is more of an opportunity to help out the community, not an ultimatum or anything, heh.)

Slack moderation is global, so we can't give you admin access to one channel, so that means if you want to do this you'll need to check out:

- https://github.com/kubernetes/community/blob/master/community-membership.md
- https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#moderation
- https://github.com/kubernetes/community/blob/master/communication/moderation.md

I'd like to keep the channel open as it's still kind of a free zone, official boards never let the people put in honest feedback and keeping that space for people to discuss positions is useful. 

If anyone else from -careers wants to take a stab at this let me know, about 9 months ago I felt this channel wasn't worth the moderation effort we put into it but I think if we can keep the moderation load the same, give people new opportunities to volunteer, AND keep the channel useful then it's worth trying.

**Comment by elisiano** [comment]
@castrojo that was a long read! After reviewing it I would say I'm open to giving it a try.
Just a note about timezone: I'm mainly US/ET but a couple of months a year I am located in CET. Reading the rules I would just need to let other admins know (and most of the time I cover the same US/ET zone at work so it overlaps with the community duties).

**Comment by hanoisteve** [comment]
I think we need to keep communication about opportunities a two way channel. Also even though I am not looking at the moment I find it interesting to see what is in demand in the industry and be able to discuss with people about opportunities.   Moves away from slack are almost always a downgrade in quality of the communication. Perhaps its not the place for people to post resumes but thats different issue from just seeing the jobs and being able to discuss.

**Comment by castrojo** [comment]
/close

This is staying for the time being so no need to track it. We'll see how the per-channel tools shape up over time.
