### ISSUE TITLE
eks cluster nodes showing no resource found

### ISSUE THREAD

**Issue by veera2019** [kubernetes/community#4361]
@k8s-github-robot i have installed eks cluster in aws and created nodes using cloud formation template.
while accessing cluster from ec2 instance if i kubectl get svc i am getting output and it's working 
if i run kubectl get nodes it's getting no resource found and i have added node role in aws-auth-cm config file also still getting error

kubectl get nodes
no resource found

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/triage support
/close
