### ISSUE TITLE
How can we rename a running cluster after cloning a whole drive, without recreating a kubernetes stack?

### ISSUE THREAD

**Issue by tsunamireversal** [kubernetes/community#4383]
As you can see, we cloned a drive and kubernetes can be brought up, BUT the name of the cluster (demo) is from the source disk, and is wrong:
```
root@demo-clone  [10:37] [ ~ ] #  kubectl get nodes
NAME                        STATUS   ROLES    AGE   VERSION
demo   Ready    master   43d   v1.15.6
```

Is there a way to keep the stack up and running (after all, it's all working!) but just rename the cluster?

If not, I think it would be really helpful to be able to do that for a running system.

**Comment by nikhita** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes)
or our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow and Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
