### ISSUE TITLE
NetworkPolicy not working with SCTP protocol

### ISSUE THREAD

**Issue by Mishra-Akash** [kubernetes/community#4420]
I am trying to setup a Network Policy for my Pods. I need to only allow Port 3301(on SCTP) & 443(TCP) as ingress. But Once NP is created , rule is not working.

NP.yaml==>
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: custom-networkpolicy
namespace: alpha
spec:
podSelector:
matchLabels:
role: web
policyTypes:

    Ingress
    ingress:
        from:
            namespaceSelector:
            matchLabels:
            app.kubernetes.io/traffic-policy: ingress-allow
            podSelector:
            matchLabels:
            app.kubernetes.io/web-ingress: allowed
            ports:
            protocol: SCTP
            port: 3301

Kubernetes configuration to enable SCTP support ==>

../manifests/kube-apiserver.yaml: - --feature-gates=AllAlpha=false,SCTPSupport=true
../manifests/kube-controller-manager.yaml: - --feature-gates=AllAlpha=false,SCTPSupport=true
../manifests/kube-scheduler.yaml: - --feature-gates=AllAlpha=false,SCTPSupport=true

What you expected to happen:
As per NP, only port 443 & 3301 should be reachable from other pods with or other namspace set with required labels.

How to reproduce it (as minimally and precisely as possible):
Issue still exists.

Anything else we need to know?:
Once I removed the SCTP protocol from Ingress , rules immediately start working for other node.
I have tried to create separate rule for SCTP only but not luck.

Environment:

    Kubernetes version (use kubectl version):
    Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

    Cloud provider or hardware configuration:
    HP Blade 360

    OS (e.g: cat /etc/os-release):
    eccduser@seliics03523:~/akash/NP> cat /etc/os-release
    NAME="SLES"
    VERSION="15"
    VERSION_ID="15"
    PRETTY_NAME="SUSE Linux Enterprise Server 15"
    ID="sles"
    ID_LIKE="suse"
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:suse:sles:15"

    Kernel (e.g. uname -a):
    Linux machine1 4.12.14-23-default #1 SMP Tue May 29 21:04:44 UTC 2018 (cd0437b) x86_64 x86_64 x86_64 GNU/Linux

    Install tools:

    Network plugin and version (if this is a network-related bug):
    Calico

    Others:

**Comment by nikhita** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes)
or our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow and Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

/close
