### ISSUE TITLE
Blog posts format of “Meet Our Contributors”

### ISSUE THREAD

**Issue by idealhack** [kubernetes/community#4469]
We had the initiative to have another "meet our contributors" streaming for APAC regions (https://github.com/kubernetes/community/issues/4086) and have started talking to people about it.

During the discussion back in KubeCon San Diego and several meetings of APAC planning in SIG Contributor Experience, we got the idea that some contributors might be too shy to be on a live video session, and maybe we could start with blog posts or podcasts first. This will also help us get the word out and have more active contributors from APAC regions.

We might want to focus on countries/regions per post, also it would be great to have one about contributors from or in India during the Kubernetes forums in Bengaluru and Delhi in mid-Feb.

A discussion with SIG Docs blog subproject owners is needed too, of course.

Some 5W1H questions would be like:

- who are you and what do you do?
- how did you get started with Kubernetes?
- when and why did you start contributing?
- who did you meet in the community and what did you learn?
- what were some best memories when you work in the community?
- what has happened in your career since your first contribution?
- do you encourage other people to join the community, why?

I'll update this issue to include more tasks as the planning goes.

/assign
/sig contributor-experience

**Comment by idealhack** [comment]
cc @kubernetes/sig-contributor-experience-apac-coordinators

**Comment by parispittman** [comment]
@idealhack we are building a marketing team and will have bloggers assigned so we can help!  we've got some guidelines that we are bootstrapping and sig-docs folks are involved as well. #4459 

notes from the meeting https://docs.google.com/document/d/1IlHAJ131akGhI5ffF4OoVW0PrsVY4C0BB8l-UyQaQVo/edit

**Comment by tao12345666333** [comment]
SGTM!

blog posts will be a good start.

**Comment by nikhita** [comment]
From April 23 APAC meeting, @idealhack to create a google doc to start collaborating on questions we can ask on the blog post.

We'll also be using the doc to draw a list of folks who would like to help out with the blog posts (per country/region) and folks we'd like to interview. This should help us with estimating timelines for scheduling the blog posts (thanks @palnabarun for the idea!)

**Comment by idealhack** [comment]
thanks for all the discussions today, the doc is here: https://docs.google.com/document/d/1zB-FOvfbnKbiWlGgInnDB06hDfLsTQuuKsXQCqc-lL0/edit

**Comment by nikhita** [comment]
Deadlines/milestones planned (osting from last meeting's notes):

Collection of responses - October 8th
Collating responses and writing the blogs - October 22nd
Publishing the series - November 15th

**Comment by mbbroberg** [comment]
Hey @Pensu, did this happen? If so, link up the posts here and we'll close this out! Else, we can push to 1.21. Thanks!

**Comment by palnabarun** [comment]
Hi @mbbroberg 👋🏽, we are still collecting responses. We have a meeting in a few hours to discuss the progress of the blog series. On that note, I think it is better to be pushed to 1.21.

/milestone v1.21

**Comment by palnabarun** [comment]
Ah! I am not a member of @kubernetes/community-milestone-maintainers. 😅 

@mbbroberg Please feel free to milestone this issue to v1.21.

**Comment by mbbroberg** [comment]
You bet @palnabarun! Thanks for what you're doing 👋

**Comment by nikhita** [comment]
I don't think most of the folks on this thread have bandwidth to drive the "blog posts format" effort but would be willing to help shepherd if there's someone else taking the initiative.

We've had a slew of new contributors from India recently. Since this was originally intended for contributors from the APAC region, I am going to reach out to them to check if anyone has the time to drive this.
/remove-lifecycle rotten

**Comment by palnabarun** [comment]
First of all, thank you all (@Priyankasaggu11929 @Debanitrkl @anubha-v-ardhan @verma-kunal @Haimantika @CIPHERTron @ShivamTyagi12345 and anyone else who is interested in this effort) for taking up this initiative. 💯 

I can happily now unassign myself. 😌 
/unassign

---
Responding to @Priyankasaggu11929's question from the [Slack thread](https://kubernetes.slack.com/archives/C1TU9EB9S/p1629185267141100?thread_ts=1628501759.053600&cid=C1TU9EB9S)

> How the folks working on the project & their work was tracked? Was there someone leading the initiative? Does this fall under a certain sub-group or anything like that that we could re-use?

The erstwhile [SIG Contribex APAC Coordinators](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/role-handbooks/apac-coordinator.md) used to own this effort. A subset of the APAC Coordinators were collectively working to gather responses from people.

> Because there are so many people who are interested to start contributing with the blog post series? In the previous run, was there certain different roles & responsibilities that were defined so, different people could take one of those roles or responsibilities & cohesively work on them?

The effort can be broken down into the following:
1. Coordinators to ping contributors and gather responses
2. Blog authors who would collate the above information and write the blogs

People interested right now can pick up the above work items.

> What was the initial way to reach out to people? & also to decide whom among so many great APAC contributors, should be interviewed or it was more by networking or some group suggestions?

We started scouting people whom we know + looking at k8s.devstats.cncf.io . Back then, there were not as many people from the region contributing to the community as there are now. It is a great thing that the blog series can cover more contributors now since we have a lot of interesting contribution stories to hear at this point in time. 👍🏽 

> While reaching out to folks (potential interviewees), the way was to ask them for their opinion on what mode of discussion they would prefer ~ like video chat, podcast, or questionnaire, or the questionnaire was made default? (I read in the prior chats, that because not all folks use English as their first language, so, the questionnaire or other adhoc modes of collecting responses were considered)

The best way to ask people about their experiences was to involve a form of textual communication as we can't assume that folks would have the bandwidth to connect over audio or video. Hence, we chose a [Google Form](https://bit.ly/k8s-apac-moc-survey) to gather responses.

The language of communication was an unsolved problem for us. The contributors we reached out to were mostly comfortable in answering in English. However, this should not be taken as a rule of thumb. We had plans to publish blogs in non-English Asian languages as well. An important goal should be to involve coordinators and blog authors from other linguistic demographics to cover all APAC Contributors.

> Is there somewhere we could read the previous "meet our contributors" blog posts? or some of the previous PRs? so, to understand the process followed the previous time.

Unfortunately, there were no blogs written as part of this initiative. However, @Pensu wrote a blog (https://github.com/kubernetes/contributor-site/pull/217) as part of a different initiative that was posthumously published.

> If we require to create a sig-contribex wide visibility google doc, what's the procedure to do that?

There is no well-defined process for that. But, what works well is to create a Google Doc with personal Gmail account and give edit access to kubernetes-sig-contribex@googlegroups.com. For example, folks who have joined kubernetes-sig-contribex@googlegroups.com can freely edit the initiative document -> https://docs.google.com/document/d/1zB-FOvfbnKbiWlGgInnDB06hDfLsTQuuKsXQCqc-lL0/edit#.

**Comment by verma-kunal** [comment]
Thank you so much @palnabarun for all the points [here](https://github.com/kubernetes/community/issues/4469#issuecomment-901044060) 
Helped a lot in understanding about the initiative!! Love to be a part of this ❤️

**Comment by lakshya8066** [comment]
Hey everyone!
I can help with writing the blog posts. Should I add my name in the [doc](https://docs.google.com/document/d/1zB-FOvfbnKbiWlGgInnDB06hDfLsTQuuKsXQCqc-lL0/edit#) and contact a coordinator who has received a response from their contributor?

**Comment by kaiwalyakoparkar** [comment]
@lakshya8066 yeah, you can go ahead with adding your name. For the responses part - coordinator does not have the responses you will have to reach out to @Deba or @psaggu for the responses :)

**Comment by Darshnadas** [comment]
I would like to help in this series as well :) do I assign myself?

**Comment by anubha-v-ardhan** [comment]
Oops, GitHub only allows 10 assignees at a time. No worries, it doesn't matter if you're assigned or not, you are most welcomed.

**Comment by Darshnadas** [comment]
Awesome then!

**Comment by Debanitrkl** [comment]
The blog post series is live
/remove-lifecycle stale
