### ISSUE TITLE
devel docs need to update references from hack/e2e.go to kubetest

### ISSUE THREAD

**Issue by YuikoTakada** [kubernetes/community#4486]
in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md#building-kubernetes-and-running-the-tests , a file name `hack/e2e.go` is written, but this file has been removed since https://github.com/kubernetes/kubernetes/commit/7a1eaa112e720f3a9097f30f07644b05e1d772dc 
this docs need to be updated.

**Comment by mrbobbytables** [comment]
There are 4 docs that need to be updated to reference kubetest instead of hack/e2e.go:
- [contributors/devel/development.md](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md)
- [contributors/devel/sig-architecture/conformance-tests.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md)
- [contributors/devel/sig-node/node-performance-testing.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/node-performance-testing.md)
- [contributors/devel/sig-testing/e2e-tests.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md)

/area developer-guide
/kind documentation
/sig contributor-experience
/sig node
/sig architecture
/help wanted
