### ISSUE TITLE
chair role book/handbook? 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4577]
After speaking with numerous chairs, many requested that we have a baseline role book, others suggested they make their own, etc. I was curious what a baseline would look like anyway so I mad libbed [sig-governance.md](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md) sections for chairs, how sigs should operate, [governance.md](https://github.com/kubernetes/community/blob/master/governance.md#sigs) mentions of operations, all shaped into a role description. This is not to be confused with the chair+tech lead combo role. 

Chairs: make suggestions below in comments and we'll update the issue body to collect them all. 

**Duties and responsibilities**
Run operations and processes that govern the SIG:
- SIG roadmap (may delegate responsibility to tech lead or work together with other roles)
- define how priorities and commitments are managed
- ID, track, and maintain SIG features for current release (can share with other roles)
- Organize (at least) bi weekly meeting cadence on zoom with open meeting notes and agenda; can also be delegated to other members
- Organize contributing instructions in your sig’s repo with a contributing.md file
- Organize KubeCon Intros and Deep Dives with CNCF Event staff, but can delegate to others to create material and present but must review and approve beforehand
- Record meetings and make them available on youtube
- Report activity with the community via k-dev mailing list at least once a quarter (slides, video from kubecon, etc)
- Don’t use private comms to talk to folks - only k8s channels
- Remain active and responsive in role (if taking more than 1 month away, coordinate with another member for duties)
- facilitate
- drive charter changes and get community buy-in
- communication and coordination with other SIGs, steering, and the broader community through attending other SIG meetings when needed, providing quarterly updates either by distributing on kubernetes-dev@ mailing list or presenting at the monthly community meeting, and providing a yearly project health update.  
- ensure other SIGs and community members can find notes of meetings, discussions, designs, and decisions, and periodically communicate a high-level summary of the SIG's work to the community
- People management qualities (suggested: Stephen A) and/or catalytic skills? (suggested: Zach C) 
- [something about coordinating affiliate working group updates] (suggested by: paris)

**Requirements**
- member of the GitHub org
- Increased availability (suggested: bob k)

**OPEN ENDED QUESTIONS:**
- assuming since steering owns sig-governance.md, that body would need to ultimately approve of a 1-need for a baseline role book, et al and 2-the content itself; filing issue here vs steering repo because the doc is located here. (this is more of validation question :) )
- what other qualities of a role book / handbook is this missing?

**Comment by soltysh** [comment]
The above duties and responsibilities assume that chair is also holding tech lead role, when the latter is present I'd like to see more explicit split of the roles. For example SIG roadmap is more up-to TL, if we have TL Deep Dives might be better suited for TL to lead, but chair can definitely organize.

**Comment by LappleApple** [comment]
Hi everyone:

Apologies in advance if what I write is super-obvious or totally off-base (still a bit new around here), but here are some thoughts... 

Ideally a team wants to have someone minding:
-  **the roadmap**: from Paris' suggestions above, that would be the SIG Chair. So they'd be guiding "the why," and would ideally demonstrate through actions that they value alignment, responsiveness in communications with other SIGs/stakeholders, and improving SIG processes to ensure healthy and consistent workflow.

- **the technical vision for making roadmap delivery possible**: this would be the Tech Lead. They'd also guide the SIG on quality, testing, managing/planning away tech debt, etc. They are peers with, not secondary to, the Chairs when it comes to designing the roadmap. 

- **the execution**: this would be the contributors and members. The Chair and the Tech Lead can also contribute code, but to second @jeefy's comment [here](https://github.com/kubernetes/community/issues/4289#issuecomment-561962356) somewhat, they should not be overextended. This is obviously a personal responsibility, but maybe some guidelines can help. Personal time management is important to help with focus (one thing done really well is often more valuable than 10 things done not-as-well) and to avoid burnout. Work in progress limits are great, including for individuals. 

- **SIG health**: This is likely to be similar to the "people management qualities" Stephen A brought up. I would not make minding SIG health a centralised, official role. But I would try to find 1-3 members of a SIG who care about it an awful lot, or who are willing to try to promote it through some simple and effective practices. By "health," I mean making sure that processes exist and are working (or if not, the SIG talks about it, probably in a retro); and that members feel engaged, clear on how they can contribute (it's not always code), and growing through their involvement with K8s. I'd focus on these three pillars:
    - alignment and communications (with other SIGs, with policies, within a SIG, with contributors-can mean anything from "did we get Paris the info she asked for?" to "are we being kind to our contributors?")
    - delegation
    - prioritization (can get into the realm of time management)

It's good that there can be more than one chair or lead. This means that three Chairs in a SIG could take primary ownership of different parts of the WHY-driving functions (prioritization, triage, aligning, etc.) so that they're not the responsible for all of it. But they should share the load among themselves to prevent bus factor and bottlenecks. And tracking/documenting their work in lightweight formats (GitHub Project Boards, for example) helps to increase transparency/reduce confusion when it comes to the status and ownership of work in progress.

Everything above comes informed by experiences working at fairly progressive companies (large and mid-sized) that succeeded in bringing about autonomy, trust and balance between product and engineering leads. Can provide concrete examples if anyone is interested in brainstorming how they might positively inform K8s roles and processes.

*****
I've tried to draft-categorise Paris' bullet points under some themes, and added a few new bullet points. Maybe you'll have some feedback. I'm trying to scale down the Chair's role and delegate activities to suggest a work-in-progress limit for the Chair role. 

**Purpose and prioritization** 
_WHO DOES: SIG Chair and Tech Leads co-own -- Chair owns the WHY, TLs own the HOW_
- Guiding the SIG delivery roadmap: making sure there is one, that it's realistic, that it's aligned with the release team/other SIGs as necessary
- Driving awareness of SIG roadmap through communications with other SIGs and with the community 
- Negotiating and aligning with other SIGs to avoid blockers/conflicts/risks and to collaborate
- ID, track, and maintain SIG features for current release (can share with other roles)
- Remain active and responsive in role (if taking more than 1 month away, coordinate with another member for duties; also make sure that TLs do same)
- drive charter changes and get community buy-in (Chairs and TLs seem best-positioned to do this)
- create a plan/schedule for proposed CNCF, marketing and community outreach activities every release cycle (could be done in a regular meeting w/contributor input)
- providing a yearly project health update (Members could contribute to creating it)
- communication and coordination with other SIGs, steering, and the broader community through attending other SIG meetings when needed 

**Running/managing the SIG**
_WHO DOES: Highly engaged, reliable Members_
 - Organize (at least) bi weekly meeting cadence on zoom with open meeting notes and agenda; can also be delegated to other members
- Organize contributing instructions in your sig’s repo with a contributing.md file
- Record meetings and make them available on youtube
- Discourage using private comms to talk to folks - have people use only k8s channels to maintain SIG transparency and alignment
- coordinating affiliate working group updates (Members can draft, Chair and TL review and send)
- ensure other SIGs and community members can find notes of meetings, discussions, designs, and decisions
- periodically communicate a high-level summary of the SIG's work to the community (Members can draft, Chair and TL review and send)
- facilitate (I would aim to avoid putting this function on the Chair and the TL as much as possible/membership reliability allows, because it's difficult to double-duty running meetings and participating in them)

**CNCF/Marketing and Community Relations** 
_WHO DOES: Could reliable Members could some of this, with guidance and final review by Chairs and TLs? Either way, Chairs and TLs, as reps for their SIG, would definitely have to be responsible for and drive some messaging efforts themselves._
- Organize KubeCon Intros and Deep Dives with CNCF Event staff, but can delegate to others to create material and present (Note: Chairs must review and approve beforehand)
- Report activity with the community via k-dev mailing list at least once a quarter (slides, video from kubecon, etc)
- providing quarterly updates either by distributing on kubernetes-dev@ mailing list or presenting at the monthly community meeting

**Comment by parispittman** [comment]
@LappleApple the definition of member you are using here is SIG member right? the older doc states that member in this docs case is chair, tl, and subproject owner and not sig member so want to make sure we are on the same page. that is the reason behind this issue. 

I like the breakout sections by area/function/umbrella action. I think the why needs to be explicitly drawn out for the first section. ie for each bullet who exactly does what?

much of this has assets tied to it like youtube, zoom, etc. that chairs only have access to. I would still want the running the SIG part to be the responsibility of the chair and the delegation authority to member. so something like:
Running/managing the SIG
WHO DOES: Chairs but can delegate to highly engaged, reliable Members in certain cases

**Comment by LappleApple** [comment]
Hi @parispittman: That's right, SIG Member. Noted re: wanting Chairs to run the daily/weekly SIG mechanics; these duties could then be rotated or shared among a SIG's Chairs.

**Comment by parispittman** [comment]
/close

the work was done in #4716
