### ISSUE TITLE
baseline and expectation of comms for chairs

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#4584]
disclaimer: abbreviation used - ack (short for acknowledge)

right now communication expectations for chairs is a little fuzzy - where they should be looking, what intervals, for what?, expected SLAs/ack times, what needs an ack from everyone/what needs an ack from some

 thanks to @onlydole we captured[ preferred channels for immediate contact](https://docs.google.com/spreadsheets/d/1osoBcTtzjiXfvojEa_-I-8-TZagUuZjaFePIteV-9CM/edit#gid=0). we still need to ask ~20 more chairs to update this. you'll have access to this spreadsheet if you are a chair or tech lead or on the contribex mailing list. 

I'll PR in a doc somewhereTBD (sig-gov.md, communication.md, it's own doc, maybe a chair role-book?, more soon) the expectations

ideas/suggestions: 

- should check slack #chairs-and-techleads every week, 
- must check mailing list once a week (your SIGs)
- must check kubernetes-sig-leads@ biweekly, should check weekly (sign up for digests),
- should ack (acknowledge) even if there is no update or no action needed/done/etc (this is good community practice)
- if the author asking for the response, action, or necessary feedback, you will be pinged directly in #chairs-and-techleads or a github issue where you will ack there for record

open ended questions:

- should have some way to tie your github to slack so people can find you, especially those on the release team. do we ask for slack handles in sigs.yaml? or the preferred contact doc linked above? what is it?
- should there be sla's tied to certain things/acks (example: security, breaking contributor changes, releases) / are there already that we can document here?
- when is it ok for us to email the entire sig mailing list to get comms to you/your group? (a lens to look through: we would email all 40 groups on this topic, not just yours)
- what comms should chairs expect on each of those channels listed above?

refs:
#4289 
#2951 
#4461

**Comment by neolit123** [comment]
added my details to the XLS. in general i think that chairs should be at the minimum watching their respective mailing lists (google groups).

**Comment by LappleApple** [comment]
Hiya, the [preferred channels for immediate contact chart](https://docs.google.com/spreadsheets/d/1osoBcTtzjiXfvojEa_-I-8-TZagUuZjaFePIteV-9CM/edit#gid=0) now misses only seven folks' info. To collect the other 13, I DM'ed people. Most responded immediately, a few responded after two pings. The remainder I will ping again, but it raises a responsiveness "smell." 

I'm 99% confident that the lag is due to folks having a lot on their plates. But this raises the question of how we might support folks with some time management and prioritization coaching. I am thinking here about @tpepper's issue on [leadership training](https://github.com/kubernetes/community/issues/3662) and some of my conversations with Chairs, Leads, and others involved in process improvement. Through those chats I've distilled the most urgent leadership coaching needs (as I perceive them) into these three themes:
- prioritisation (including time management and focusing on delivering the *highest value* instead of the *highest # of things*)
- delegation 
- communication

I see some incremental coaching being possible here, starting in the #chairs-and-techleads channel (now repurposed for building a Community of Practice around process-related topics). My thought: use that channel to first collect insights and data on these very basic questions:
- how do Chairs and TLs define "responsive"/what does that look like?
- what do *they* think is expected of them communications-wise? 
- how much time do they currently spend on comms/responding to others, and do they think it is too much/not enough time? 

If a conversation picks up, we/I can moderate it to keep asking follow-up questions, to gain more insights. Then it might arise that some individuals or small groups want 1:1 coaching on a responsiveness-related topic. (Or people might just ignore the question, but that's also data. :) )

Please let me know if my proposal/proposed questions are redundant with other efforts you've already done. But from my "fresh eyes" POV these are the first thoughts I had. If it's all new and sounds good, I'd do it after this week given where we are in the release cycle.
