### ISSUE TITLE
if i want to use http request to get  k8s api '/api/v1/namespaces/namespace/pods/pod/log?follow=true',the result is dynamic,how i can get the result

### ISSUE THREAD

**Issue by zhupeixiang1234** [kubernetes/community#4612]
### GitHub Username
e.g. (at)github_user

### Property you'd like to Moderate
e.g. discuss.k8s.io, kubernetes-dev

### Username on Property Requested
e.g. (at)property_user

### Requirements

- [ ] I am a Kubernetes Org member already
- [ ] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [ ] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [ ] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### List of qualifications for this position

- Prior moderation experience
- Links to public discussions showing your moderation experience (if available)
- Any other qualifications

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum or Stack Overflow to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/triage support
/close
