### ISSUE TITLE
How to get my Kubernetes Cluster CNI types?

### ISSUE THREAD

**Issue by sober-wang** [kubernetes/community#4674]
Because I not get help in stackoverflow topic kubernetes ,so I come back this
How should I get a running kubernetes cluster CNI types.

I choose Go language

**Comment by mrbobbytables** [comment]
The Stackoverflow post is correct. There isn't a single way to determine this from Kubernetes directly. It's meant to be an abstraction where Kubernetes "doesn't know" about it.
You can look at the [cni spec](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration) to get some information via the host or mounting the config.

Please keep those sorts of questions on stack overflow or [discuss](https://discuss.kubernetes.io/) (the kubernetes user forum). We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum or Stack Overflow to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/triage support
/close

**Comment by errordeveloper** [comment]
@mrbobbytables I do think there should be an open issue on this topic, this one is a good example of user raising a question regarding something we debated in addons WG. I'd consider reopening :)

/cc @stealthybox

**Comment by mrbobbytables** [comment]
if there is a better place for it, I can move the issue there 👍

**Comment by errordeveloper** [comment]
I am not really sure where that would be, given the OP has posted this
question in multiple palaces, I believe it is okay to keep this one closed
:)
