### ISSUE TITLE
Specific issue lifecycle behavior for each SIG

### ISSUE THREAD

**Issue by rikatz** [kubernetes/community#4754]
Hello :wave: 

In the last [SIG Network](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit) meeting, a question was raised about what's the default policy of the SIG for issues lifecycle, when the issue is stale needing some user feedback like if it was solved or not, or even if it needs more information to reproduce it.

There was not really a 'default policy', as some folks wait until Prow closes it automatically, others after 2 bi-weekly meeting cycles (28 days). So the question was "Isn't waiting 90 days to close a stale issue too much? Or shouldn't the bot have some behavior for each SIG?"

So there's a proposal from our meeting, that maybe Issue Lifecycle Behavior should be specific for each SIG, having some sort of metadata allowing SIG Chairs to configure how the bot will deal with stale issues automatically. 

As an example, Prow should alert the issue is stale after 14 days and close the issue after 28 days for SIG Network, but this could be different for SIG API Machinery, which might have a different pace for issue triage, testing and solutions.

There are already some concerns raised in sig-contribex Slack channel about how to deal with issues that cross multiple SIG boundaries, and probably other more will come.

Thank you!

**Comment by mrbobbytables** [comment]
While I understand the idea behind this. I'm -1 on this at least for at least large shared repos k/k, k/community, and k/enhancements. 
A few issues that come to mind:
- Issues and PRs can (and do frequently) have more than one sig involved. Which sig's settings take priority? What if one sig's SLA is different than the others?
- Confusion: "Why was my issue closed here in 2 weeks, where this one was 90 days?"
- What happens if a person goes on vacation or a large amount of people go to an event like KubeCon that might cause a general delay.

Repo specific settings, for subprojects I think are much more feasible. It's very clear that all items in that repo are treated the same.

**Comment by rikatz** [comment]
@mrbobbytables thank you.

My thoughts about your concerns:

> Issues and PRs can (and do frequently) have more than one sig involved. Which sig's settings take priority? What if one sig's SLA is different than the others?

Maybe this could be solved with the 'bigger SIG configuration', like if SIG A have a config of 10 days and SIG B a config of 90 days, follow the bigger one.

> Confusion: "Why was my issue closed here in 2 weeks, where this one was 90 days?"
I do agree with this one. This could also push out people of working with a specific SIG with more strict rules. But maybe the bot could provide a feedback of WHY that issue is being closed with that specific amount of time. IMO I think we maybe miss in SIG charters, docs or somewhere how each SIG behaves. We don't have a bot doing this, but still there are some contributors that follow their own guidelines and close issues that are in a lack of answer after 15 days, 30 days, without any standard.

> What happens if a person goes on vacation or a large amount of people go to an event like KubeCon that might cause a general delay.

Well, this might be a problem as well, but I think that this is much more about having a good common sense while configuring each SIG metadata. If a SIG chair configures the bot to close issues after 7 days, he'll be accepting the risk of this happening. Honestly I don't think any SIG or WG would configure this to be less than 14d/28d (stale warning/issue closing) but still I only have the feedback of SIG Network (@thockin maybe we could use your point of view here).

Thank you :)

**Comment by cblecker** [comment]
The lifecycle bot closing is supposed to be the "last resort" (which is why it takes 150 days for it get cleaned up). If SIG Network wants to close an issue earlier, can't we just `/close` it?

**Comment by thockin** [comment]
We're currently doing this manually, yes.  The question is whether this is common enough to warrant EVEN MORE issue lifecycle management automation.  E.g.  We don't have a `/ball-is-in-OPs-court` command+label, but if we did it seems reasonable to auto-close those faster than 90d.

E.g.
day0: user files issue
day2: sig triage asks for info and sets `/triage info-needed`
day16: sig ignores it because "info-needed"
day30: bot closes it with "reopen this if you have more info" 

This saves us a triage pass where we have to look at every issue with triage/unresolved, scroll to the bottom, then manually act (or don't).

Now maybe 28 days is too low for "stuck waiting for info" but 90 seems too long, and if there's no automation, they will just get forgotten.

It seems like an obvious target for automation, but I ACK that the ROI here may simply not be high enough.

**Comment by parispittman** [comment]
✨ this sounds like a good discussion for the next sig chairs meeting :) ✨ could scope how this may or may not appeal to other sigs

**Comment by cblecker** [comment]
There might be some room for automation around the "this is pending on author info, and should auto-close quicker if we don't get a response". I personally don't know if the ROI is worth it though.

Where things get really bad from a contributor UX perspective is if there are different bars depending on the SIG label. Consistency between repos and sigs is a key recurring issue.. the situation where "my issue autoclosed in X days because it was labelled sig/network but doesn't close for Y days if it's sig/autoscaling" is a road we really don't want to go down.

**Comment by rikatz** [comment]
/remove-lifecycle stale

There's a PR ongoing in test-infra about this, but if you think we should deal directly in the PR I'm fine with that :)

**Comment by nikhita** [comment]
> There's a PR ongoing in test-infra about this, but if you think we should deal directly in the PR I'm fine with that :)

@rikatz do you know where I can find this PR :)

**Comment by rikatz** [comment]
Hello @nikhita :)

Here's the PR: https://github.com/kubernetes/test-infra/pull/18171

It's failing because of some need to create a new dashboard in test-grid or use other one, but the main idea is there: A per Sig issue-lifecycle job, with issue lifecycle rules.

It's worth to comment that this can be 'problematic' with issues with more than one sig label, if both of them uses their own lifecycle but also I think this can be discussed or even improved in the bot :)

Thank you!
