### ISSUE TITLE
REQUEST: New Slack channel #contributor-discussion

### ISSUE THREAD

**Issue by jeefy** [kubernetes/community#4799]
**GitHub Username:** @jeefy 
/cc @parispittman @BenTheElder 

**Slack Username:** jeefy

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**
Channel proposal

**Name of Requested Resource:**
#contributor-discussion

**Description of Request:**
This isn't officially a channel request, no no. This is just a tribute (placeholder)

Context: https://kubernetes.slack.com/archives/C1TU9EB9S/p1590026988441000

To be discussed at the next Contributor Comms meeting: @BenTheElder likes the idea of a more moderated / K8s-contributor-focused channel. A specific use case would be a place to put on-blast issues with K8s infra or CI, that contributors actually read.

#kubernetes-dev unfortunately has bloated/grown and is more of a #kubernetes-users+1, and doesn't serve the desired purpose.

**Note to slack admins:** Don't +/-1 or debate the creation of this channel yet. Instead, discuss the merits of cleaning up and moderating #k-dev versus the creation of a new channel, and ways we can better facilitate contributor comms.

**Comment by BenTheElder** [comment]
To elaborate here:

I think we could try to moderate #kubernetes-dev, but I think it may be a somewhat futile and counter productive effort. I think most users simply join the slack, and look around by channel name. The channel descriptions are truncated and not super prominent in most of the slack UI.

It's a reasonable enough guess that "kubernetests dev" is a channel for developing _on_ kubernetes rather than upstream contribution. Most of the recent content seems to be stuff like "help me email a CSV of AWS resources" or "how do I istio | helm | ....", which isn't exactly related to upstream development ...

I'd like to get upstream contributors active in a channel again, if only for posting issues with the CI / regressions to be aware of, channeling notices we'd post to the mailing list as well (e.g. the switch to klog v2), etc., if not also just actual discussion of / help with upstream development, which mostly seems to be at best happening in SIG channels or private discussion currently.

I think it would be easier to advertise a new, more clearly named channel than try to moderate 
 / somehow clarify #kubernetes-dev

**Comment by BenTheElder** [comment]
... once upon a time this purpose was served by #google-containers on freenode :-)

**Comment by cblecker** [comment]
My gut says creating Yet Another Communication Channel is just going to be plagued by the same issues. I agree that k-dev's usefulness can be improved.

Could something like https://slack.com/intl/en-ca/slack-tips/automatically-onboard-new-channel-members work, where when someone joins k-dev we give them the lowdown on what the channel is about?

**Comment by jeefy** [comment]
I feel like we could make kubernetes-dev the place we want it to be, but it
will involve strict moderation and probably an @channel from an admin
explicitly stating the purpose of the channel and the more stringent
posting guidelines.

That said, at-time-of-reply there are 6937 people in the chat and the
chatter is an even mix of applicable and non-applicable messages.

**Comment by parispittman** [comment]
I like the idea of changing to the word contributor. But I also like the idea of moderating the channel because of 5k+ people in it already.

**Comment by coderanger** [comment]
I've spent a few months on the "strict moderation of #kubernetes-dev" train. How do you feel about closing this?

**Comment by BenTheElder** [comment]
Maybe we should advertise it again? Getting it back on topic is great but doesn't on its own age having a place to message all of upstream (think announcements but for development)

**Comment by mrbobbytables** [comment]
@coderanger what do you think? You've been cleaning it up? Do you think it'd be good to keep it or create a new channel?

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale

After a little bit of discussion further on it - and after a lot of efforts from @coderanger to clean up the k-dev channel. I do agree it's just not bringing in the right people. 

I'm +1 to rename it to hopefully focus it and attract the right audience.

**Comment by coderanger** [comment]
+1 as a rename. Slack has enough affordances around channel renames that I'm not super worried about it being disruptive (vs making a new channel which I think would be).

**Comment by parispittman** [comment]
+1 to a channel rename vs new channel.

**Comment by coderanger** [comment]
We did indeed rename to `#kubernetes-contributors` and it seems to have helped. Closing this out since I think this is as addressed as it can be for now.

/close
