### ISSUE TITLE
Automation of twitter posts

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes/community#4825]
Relates to #4626 

We have a number of recurring outreach opporutnities that will come out of the Twitter efforts of contributor communications. 

- Occasional `good-first-issue` notifications
- Weekly community group meeting calendar link 
- Shout outs from Slack 

The exact method to automate isn't determined yet and this issue is intended to capture the discussion around it. These posts will need to follow the same review process as others, which is also TBD. It will ideally happen in Twitter using existing infrastructure and processes. 

cc @chris-short and @kaslin who are leading the effort. 
cc @gkarthiks @rajula96reddy who are interested in helping. 

/area contributor-comms 
/sig contributor-experience

**Comment by mbbroberg** [comment]
:point_up: @mrbobbytables that error doesn't seem to be accurate given the labels were applied. Thoughts on it being a bug?

**Comment by mrbobbytables** [comment]
@mbbroberg It's occasionally happened before, not sure what triggers it, but can ping in sig-testing about it

**Comment by Pensu** [comment]
Adding the feature request from marketing meeting discussion: We should add an automation for time-zone aware posting of tweets. This will help us in getting more engagement and will increase our reach across the globe. For example, if a blog (thanks @kaslin!) is tweeted during working hours in NA/EU/APAC time zones, the likelihood of getting more eyes on it increases. Here is what the process would look like:

- Define the frequency that would be enough to cover the globe - Based on discussion, 2 sounds good to get started.
- Define the time - Once during morning hours of Americas timezones (ET/PT) and 2nd one during APAC early hours. 

Just to keep a corner case scenario out, we would have to keep an eye on time aware tweets, so that we don't post expired stuff.

**Comment by mbbroberg** [comment]
This is completed by the creation of https://github.com/kubernetes-sigs/contributor-tweets
