### ISSUE TITLE
Namespace in terminating state

### ISSUE THREAD

**Issue by bond007007** [kubernetes/community#4845]
I have a kubernetes cluster of version 1.15.3.
From last few days I observing that all the namespace which I am deleting (kubectl delete ns <xyz>) are going into terminating state.

Though I have tried to edit json (finilizer) after that I used curl command to delete the namespace. But still my namespace is in terminating state.
Plz help me in resolving my issue.
Thankyou.

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum or Stack Overflow to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/triage support
/close
