### ISSUE TITLE
devel: broken link in generating-clientset.md

### ISSUE THREAD

**Issue by miton18** [kubernetes/community#4882]
I was looking for some documentation about Expansion generator, but in this page
[https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md)

title: 3. Adding expansion methods

>  For example, this file adds...

the __file__ link is broken

**Comment by nikhita** [comment]
@miton18 Good catch!

That file references manually written methods in the expansion interface for pods' client. The link should be updated to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/pod_expansion.go.

Marking this as a good first issue since it involves a link change.

/good-first-issue
