### ISSUE TITLE
NCW2: Write video recording guide

### ISSUE THREAD

**Issue by jberkus** [kubernetes/community#4893]
We will be prerecording most new NCW segments.

To help folks create their NCW segments, we'll need guides to doing easy recording of sessions for the presenters, most of whom are working from home.

Ideally, we want guides and advice for all of the following tools:

- [ ] Zoom, Meet, and other conferencing software to record.
- [ ] Open Broadcast Studio
- [ ] native Windows, Linux, and/or Mac screencasting software
- [ ] Any other popular and/or free recording software

These guides should include all of the following:

1. Setup instructions
2. Advice on optimizing audio and video
3. How to collect the recording
4. Easy ways to edit the video, if available
4. How to transcode the recording, if necessary
5. How/where to upload it.

Since there will be a lot of content overlap between tools, we'll collab on common sections like transcoding/uploading.

/sig contributor-experience
/kind documentation
/area new-contributor-track
/help-wanted

attn: @alisondy @markyjackson-taulia @chris-short

**Comment by chris-short** [comment]
I’m going to be honest here, we need to pick a preferred method and stick to it. Otherwise we’ll be getting varying degrees of quality, resolutions, etc. We can give platform specific options, of course, but building guides for infinite scenarios doesn’t seem reasonable. If there’s a universal option, I’d much prefer writing one guide over n+1.

I also mention this because hardware requirements for folks screen recording and recording a web cam can often be pretty high. My Red Hat issued Mac couldn’t pull off a dual OBS setup. I ended up having to pre-record a talk with proprietary software. If we’re building guides, we have to assume people have limited compute options too.

If we think Zoom cloud recordings are high quality enough, I would encourage sending everyone down that route as opposed to myriad options for recordings ending up in varying outputs.

**Comment by jberkus** [comment]
We can suggest one option first, but given how we're crowd-sourcing production, we need to have multiple options.

Can you figure out how to test recording yourself using zoom, and check the quality?

**Comment by alisondy** [comment]
@jberkus I just tested the local zoom recording thing

it's decent

How to test
- Start a meeting with yourself
- Get the presentation slide setup with the screenshare
- Once thats all setup click the record button
- when y ou click end meeting the video should export locally if you're doing the local record option

The quality of the audio and video was good for me

**Comment by jberkus** [comment]
[Started guide draft](https://docs.google.com/document/d/1gpOhG8uaXSVyVycsi2_A-TyEpTDEIV_vpbaYOwSlf04/edit?usp=sharing)

**Comment by jberkus** [comment]
@tokt is helping with this, even if I can't assign him.
