### ISSUE TITLE
Convert to your timezone link shows the wrong time

### ISSUE THREAD

**Issue by lizhuqi** [kubernetes/community#4961]
I clicked the "Convert to your timezone" link in README.md doc, it shows 10:30AM for our local time(PST). However the right PST time shall be 9:30AM so I think the time converter is not converting the time correctly.
![TimeConverter](https://user-images.githubusercontent.com/15763677/87459637-7c6afb00-c5c0-11ea-914b-fcb0e4fe5d4c.png)

**Comment by lizhuqi** [comment]
@k8s-ci-robot 
/sig windows

**Comment by mrbobbytables** [comment]
It looks like because the timezone is set for Eastern Standard Time when it is currently Eastern Daylight Time. This should be set to Eastern Time (ET) instead of Eastern Standard Time similar to how it is done for ContribEx:

https://github.com/kubernetes/community/blob/421c198faf48e640ce704c0a56355c67993ab88c/sigs.yaml#L1090-L1093

That will avoid it falling out of sync when daylight savings time is in effect.

After updating the [tz field](https://github.com/kubernetes/community/blob/master/sigs.yaml#L2327) for sig windows in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) to be `ET (Eastern Time)` if you run `make` it should propagate the change to all other locations.


/help
/good-first-issue

**Comment by NagarajGoud** [comment]
I think i can start my journey with this.
