### ISSUE TITLE
metrics "certmanager_certificate_expiration_timestamp_seconds" confusions and questions

### ISSUE THREAD

**Issue by qfny88** [kubernetes/community#5093]
Hi, we are facing some issue with a custom alarm created in Prometheus:

certificate_expires_within_7_days.json
{
"alert": "CertificateExpiresWithin7Days",
"expr": "((certmanager_certificate_expiration_timestamp_seconds - time()) / 60 / 60 / 24) <= 7",
"for": "5m",
"labels": {
"severity": "CRITICAL"
},
"annotations": {
"summary": "Certificate expires within 7 days (name {{ $labels.name }})",
"description": "Certificate expires within 7 days.\n VALUE = {{ $value }}\n LABELS: {{ $labels }}"
}
}

As you can see, alarm is based on a query to certmanager_certificate_expiration_timestamp_seconds. It should be triggered EVERY TIME any cert managed by cert manager is about to expire in 7 days or less.

During tests I've created a service with certificate duration set to 10 minutes and renewal time set to 5 minutes.

kubectl get certificate -n netguard-smc nsmc-connector-was-was-check-cert3-crt -o yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
creationTimestamp: "2020-08-18T12:41:19Z"
generation: 1
name: nsmc-connector-was-was-check-cert3-crt
namespace: netguard-smc
resourceVersion: "2813223"
selfLink: /apis/cert-manager.io/v1alpha2/namespaces/netguard-smc/certificates/nsmc-connector-was-was-check-cert3-crt
uid: fcabde86-4949-49d5-b772-352e948fa69d
spec:
commonName: nsmc-connector-was-was-check-cert3.netguard-smc.svc.cluster.local
dnsNames:

nsmc-connector-was-was-check-cert3.netguard-smc.svc.cluster.local
duration: 10m0s
issuerRef:
kind: ClusterIssuer
name: ncms-ca-issuer
keySize: 2048
organization:
Nokia
renewBefore: 5m0s
secretName: nsmc-connector-was-was-check-cert3-tls
status:
conditions:
lastTransitionTime: "2020-08-18T12:41:20Z"
message: Certificate is up to date and has not expired
reason: Ready
status: "True"
type: Ready
notAfter: "2020-08-19T10:56:20Z"
Cert manager is still sending metrics to Prometheus for the service:

certmanager_certificate_expiration_timestamp_seconds {
app = "cert-manager",
app_kubernetes_io_instance = "cert-manager",
app_kubernetes_io_managed_by = "Tiller",
app_kubernetes_io_name = "cert-manager",
exported_namespace = "netguard-smc",
helm_sh_chart = "cert-manager-v0.13.1",
instance = "wroclaw-farm-2003-18-auto-sec0423-1987-worker-01",
job = "kubernetes-pods",
kubernetes_pod_name = "cert-manager-676784f654-nwlfl",
name = "nsmc-connector-was-was-check-cert3-crt",
namespace = "ncms",
pod_template_hash = "676784f654"
}
value: 1597834580

The cert has been renewed many times until now, but only one alarm has been created for this service based on values from the metric. From my point of view it seems that cert is renewed internally but for Kubernetes it is still the same instance of certificate/ secret that has been created on the service initialization a few hours ago, so any new alarm will not be created.

kubectl get certificate -n netguard-smc nsmc-connector-was-was-check-cert3-crt
NAME READY SECRET AGE
nsmc-connector-was-was-check-cert3-crt True nsmc-connector-was-was-check-cert3-tls 22h
kubectl get secrets -n netguard-smc nsmc-connector-was-was-check-cert3-secrets
NAME TYPE DATA AGE
nsmc-connector-was-was-check-cert3-secrets Opaque 4 22h
kubectl get secrets -n netguard-smc nsmc-connector-was-was-check-cert3-tls
NAME TYPE DATA AGE
nsmc-connector-was-was-check-cert3-tls kubernetes.io/tls 3 22h

Questions:

Is the metric data from cert manager proper? It seems that the "Value" field for the metric is related with "notAfter" (expiration) field from the certificate, but sometimes it shows time value that should pass until cert is renewed (not expired).
If the expression from the alert (above) seems to be OK, why the alert is triggered only once event though the metrics are being sent be cert-manager

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/triage support
/close
