### ISSUE TITLE
Zoom Automation Review

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5201]
The splain automation has been incredibly flakey. Many meetings not being uploaded at all, and for the sigs that have had it configured they believe everything is working as intended. 

Splain has been contacted multiple times about the flakeyness of uploads, without any real solution.

We should investigate other options - zapier has some integrations that might work as an alternative.

Details [Paris updating]:
- near ~40 zoom accounts (1 per group and some special ones) with cloud recording possibilities 
- we have google workspace - buckets, can create special accounts, etc. sig-k8s-infra owns much of this 
- we can get funding for tooling
- we have YouTube and zoom admins currently with access to keys, secrets, and cloud recordings 

/assign @castrojo @mrbobbytables 
/sig contributor-experience
/area community-management
/milestone v1.20

**Comment by castrojo** [comment]
Quick in progress update, still early days. We want to be able to upload to youtube without needing to give the near 100 chairs/tech leads admin access on youtube, what I've prototyped so far is:

1) zapier zap from a SIG Zoom account to the K8s google drive. 
2) zapier zap from K8s google drive to youtube via the contributors@ gsuite account.

We can even set the visibility as private by default so we can admin at the youtube level without having people need to go directly into the gsuite. We'd need to make a /videos or somesuch directory for each sig in the gdrive.

We would need to create two zaps per SIG, one to push from zoom to drive, and one to push from drive to youtube. We'd need to increase the day-to-day youtube team to handle the reviews, and while it is a ton of work it would make it much easier for SIGs, so IMO we should do it. Zapier has nice abilities to clone existing zaps so it's not so bad, and we can template stuff so that all the information from the zoom meeting ends up in the description of the youtube video, so maintenance for SIGs in the future would just be keeping your zoom meeting up to date (which you need to do anyway!) and the resulting vid in youtube would have the proper metadata. 

We can easily consume lots of zapier actions so we'd need to do a paid account and handle all the billing as well as keys to the account and the usual contribex minutea.

**Comment by mbbroberg** [comment]
Both @gkarthiks and I are interested and inexperienced with Zapier. Let us know how we can help (and get access to build out more automation for Comms) 👋

**Comment by chris-short** [comment]
Where do we stand with Zapier? I'm asking because of issue #5156.

**Comment by mrbobbytables** [comment]
cc @castrojo ^^

**Comment by alisondy** [comment]
I've had a chat with Bob, and we've come to the conclusion that we should pursue the zapier route

[ ] test out zapier zoom youtube meeting
[ ] document process
[ ] plan rollout on all meetings currently using splain

let me know if theres anything else that I've missed in this list

**Comment by markyjackson-taulia** [comment]
I checked with @alisondy if it was ok that I worked this
/assign @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
Zapier integration is fairly straightforward. The steps are as followed:
1. Setup the zoom account to link to the youtube account
2. Set the privacy level. In our case, we will set it to private so a YouTube admin can audit
3. Turn on the trigger action. In our case, it will be a `New Recording` upload

Some items we will need to work through:
1. There is a cost associated with Zapier. It does come with a 14-day free trial
2. We will need to coordinate with all SIG's to set up the youtube side with their zoom accounts. This may be a good time to audit those accounts as well.
3. Document the process
4. [Stretch goal] Automate the entire process

I will need to work with @mrbobbytables on implementing this but starting with contribex is a great and easy start. I will work on the contribex side Monday, as I will need the contribex zoom account info (thought I had it but do not).

**Comment by pnbrown** [comment]
Gonna be helping sort out some automated posting.

**Comment by pnbrown** [comment]
I'm out right now but there has been some progress with integration on Zapier. Can reliably get from Zoom to Google Drive. Need to test naming when I'm back and then Google Drive to YouTube.

Still would like to have a meeting with you regarding this, @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
@pnbrown totally. I am on vacation from tomorrow to next week, lets sync then and thank you.

**Comment by markyjackson-taulia** [comment]
@pnbrown If you have some cycles this week or next, let me know

**Comment by pnbrown** [comment]
> @pnbrown If you have some cycles this week or next, let me know

I'm still out but ping me on Slack. We can meet briefly.

**Comment by pnbrown** [comment]
The proof of concept automation is built in Zapier and running on the Sig-ContribEx account

**Comment by pnbrown** [comment]
/remove-lifecycle stale

Not much update from last tag removal. Need to move the automation to other Zapier and see about running it on SIG channels. Probably some prices needed here for rollouts

**Comment by pnbrown** [comment]
Zoom Automation is in a k8s Zapier account and the process for adding other SIGs through Zapier is safe to begin
