### ISSUE TITLE
[Developer Guide Audit] API Machinery

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/community#5230]
Documentation is the go-to reference for contributors. Parts of the developer guide have been cited as vastly out of date (e.g. referencing VERY outdated versions of docker). We are asking each SIG that owns a portion of the developer guide to audit their [devel guide documentation](https://github.com/kubernetes/community/tree/master/contributors/devel/). 

**This does not have to include updating it.**
(although if you want to, please go ahead 😄 )

If you could, update this issue with items that are out of date or you think should be added to the [API Machinery](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-api-machinery) portion of the devel guide. 

Assigning to leads, but please feel free to re-assign and delegate.
/assign @deads2k @fedebongio @lavalamp 

**Potential Related Item**
- [Proposal: document structure of annotation/label namespaces more completely](https://github.com/kubernetes/community/issues/300)

---
Parent Tracking Issue: #5229 
/sig api-machinery
/sig contributor-experience
/area developer-guide
/milestone v1.20

**Comment by lavalamp** [comment]
@apelisse and/or @jpbetz, can one of you do this?

**Comment by apelisse** [comment]
@jpbetz, I'll let you look at [controller](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/controllers.md) and [generating clientsets](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md) since if it's not deprecated, it will soon thanks to what you're doing.
I'll definitely look at [strategic merge patch](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md) 🔥

**Comment by apelisse** [comment]
@mrbobbytables I assume we should also suggest additions to the doc for missing features?

**Comment by mrbobbytables** [comment]
> @mrbobbytables I assume we should also suggest additions to the doc for missing features?
Yup. It gives us a good starting point to get those items documented.

**Comment by apelisse** [comment]
I've briefly looked at it, and to be honest, it's very hard to know if this is correct or not, since no one wants to touch "strategic-merge-patch" with a ten foot pole. We have limited knowledge on this (@mengqiy might). As far as I know, there are no other implementation of strategic-merge-patch in any other language, and the only existing implementation is directly (through staging) in Kubernetes. I've seen the code being used in other places but I don't think there is another implementation. Also, this is probably fine because we're trying to retire it anyway.

I'm sure we could improve our existing documentation for server-side apply, but I'm curious if we need to have an additional section here, does it serve a different purpose compared to what we already have (https://kubernetes.io/docs/reference/using-api/server-side-apply/)?

**Comment by mrbobbytables** [comment]
Just wanted to check back in on this, 
@apelisse do we have a ballpark release target to deprecating strategic-merge-patch?
re:SSA, maybe just a pointer to the docs on kubernetes.io? Namely, if someone is coming here for api-machinery docs, they might not know of the info on kubernetes.io


@jpbetz did you happen to give the controller and generating clientsets a look?

**Comment by apelisse** [comment]
> @apelisse do we have a ballpark release target to deprecating strategic-merge-patch?

We don't, and it's unclear if we can do it, or how. We would probably the field tomb-stoning part of server-side apply to formally deprecate SMP, but we don't have consensus on that feature yet.

We need to see how people use server-side apply to know exactly what we'll be needed. Time will tell.
/remind-me in 3 years :-)

**Comment by apelisse** [comment]
> re:SSA, maybe just a pointer to the docs on kubernetes.io? Namely, if someone is coming here for api-machinery docs, they might not know of the info on kubernetes.io

Yes, that's a good idea.

**Comment by MadhavJivrajani** [comment]
Hi! 

Please feel free to re-direct me if this isn’t the right place to ask this: I’ve noticed that there isn’t a lot of developer documentation around topics such as different components of client-go informers. A few of us usually do code walkthrough sessions on such topics and try and document them as well. @nikhita suggested that it might be a good idea to have these documented as part of the developer documentation so as to help make it available to a larger audience. 

An example of such documentation would be [this](https://www.notion.so/client-go-Informers-7d5aecc535a04239b20d8f7c6f874637) on informers. 

I mainly wanted to ask and get a feel of whether something like this already exists and if not, would folks be okay with having something like this as part of the developer documentation for api-machinery. 

Thanks!

**Comment by MikeSpreitzer** [comment]
@MadhavJivrajani : I think it is important to distinguish two sorts of documentation.  One is aimed at the larger audience of _users_ of client-go.  I do not think these folks need a walk-through of the implementation of informers; regarding informers, that audience only cares about the interface.  OTOH, they _do_ deserve documentation about how to write controllers.

The other sort of documentation is aimed at the smaller audience of _implementors_ of client-go.  I also tried to write some doc for them, at https://github.com/kubernetes/client-go/blob/bcf88f084d9bbbf970b9824ba2eb449efea9e24a/tools/cache/shared_informer.go#L274-L286 .  I attempted only a brief outline because implementation details change relatively frequently and it is not uncommon for those changes to neglect keeping the comments up-to-date.

**Comment by MadhavJivrajani** [comment]
> I do not think these folks need a walk-through of the implementation of informers; regarding informers, that audience only cares about the interface. OTOH, they do deserve documentation about how to write controllers.

That's a good point. IIRC, there's some devel docs on writing controllers, in that

**Comment by MadhavJivrajani** [comment]
> I attempted only a brief outline because implementation details change relatively frequently and it is not uncommon for those changes to neglect keeping the comments up-to-date.

Thanks for this! 
I do think that having some devel documentation that is centred around interaction among high level entities (an example would be devel docs around [sig-scheduling](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scheduling/scheduler_queues.md)) rather than implementation details might be helpful for implementer/contributors to client-go.

**Comment by sftim** [comment]
/triage accepted
Yes, this is a good thing to do.

If folks want advice about how to write these docs, ask in #sig-docs on Kubernetes Slack.
