### ISSUE TITLE
SIG Storage - NFS Supplemental Groups not working

### ISSUE THREAD

**Issue by Boes-man** [kubernetes/community#5321]
/sig sig-storage

Kubernetes: 1.17.11
[NFS Volumes](https://kubernetes.io/docs/concepts/storage/volumes/#nfs)

The external nfs export is using Group based ID for permissions on the folder. EG:
ls -lZ /data/folder
drwxrwsr-x 2 root 1140214 ? 4096 Sep 30 08:55 subfolder1
drwxrws--- 2 root 1140214 ? 4096 Sep 30 08:55 subfolder2
drwxrws--- 2 root 1140214 ? 4096 Sep 30 08:55 work

It is expected the the pod security context would need an entry for supplementalgroups, in this case supplementalGroups: [1140214] for the pod to be able to rw into /data/folder/work (for example).

We have found the pod being able to mount the nfs volume and access up to /data/folder, but get permission denied for /data/folder/work

We have found a workaround by using runAsUser (65534 )and runAsGroup (1140214), no supplementalGroups , but the problem is that the application code in the container now needs to be revisited to change the folder permissions to work with these UID and GIDs.

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
