### ISSUE TITLE
pod cidr not assigned during kubeadm init

### ISSUE THREAD

**Issue by srinathkm** [kubernetes/community#5339]
This issue started happening after the system was updated using yum. Currently the OS details are :

**Linux abcd.com 5.4.17-2036.100.6.1.el7uek.x86_64 #2 SMP Thu Oct 29 17:04:48 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux**

After kubeadm init, checking the pods and nodes shows : kubectl get nodes,pods -n kube-system shows status as CrashloopBackoff. For eg : 

NAME                                                  READY   STATUS    RESTARTS   AGE
pod/kube-flannel-ds-kq47c                             0/1     CrashloopBackoff   0          5s

On checking the logs for the flannel pod as : 

kubectl logs kube-flannel-ds-kq47c --namespace=kube-system 

shows the following error :

**I0613 09:03:38.016281       1 vxlan.go:120] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false,
E0613 09:03:38.016872       1 main.go:280] Error registering network: failed to acquire lease: node "hostname" pod cidr not assigned**

Root cause of this issue is /etc/kubernetes/manifests/kube-controller-manager.yaml file does not have the following entries: 

- --allocate-node-cidrs=true
- --cluster-cidr=10.244.0.0/16

kubeadm version: 
**&version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:15:05Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}**

This issue is similar to https://github.com/coreos/flannel/issues/728

Is there a solution to this issue or the workaround of adding the entries in the yaml file is still the way to go?

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/triage support
/close
