### ISSUE TITLE
csi plugin container mount lustre failed

### ISSUE THREAD

**Issue by GodGirlwsy** [kubernetes/community#5364]
Operation for "\"kubernetes.io/csi/lustreplugin.csi.h3c.com^lustre-csi-pv\"" failed. No retries permitted until 2020-12-15 14:37:00.574828082 +0800 CST m=+2383.010640361 (durationBeforeRetry 16s). Error: "MountVolume.SetUp failed for volume \"lustre-csi-pv\" (UniqueName: \"kubernetes.io/csi/lustreplugin.csi.h3c.com^lustre-csi-pv\") pod \"deployment-lustre-5ffb8566b7-vqk5k\" (UID: \"dc3e451a-3e9f-11eb-96b2-0cda411d2b9a\") : rpc error: code = Unknown desc = Lustre, Mount Lustre fail: %!s(MISSING)Failed to run cmd: mount -t   lustre 186.31.29.29@tcp: /var/lib/origin/openshift.local.volumes/pods/dc3e451a-3e9f-11eb-96b2-0cda411d2b9a/volumes/kubernetes.io~csi/lustre-csi-pv/mount, with out: mount: mounting 186.31.29.29@tcp: on /var/lib/origin/openshift.local.volumes/pods/dc3e451a-3e9f-11eb-96b2-0cda411d2b9a/volumes/kubernetes.io~csi/lustre-csi-pv/mount failed: No such device\n, with error: exit status 255"

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
