### ISSUE TITLE
nginx - Not able to connect to External IP of a VM in GCP from a browser

### ISSUE THREAD

**Issue by amar2k05** [kubernetes/community#5383]
Hi,

I have created 1 MAster and 1 Worker node on GCP with below config.

Master - E2 Small(2 vCPU, 2GB Memory), CentOS7, Standard Persistent Disk - 20GB, Allow http,https traffic

Worker - E2 Micro(2 vCPU, 1GB Memory), CentOS7, Standard Persistent Disk - 20GB, Allow http,https traffic

I have created an nginx POD and exposed it to outside internet using NodePort service.

But I am not able to access from broswer. I used below

http://34.67.102.11:30084/

IP is the Master Node VM External IP which i got from GCP Console

NodePort i have got describing the service.

Kindly let me know if i am missing anything.

Thanks,

Amarnath.

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
