### ISSUE TITLE
Kubernetes scanner commands issue

### ISSUE THREAD

**Issue by MohdRashid01** [kubernetes/community#5431]
Hello Everyone,

I have issue with this command as when i execute in terminal i got Flag --generator has been deprecated

Can anyone help me out with this issue.

kubectl run --generator=run-pod/v1 net-test --image=net/bot:latest --env="FX_HOST=cloudnetwork.net.com --env=“FX_IAM=Mwc/0zF7dfX+PUq6JxxxxxdbFUExxeL5” --env=“FX_KEY=chFPCKn+EB00tUxxxwX0WuYlLCtM1Gr/kQxx+UxR1nxxK6nSrvxxxOFT8Mo” --replicas=2

Flag --generator has been deprecated, has no effect and will be removed in the future.Flag --replicas has been deprecated, has no effect and will be removed in the future.Error from server (BadRequest): the server rejected our request for an unknown reason

**Comment by MohdRashid01** [comment]
But how can i add sig labels and where i need to add sig label ...can you write for me and send me ...so that i can easily understand

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
