### ISSUE TITLE
In eks cluster load balancer is not deleted if i have deleted cluster and node-pool

### ISSUE THREAD

**Issue by Ankita5892** [kubernetes/community#5438]

**Comment by nikhita** [comment]
@Ankita5892 Please re-post your question to our [Discussion Forums](https://discuss.kubernetes.io)
with more information about the exact issue you are facing.

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
