### ISSUE TITLE
Egress Network policy definition

### ISSUE THREAD

**Issue by firoshaq** [kubernetes/community#5598]
Hi Team,

I have been creating egress network policy using the official [documentation](https://kubernetes.io/docs/concepts/services-networking/network-policies/) under my name space in an AKS  cluster. I am using calico network plugin. I see that in the documentation we are able to only use  `cidr`range but with openshit we were able to use both `cidr` as well as `dnsname` as mentioned from [here](https://docs.openshift.com/container-platform/4.3/networking/openshift_sdn/configuring-egress-firewall.html#egressnetworkpolicy-rules_configuring-an-egress-firewall). So could you please let me know if we have any alternative for specifying `dnsname` in aks as well because when I use the same I get get a resource not found error.

Any help would be appreciated.

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
