### ISSUE TITLE
Mega/Process KEP changes & the Community Meeting

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#5730]
**Goals:**
- more communication and 
- more discussion/ feedback / consensus around mega and wide community process changes KEPs 
  - more than 3 cross cutting SIGs (arbitrary number) AND KEPs that are strictly around large community process changes 

**Knowns:**
- we have space at the community meeting now for large group discussions for ~30 minutes; we are also looking for content (aka it's not overflowing right now) cc/ #5462 
- KEPs are hard for large community process changes (example: #3795)
- KEPs are also hard to communicate across many sigs and wgs 

**Possible solution:**
- save 30 minutes of the Monthly community meeting for at least one KEP discussion
- Invite KEPs that meet a certain criteria to a Community Meeting for an up to 30 minute discussion
- (out of scope for this issue: the rest of the 30 minutes can be devoted to release and community updates as well as announcements, shoutouts, etc.)
- require KEPs have a discussion at the community meeting for ones that meeting Some Criteria
  - consider in terms of impact to end users
  - maybe PRR has a part to play here?
  
**Open questions:**
- what's the arbitrary number definition for how many sigs a kep should cross cut to warrant a community meeting? 3, 6, 9? Half of the groups we have at Time? Half of all vertical SIGs?
- who would be point on the facilitation? KEP author? SIG Lead?
- could someone from the release team flag which KEPs are good or should there be an automated process?

**Comment by kikisdeliveryservice** [comment]
Q: would the idea to be get feedback on the KEP or present the KEP to the community as an informative thing?

If it's the latter, I'd probably consider them in terms of impact to end users and also perhaps thinking about the PRR (Production Readiness Review) that captures a lot of those concerns in some combination with KEPs that SIGs (who now have more ownership/control over KEPs) want to highlight?

**Comment by parispittman** [comment]
@kikisdeliveryservice - love it! 

first q: I think more of the latter and but driving folks to participate in the KEP with feedback is also awesome. I'm inclined to use the why not both emoji here. :D

**Comment by mrbobbytables** [comment]
> require KEPs have a discussion at the community meeting for ones that meeting Some Criteria
consider in terms of impact to end users
maybe PRR has a part to play here?

I'm all for talking about KEPs, but I don't think we should require it. With the community meeting being monthly it could hold things up significantly for KEPs to be merged.

**Comment by kikisdeliveryservice** [comment]
@parispittman We discussed this in the Enhancements meeting and we believe that having a forum to communicate about KEPs is a great idea but that the usage of the meeting is best left up to SIGs. Since SIGs own KEPs and planning we believe the decision to discuss/present KEPs should start first with them.  We'd love for you to share this offer with SIG leads for their feedback and ideas of whether such a meeting would be useful to them. :smile:

**Comment by celestehorgan** [comment]
> KEPs are hard for large community process changes (example: #3795)

I think I understand the internal pressure/need here, particularly around long-winded KEPs, however I think the core of the issue seems to be not a _lack_ of discussion but really that there's too much discussion, and (particularly for process KEPs) it's unclear when the discussion can come to an end. This leaves KEPs that are open for long periods of time and dramatically increases the mental burden on the KEP owners.

1. Who has the authority to decide that discussion is over on a KEP?
2. Can those people decide to leave certain comments or comment threads unresolved if they feel the comments are too divergent from the scope of the KEP/bikeshedding?
3. In the case of process KEPs – process KEPs get proposed, typically, because the owning SIG realizes that they're proposing a cross-cutting policy change. Who owns approval on cross-cutting policy changes? 

To be opinionated and answer my own questions:

1. Once they have approval from the appropriate SIGs/approvers, the KEP owner can end discussion at will.
2. I think the KEP owner is responsible for addressing the overwhelming majority (say, 80%+) of comments on a KEP, but if 10-20% of them are either out of scope or the original commenter refuses to budge in their opinion, I think the KEP owners, as the people who are responsible for carrying out the work on the KEP, have the right to leave certain comments unresolved.
3. IMHO, Steering should be the approver on anything that looks like a process/policy KEP, as these are cross-cutting :)

**Comment by justaugustus** [comment]
Related on communications for large charges: https://github.com/kubernetes/community/issues/5344

**Comment by BenTheElder** [comment]
> IMHO, Steering should be the approver on anything that looks like a process/policy KEP, as these are cross-cutting :)

1000 times this. and generally everything else in https://github.com/kubernetes/community/issues/5730#issuecomment-828054855

**Comment by parispittman** [comment]
closing this since consensus was not reached 

/close
