### ISSUE TITLE
Missing documentation license

### ISSUE THREAD

**Issue by CsatariGergely** [kubernetes/community#5734]
The community repo has only an Apache 2.0 License in the LICENSE file and there is no indication that all documentation is licensed under [CC BY 4.0](https://git.k8s.io/website/LICENSE) what should be the case according to the [CNCF charter](https://github.com/cncf/foundation/blob/master/charter.md).

**Comment by mrbobbytables** [comment]
I believe all docs are covered by the LICENSE at the root (apache 2)
cc @swinslow 
What are your thoughts?

**Comment by CsatariGergely** [comment]
@mrbobbytables according to some interpretations Apache License 2.0 is a code license, this is why the documentation usually is licensed with a different license, like CC BY 4.0. The CNCF Charter also suggests this way.

**Comment by nikhita** [comment]
@swinslow @caniszczyk can you provide guidance here?

**Comment by swinslow** [comment]
Hi all, yes, under the [CNCF charter (section 11(f))](https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy) documentation should be under the CC-BY-4.0 license. The [Kubernetes website](https://kubernetes.io) for instance indicates this in the footers at the bottom of its pages.

**Comment by mrbobbytables** [comment]
@swinslow This is with regard to all the markdown docs within the community repo and elsewhere. It's easier to flag that on the website where ALL the content is intended to be CCBY.

**Comment by CsatariGergely** [comment]
It would be more clear for the contributors if the license would be part of the repo with an indication that all .md files are licensed with CC BY 4.0. One good way to express this is using [REUSE](https://reuse.software/).

**Comment by nikhita** [comment]
IIUC if a repo contains code _and_ markdown files, it needs to use the Apache 2.0 license. @swinslow can you please confirm?

**Comment by CsatariGergely** [comment]
> 
> 
> IIUC if a repo contains code _and_ markdown files, it needs to use the Apache 2.0 license. @swinslow can you please confirm?

Even if the documentation in the markdown files are licensed with CC BY 4.0?

**Comment by CsatariGergely** [comment]
@nikhita @swinslow can you please suggest how to move forward with this?

**Comment by nikhita** [comment]
@swinslow @caniszczyk can you please provide guidance here?

**Comment by caniszczyk** [comment]
There are also some folks that would consider .md files "code" and since this project repo has code and isn't really a public facing website, I don't see why we need to add a "LICENSE-docs" here, but if you wish

These two licenses are very similar in spirit so I think this is a non issue, they both require attribution at the end of the day.

**Comment by CsatariGergely** [comment]
Clear distinction of code and docs license makes contributions more easy for us. Thanks.

**Comment by CsatariGergely** [comment]
Is it okay if I prepare a pr to cover this?

**Comment by tpepper** [comment]
> Clear distinction of code and docs license makes contributions more easy for us. Thanks.

Can you elaborate on this?

**Comment by parispittman** [comment]
For context to folks reading this, I asked @CsatariGergely to come and talk to us at a Steering Committee meeting, unfortunately it can't happen in December due to Nokia schedules. I offered a contribex meeting but the Steering Committee has decided that is not an appropriate venue for this conversation. 

Speed up to now/the latest :)
@CsatariGergely, we'd like to welcome you and any other Nokia reps to our January 3, 2022 meeting. If you'd like to continue the discussion in the meantime, we are happy to here on this issue or at one of our mailing list options: steering@kubernetes.io or steering-private@kubernetes.io. thanks!

**Comment by cblecker** [comment]
Relates to: https://github.com/kubernetes/community/pull/6502
