### ISSUE TITLE
faild to deploy nginx controller

### ISSUE THREAD

**Issue by bec1442** [kubernetes/community#5849]
I followed a tutorial to configure an internal nginx-controller and worked just like the tutorial.
I wanted to re-enforce the learning by repeating the tutorial so I did delete the namespace first
>Kubectl delete namespace ingress-basic
But trying again, I get error.  Even if I change the namespace (“ingress”), still reference to old 
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "nginx-ingress-ingress-nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "ingressc": current value is "ingress-basic"
The command kubectl get namespace -A shows nothing regarding old namespace.
What am I missing?

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
