### ISSUE TITLE
Document the overlap (or not) between Server Side Apply and Kustomize

### ISSUE THREAD

**Issue by JohnRusk** [kubernetes/community#5887]
When reading the Kustomize documention, I came to this page https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md  which says that Strategic Merge is probably obsolete and Server Side Apply is the way to go.  

But I can't find anything that explains when to use Kustomize (and Strategic Merge) and when to use Server Side Apply.  That needs to be documented.

The question has already been asked, but not answered, here https://github.com/kubernetes-sigs/kustomize/issues/2427

cc @apelisse why created the commit about Strategic Merge being obsolete.

**Comment by coderanger** [comment]
The two are kind of unrelated? Kustomize is a CLI tool for combining multiple YAML files together into a single manifest for a given environment (or whatever). Server Side Apply is a type of API request for managing API objects. The merge in Kustomize is different from an API PATCH request because it's not thinking about "live object" vs "patch data", it has two chunks of user input and is combining them. So it doesn't have to worry about living data, there is none in Kustomize, it's 100% only user input. Also if this was going to be documented it would probably be in the Kustomize docs?

**Comment by coderanger** [comment]
Also the most common use case for Kustomize is something that boils down to `kustomize build ... | kubectl apply -f -` so the first bit is Kustomize's compilation and the second bit either currently uses SSA or will soon (depending on your setup and arguments).

**Comment by JohnRusk** [comment]
That makes sense @coderanger . The confusing bit is that when I read the Kustomize documentation, that takes me to the above-mentioned page about Strategic Merge Patch, which tells me that Strategic Merge Patch is obsolete. The implication is that its obsolete _in the context of kustomize_ (where it is used).  I take it, from your comments just now, that that implication is incorrrect?

**Comment by coderanger** [comment]
Yeah, SMP as an API request type (more specifically a type of PATCH request) is on the way out. It's not clear exactly how the code with shake out, if kustomize will inherit it directly or what but it's an extremely different use case :) API deprecations don't apply to things that aren't the API. Also that said, most users of Kustomize that I've seen don't even use the special magic SMP keys, since kustomize groks the schema-level stuff like keyed arrays directly.

**Comment by JohnRusk** [comment]
Thanks. Makes sense. I think the only problem, if there is one, is that the Kustomize docs hyperlinked into the SMP _general purpose_ docs.

**Comment by JohnRusk** [comment]
Not sure if it's worth fixing the Kustomize docs.

**Comment by coderanger** [comment]
I leave that up to the Kustomize team :) I think there's nothing in particular to fix on the Kubernetes core side though since the two topics have nothing to do with each other aside from a passing historical connection.

**Comment by caerulescens** [comment]
> The confusing bit is that when I read the Kustomize documentation, that takes me to the above-mentioned page about Strategic Merge Patch, which tells me that Strategic Merge Patch is obsolete. The implication is that its obsolete in the context of kustomize (where it is used). I take it, from your comments just now, that that implication is incorrrect?

@JohnRusk @coderanger I think this misunderstanding is still an issue because I reached the same conclusion and then found this back and forth. Referring to the disclaimer [here](https://github.com/kubernetes/community/blob/fb45a6299d500da8347b5b9b015e9bc65fbdd91e/contributors/devel/sig-api-machinery/strategic-merge-patch.md).
