### ISSUE TITLE
mailing lists and calendar invites

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#5981]
@thockin raised this in sig-contribex

Problem:
subscribed to multiple mailing lists and those mailing lists send multiple calendar invites per group (ie big sigs with lots of subproject meetings). the amount of meetings on calendars is a burden for folks. 

Knowns:
calendars are terrible (hard to manage, timezones, ical, etc)
we have too many meetings (45+ a week)
permissions to change calendar invites has lots of layers (whoever establishes the invite is the owner)
[calendar guidelines](https://github.com/kubernetes/community/blob/master/communication/calendar-guidelines.md) 
leave comment below for others 

Proposals:
- have chairs create a mailing list for meetings only, example: sig-network-mtgs@
  - pro: chairs can still control the meeting, only people who want to attend meetings will subscribe vs read a mailing list 
  - con: yet another mailing list to add to our 250+ (small win: it won't need moderation) 
- everyone subscribe to one mega upstream k8s calendar like the one displays on k8s.dev/calendar
  - pro: everyone has all of the meetings \o/
  - con: potential issues with who can change meetings, permissions, etc; there are a lot of meetings a week, can be hard to copy to calendars and retain change info 
- yours? comment below.

**Comment by thockin** [comment]
Or one meetings-calendar per SIG?

**Comment by justaugustus** [comment]
> have chairs create a mailing list for meetings only, example: sig-network-mtgs@

+1 to per-SIG meeting calendar + list.
Most of us should already have associated calendars as part of SIG creation steps.

Voting for this one because I'm primarily interested in joining a list to get a fresh calendar invite because it blocks my availability. Depending on the email system, calendar configuration, or organizational restrictions, there's no guarantee that a separate calendar subscription will do the same.

cc: @kubernetes/sig-release for thoughts as well

**Comment by mrbobbytables** [comment]
I am +1 for separate ML for calendar invites, but I would hold off on doing anything like that right now and make it a standard pattern when sigs start to migrate to kubernetes.io managed groups.
