### ISSUE TITLE
terminationmessage path and policy not working as expected

### ISSUE THREAD

**Issue by sudheerpodila** [kubernetes/community#6029]
I am using below configuration to log the abrupt disruption in pods using terminationMessagePath  as  terminationMessagePath: /tmp/message-log and terminationmessagePolicy as  terminationMessagePolicy: FallbackToLogsOnError
but when the pods are getting restarted I am just seeing the path getting created as:
-rw-rw-rw-    1 root     root             0 Sep 12 18:13 message-log

but file size is always of 0 byte.
Is this a bug in k8 version  EKS 1.19

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
