### ISSUE TITLE
Need help with configuring jenkins proxy which is running inside pod deployed via helm

### ISSUE THREAD

**Issue by rg13567** [kubernetes/community#6097]
I  have a kubernetes cluster setup with master and worker nodes
I deployed jenkins on my worker node with helm chart. I want to configure jenkins proxy as part of deployment so that once my jenkins pod comes up it already has my proxy configured in order to install plugins.
Can anyone suggest how this can be done?

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
