### ISSUE TITLE
Why do you think resp.StatusCode = 200 is a failure?

### ISSUE THREAD

**Issue by smallAttr** [kubernetes/community#6256]
[source code](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/httpstream/spdy/roundtripper.go)

`func (s *SpdyRoundTripper) NewConnection(resp *http.Response) (httpstream.Connection, error) {
	connectionHeader := strings.ToLower(resp.Header.Get(httpstream.HeaderConnection))
	upgradeHeader := strings.ToLower(resp.Header.Get(httpstream.HeaderUpgrade))
	if (resp.StatusCode != http.StatusSwitchingProtocols) || !strings.Contains(connectionHeader, strings.ToLower(httpstream.HeaderUpgrade)) || !strings.Contains(upgradeHeader, strings.ToLower(HeaderSpdy31)) {
		defer resp.Body.Close()
		responseError := ""
		responseErrorBytes, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			responseError = "unable to read error from server response"
		} else {
			// TODO: I don't belong here, I should be abstracted from this class
			if obj, _, err := statusCodecs.UniversalDecoder().Decode(responseErrorBytes, nil, &metav1.Status{}); err == nil {
				if status, ok := obj.(*metav1.Status); ok {
					return nil, &apierrors.StatusError{ErrStatus: *status}
				}
			}
			responseError = string(responseErrorBytes)
			responseError = strings.TrimSpace(responseError)
		}

		return nil, fmt.Errorf("unable to upgrade connection: %s", responseError)
	}

	return NewClientConnectionWithPings(s.conn, s.pingPeriod)
}`

**Comment by coderanger** [comment]
Hi there, this repository is used for tracking community business and logistics. It looks like that's some code from https://github.com/kubernetes/kubernetes so that would be the place to ask in the future. But as to your specific question, that code is doing a protocol switch from HTTP to SPDY so a 200 OK response would indicate the server didn't understand the request for a protocol change which here is a failure because we can't fall back on HTTP (as opposed to stuff like HTTP2 to QUIC upgrades where usually you can safely continue on HTTP if needed). A 101 Switching Protocol response indicates that the server understood the request and is agreeing to a protocol switch, so that's the only response that is not an error here.

/close
