### ISSUE TITLE
terminationmessage path and policy not working as expected

### ISSUE THREAD

**Issue by sudheerpodila** [kubernetes/community#6282]
I am using below configuration to log the abrupt disruption in pods using terminationMessagePath as terminationMessagePath: /tmp/message-log and terminationmessagePolicy as terminationMessagePolicy: FallbackToLogsOnError
but when the pods are getting restarted I am just seeing the path getting created as:
-rw-rw-rw- 1 root root 0 Sep 12 18:13 message-log

but file size is always of 0 byte.
Is this a bug in k8 version EKS 1.19

I have already raised this query in kubernetes user forums but no one responded, awaiting solution for this problem.

https://discuss.kubernetes.io/t/terminationmessagepath-not-capturing-logs/17504

**Comment by Debanitrkl** [comment]
@sudheerpodila this is not the right place to put up this issue.
I'm not sure if this issue is with k8s itself or with the EKS. If it's the former case then you should put the issue here https://github.com/kubernetes/kubernetes/issues or ask in Kubernetes slack under #kubernetes users channel someone will help you out.
