### ISSUE TITLE
Draft schedule for Kubecon EU 2022 Contributor Summit

### ISSUE THREAD

**Issue by tokt** [kubernetes/community#6554]
### Describe the issue

Proposed event schedule:

**0900** - Breakfast and Banter, Gathering Topics
**1000** -  Welcome, and keynote?
**1100 - 1115** Close Voting, 1130 Announce Topics
**1200** - Lunch
**1300** - Unconference
**1400** - Unconference
**1500** - Afternoon Tea, 1530 Unconference
**1600** - Unconference
**1700** - Contributor Panel (topic for that?) and closing
**1800** -   (transport to the reception venue)
**1900** - Reception

Please, comment below with thoughts, ideas?

**Comment by puja108** [comment]
Based on yesterday's discussions, slightly adapted schedule:

0900 - Breakfast and Banter, Gathering Topics
1000 - Welcome
1130 Start Voting
1200 - Close Voting and start Lunch
1300 - Annpounce Unconference Schedule and first sessions
1400 - Unconference
1500 - Afternoon Tea, 1530 Unconference
1600 - Unconference
1700 - Steering AMA and closing (tell people about transport and pooling to social)
1800 -  (transport to the reception venue)
1900 - Reception

We decided to not do a big opening as we are expecting people to slowly trickle in over the morning/day because EU folks might just arrive on Monday, and people from further away will most probably be fighting with jetlag (cc @jberkus). We can still think about if we really need a Welcome at 10am or if we do the welcome together with either the kick off of the voting or even the announcement of topics and tell people about unconference style and timeline at the door. WDYT?
Considering "trickling in" I also adjusted the voting period and moved announcing schedule to after lunch as a kickoff to the unconference sessions. again nothing written in stone here, feedback welcome.

If the abovve is fine, the next thing to agree upon will be how long we want uncoference sessions to be to create the slots accordingly.

**Comment by jberkus** [comment]
Questions:

> 1300 - Annpounce Unconference Schedule and first sessions

Does this mean that the first sessions start at 13:10?

> 1500 - Afternoon Tea, 1530 Unconference

Is that a half-hour Unconference session at 15:30?  or something else?

**Comment by jberkus** [comment]
More ideas:

> 1000 - Welcome
> 1130 Start Voting

How about having one pre-planned session from 10:30 to 11:30?  Something we've figured out ahead of time?

**Comment by puja108** [comment]
> > 1300 - Annpounce Unconference Schedule and first sessions
> 
> Does this mean that the first sessions start at 13:10?
> 
> > 1500 - Afternoon Tea, 1530 Unconference
> 
> Is that a half-hour Unconference session at 15:30? or something else?

These both are a bit TBD, I'd like to get an y'alls suggestions if 30 or 45 min slots would be best. Once we have a slot length, we can detail out the unconference part of the schedule I'd say.

> How about having one pre-planned session from 10:30 to 11:30? Something we've figured out ahead of time?

I like that idea. Did you already have sth in mind?

**Comment by puja108** [comment]
cc @pnbrown re schedule adjustment

**Comment by mrbobbytables** [comment]
Summit is over, thanks all!

/close
