### ISSUE TITLE
maintainer audit for a few SIGs

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6622]
### Describe the issue

looking to get unique reviewers and approvers for the following SIGs using the maintainer audit tool

SIGs:
Testing
Multicluster
Node
Cloud provider
API Machinery 

Audit tool:
https://github.com/kubernetes-sigs/maintainers 

/help
/sig contributor-experience

**Comment by MadhavJivrajani** [comment]
@parispittman 👋🏼 

### SIG Testing

**Reviewer and approver count across _all subprojects_:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 36  | 44  |

**Reviewer and approver count _only_ in `k/k`:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 9  | 26  |

---

### SIG Multicluster

**Reviewer and approver count across _all subprojects_:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 20  | 22  |

---

### SIG Node

**Reviewer and approver count across _all subprojects_:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 37  | 34  |

**Reviewer and approver count _only_ in `k/k`:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 22  | 17  |

---

### SIG Cloud Provider

**Reviewer and approver count across _all subprojects_:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 118  | 114  |

**Reviewer and approver count _only_ in `k/k`:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 32  | 21  |

---

### SIG API Machinery

**Reviewer and approver count across _all subprojects_:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 92  | 67  |

**Reviewer and approver count _only_ in `k/k`:**

| Review Count  | Approver Count |
| ------------- | ------------- |
| 49  | 24  |

---

### Summary of how this information was obtained:

This is a summary of how these numbers were obtained in order to keep me honest - so please lmk if you think something isn't right or something can be done better.

The primary tool used to obtain this information is `maintainers`: https://github.com/kubernetes-sigs/maintainers. However, due to missing metadata in OWNER files or a few shortcomings of the tool itself, obtaining a good enough estimate of these numbers proved to be difficult. A summary of the steps:
- Run `maintainers export` on `k/k` to get a high-level overview of the reviewers and approvers present and get the counts based on OWNER_ALIASES.
  - For ex: if an alias called `sig-foo-api-reviewers` exists, get how many of them are there.
- Run `maintainers export` on each subproject of that sig. Subprojects are obtained from the [source of truth](https://github.com/kubernetes/community/blob/master/sigs.yaml).
  - Each entry in this CSV will be attributed to a reviewer/approver in _that_ SIG.
- There may still be counts that are left out on account of projects that are not necessarily listed in the source of truth, for ex: https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd-version-monitor/OWNERS.
- Because of this `maintainers labels` is run on `k/k` and the paths where there are SIG Labels mentioned in OWNER files are also read and the reviewer and approvers in those files are also counted for that SIG.

#### Note

Please note that there may still be paths which are not accounted for. The ideal way IMO to get this information would be to try and reuse the code that the bot uses in order to apply SIG labels, i.e. - if a directory does not have SIG label information, inherit from a parent directory:

https://github.com/kubernetes/test-infra/blob/419f87ddc87cf5739ebd5eb0b3265ac72cce527b/prow/repoowners/repoowners.go#L798

**Comment by parispittman** [comment]
thanks again @MadhavJivrajani !

/close
