### ISSUE TITLE
emeritus counts in OWNERs files

### ISSUE THREAD

**Issue by parispittman** [kubernetes/community#6623]
### Describe the issue

Looking to get a number for how many times 'emeritus' was put into any OWNERs file all k8s repos for two periods:
1 - calendar year 2021 - Jan 21-Dec 21
2 - Jan 22 - now

/help
/sig contributor-experience

**Comment by MadhavJivrajani** [comment]
@parispittman - some numbers for k/k:

### For the calendar year 2021:

Important to keep in mind:
- Total number of OWNERS files where an `emeritus_approver` was added = 66
- Total number of OWNERS files where an `emeritus_approver` was removed = 2

- Number of added `emeritus_approvers` = 98
- Average number of `emeritus_approvers` added per OWNERS file = 1.48
- Number of removed  `emeritus_approvers` = 2
- Average number of `emeritus_approvers` removed per OWNERS file = 1


### For since the beginning of 2022:

Important to keep in mind:
- Total number of OWNERS files where an `emeritus_approver` was added = 63
- Total number of OWNERS files where an `emeritus_approver` was removed = 0

- Number of added `emeritus_approvers` = 80
- Average number of `emeritus_approvers` added per OWNERS file = 1.26
- Number of removed  `emeritus_approvers` = 0
- Average number of `emeritus_approvers` removed per OWNERS file = 0

--- 

### How was this data obtained:

- Check out the repo at the commit for Jan 1 2021 and Dec 31 2021
- Calculate numbers for these two instances of times
- Calculate the difference

**Comment by MadhavJivrajani** [comment]
Created https://github.com/kubernetes-sigs/maintainers/pull/21 to try and automate this for the future.

**Comment by parispittman** [comment]
thanks @MadhavJivrajani again! closing this 

/close
