### ISSUE TITLE
Nodes are flapping with error PLEG is not healthy: PLEG was last seen active 3m.6314604s ago, threshold is 3m0s  This issue is coming only in 2 nodes out of 18 nodes

### ISSUE THREAD

**Issue by nagpalnitin0110** [kubernetes/community#6645]
Cluster version:- 1.20.14
Total Nodes:- 18
Issue on worker Nodes

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
