### ISSUE TITLE
Install Multus on Kubernetes

### ISSUE THREAD

**Issue by AvishaiMan1** [kubernetes/community#6768]
### Describe the issue

I am trying to install Multus on the machines I set up. I installed all plugins from https://github.com/containernetworking/plugins.

Attach the configuration file:

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-confavishai
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens192",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.154.142.0/24",
        "rangeStart": "10.154.142.200",
        "rangeEnd": "10.154.142.220",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.154.142.1"
      }
    }'
I tried to pick up Pods with a link to the same network configuration file:

  annotations: 
    k8s.v1.cni.cncf.io/networks: macvlan-confavishai
and I get an error: failed to find plugin "macvlan" in path [/opt/cni/bin /opt/cni/bin], failed to clean up sandbox container

In the /opt/cni/bin folder there is a Macvlan with permissions so I don't understand where the error comes from.

Would appreciate help!

/sig cni

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
