### ISSUE TITLE
[CONTRIBUTOR SUMMIT NA DETROIT UNCONF] Sign Up

### ISSUE THREAD

**Issue by markyjackson-taulia** [kubernetes/community#6932]
### Describe the issue

**Unconference: k-dev email / slack #contributor-summit suggestion:**

We're hosting an Unconference for the Contributor Summit this year in Detroit. We'd love to hear from you about topics in which you are interested. You can submit a topic, and upvote topics that seem interesting to you. We want to understand what is of general interest to the community, and not just for those who happen to be joining us in Detroit.

_Topic: [Sample Topic Submission]
Description: [Sample Topic Description]
Moderator: [Will you be there in person and like to moderate? (yes or no)]_

EDIT [mrbobbytables]: Upvote/Downvote on topics in this issue with a 👍 👎 emoji.

Feel free to reach out to #contributor-summit for any questions.

Thank you!
KCNA Contributor Summit 2022 Content Team

/sig contributor-experience /area contributor-summit
/area na-summit
/assign markyjackson-taulia

**Comment by RobertKielty** [comment]
Topic : Launching Prow Plugins from Github Actions

Description:
I finished an initial proof-of-concept custom GitHub Action called pga that runs a subset of Prow Plugins.I would be happy to give a demo of it in action and describe why the work was undertaken, go over some implementation details, and what I think the next steps are from an implementation point of view.  

I would like to discuss the strategy behind considering this tool for use in the wider CNCF project community for smaller resource constrained projects and get feedback from the k8s community.

Deck 
https://docs.google.com/presentation/d/1NcPTJL0Lw8Y0-ovaSAIS7AM_zsEkIyLwKYDeTniHSqA/edit?usp=sharing

Moderator: Happy to demo this myself 
cc @hh @carolynvs @geekygirldawn

**Comment by seans3** [comment]
Topic: `kubectl apply/prune` direction

Description:

`kubectl apply/prune` has been alpha for many years, and it has some fundamental limitations. See:

https://docs.google.com/document/d/1y747qL3GYMDDYHR8SqJ-6iWjQEdCJwK_n0z_KHcwa3I/edit?usp=sharing

This discussion would cover the possible directions for this important functionality.

**Comment by craiglpeters** [comment]
Topic: hurdles for new K8s contributors

Description:
What are the hurdles for new contributors to K8s, and how can we categorize and prioritize them? I am very interested in gathering the perspectives of both new and long-time K8s contributors. I worry that those of us who have been doing this too long don't remember what it was like to be new.

Moderator: happy to do it if it makes sense
cc: @chris-short @mrbobbytables

**Comment by vinaykul** [comment]
Topic: Extending kubemark for measuring CNI performance at large scale

Description: We have been working on a PoC that extends kubemark to run real CNI drivers and allocate IPs from them for cost-effective large scale testing. We [shared our idea with sig-scale](https://groups.google.com/g/kubernetes-sig-scale/c/rcnlFhE5FHQ) some time ago to ensure they have no concerns. 

We have made some progress since, and we can share some very-early-very-initial set of results with a working demo. I want to get feedback on whether this might be something the community finds useful, and if yes, want to seek out ideas on how best to proceed given what we currently have.

Here is the [summary slides describing our approach with design doc link](https://drive.google.com/file/d/1nLoBzQHOmdruqwqyWxneosGqk3v7VD0t/view?usp=sharing)

Moderator: If this sounds interesting, I'll present our idea, outline some of the challenges we ran into, and also happy to moderate, if needed.

**Comment by thockin** [comment]
Topic: Multi-cluster horror stories
Description: We all have those stories - whether they are our own or a friend 's or a customer's.  Let compare notes about what we are struggling with around multi-cluster and help set priorities.
Moderator: I can do it if nobody wants to

**Comment by thockin** [comment]
Topic: API battle scars

Description: Let's compare the places where we have found the kube API to be... problematic.  It's important that we all learn from each other's mistakes, so let's take apart some of the worst "seemed like a good idea at the time" situations.

Moderator: happy to lead it

**Comment by bobbypage** [comment]
Topic: Pod Lifecycle - the good, the bad, and the misunderstood

Description: Pod Lifecycle is critical to formalize and document so that k8s users can understand what is the expected behavior for the lifecycle of their pods. This is important for users building on top of kubernetes (such as external controllers), so they can understand what guarantees there are around various lifecycle steps as well (us) the k8s developers.

There has been some recent challenges due to regressions in pod lifecycle, and I would like to discuss and gather feedback on what we can do to better define the pod lifecycle invariants, documentation, and sufficient conformance testing around this topic.

Moderator: Yes, will be there and happy to lead it. I have some initial work on this topic working with @smarterclayton and would like to obtain early feedback on it.

**Comment by atosatto** [comment]
Topic: maintaining the quorum - running stateful workloads on Kubernetes 

With the popularity of the Kubernetes project growing within the community, more and more end-users are starting to use it to run stateful workloads. While Kubernetes provide foundations to easily run these class of services orchestrating them poses unique operation challenges in order to maintain quorum and ensure no service downtime. In this session we would like to discuss best-practices and different solutions to run effectively stateful workloads adopted by the community as well area of improvement for the Kubernetes project.

Moderator: yes, I will be happy to help coordinating the session

**Comment by parispittman** [comment]
thanks for organizing unconference team! 

/close
