### ISSUE TITLE
Update Contributor Comms OWNERS

### ISSUE THREAD

**Issue by chris-short** [kubernetes/community#7010]
### Describe the issue

The Contributor Comms team has had some new folks take roles and the OWNERS file needs some changes accordingly. Please see 

cc @kaslin @AvineshTripathi

**Comment by devarsh10** [comment]
Hey @chris-short,
I would like to contribute in this.
Will you please guide me, where can I find the logs of new owners joined?

Kind Regards.

**Comment by kaslin** [comment]
Oops, this was done back in January but not attributed properly. Sorry about that and thank you for offering, @devarsh10! You're welcome to join the #sig-contribex-comms channel on slack to learn more about our group if you're still looking for ways to contribute.
Fixed by https://github.com/kubernetes/community/commit/f287230d9ea605918945a4ee7d479b4ad49af5d2
