### ISSUE TITLE
Statefulset pod stuck in Terminating state when node become NotReady

### ISSUE THREAD

**Issue by rg13567** [kubernetes/community#7056]
### Describe the issue

/sig K8s Infra

I have statefulset deployed on K8s cluster with 1 replica. Pod was running fine until the node on which the pod was running went into "NotReady" State.
After this my pod went to Terminating state and got stuck in that state.
I was hoping for my pod to get reschedule on to another healthy node but it didn't got reschedule and my application had downtime

I even created a PDB with minAvailable as 1 to maintain 1 pod Up all time but even this didn't help

Any suggestion how this can be handled in statefulset

**Kubectl version**

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:11Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-07-15T20:53:19Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
