### ISSUE TITLE
Statefulset pod stuck in terminating state in case node is in NotReady state

### ISSUE THREAD

**Issue by rg13567** [kubernetes/community#7060]
### Describe the issue
/sig area/kubernetes

I have a statefulset deployed with 1 replica for jenkins. few days back the node on which jenkins pod was running went into NotReady State . Once Node went in NotReady state, Jenkins pod went in Terminating state and stuck there for long time until Node went back in Ready State.

Ideally, my Jenkins pod should have been re-scheduled to a healthy node in case my current node is not healthy. due to this my jenkins application had downtime for the time node was in Not Ready State.

Can anything be done in this case in order to prevent such downtime in statefulset pods

/kubernetes-support

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
