### ISSUE TITLE
Shutting down one of master nodes (NotReady) still shows pods as RUNNING on it

### ISSUE THREAD

**Issue by todortanevski** [kubernetes/community#7061]
### Describe the issue

Hello!

- Kubernetes version v1.24.7
- VMware Nodes
- Node's OS: Oracle Linux 8.5

We have 6 nodes (3 master, 3 worker).
We do some resilience testing.

Shutting down one of the master nodes (NotReady) still shows pods as RUNNING on it without time limit, i.e. the situation doesn't remedy itself.

If we start the node again kubectl starts to pick up proper life signs.

We do not have application pods on master nodes, but this is not expected and it is prone to disable our environment over time.

There are similar bug(s) fixed for v1.18/v1.19 but this is v1.24, so these fixes should already be there.

Also, all pods are parts of the deployments/replicasets - no single pods are present on these nodes.

Please advise what we are doing incorrect and how to proceed.

Best Regards & Thanks!

* /sig <Cluster Lifecycle> <Node>
* /wg <Reliability>

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
