### ISSUE TITLE
spring boot POD container connect host machine 127.0.0.1:3306 DB.

### ISSUE THREAD

**Issue by sajeethpasha** [kubernetes/community#7077]
### Describe the issue

I have **MYSQL** installed in local machine **jdbc:mysql://127.0.0.1:3306/db**  and my **spring boot** application running **minikube**
inside the pod.Here i am not able to connect **springboot** application to **mysqlDB**. please provide soltuion for this one thank you.

![image](https://user-images.githubusercontent.com/70565884/215411654-b707ed22-3d85-43f4-b1c9-4935f163e114.png)

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
