### ISSUE TITLE
Draft a CONTRIBUTING.md to sig-scheduling

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/community#7228]
### Describe the issue

sig-scheduling lacks an exclusive CONTRIBUTING.md contrast to other sigs, like sig node, sig apps. It should include what is the contribution, where to start contributing to sig-scheduling, how to contribute etc..

**Comment by alculquicondor** [comment]
Ideas to put in there (draft, needs some organization):
- In general, PRs require a first pass from a reviewer. Once the reviewer is LGTMed, assign to an approver.
- Leave the reviewers assigned by the bot when possible, unless there is need for a specific contributor's expertise.
- Add a new commit to address review comments, instead of amending. Reviewers will ask you to squash when ready for merging or after a significant part of the PR is agreed upon.
- Critical bug fixes can be assigned to approvers directly. Approvers might send it back to a reviewer if they disagree on the urgency.
- When asking for a feature request:
  - Open an issue in kubernetes/kubernetes, label using `/sig scheduling`. Focus on the end user problem, instead of the API.
  - If there is debate, bring the topic to a SIG meeting.
  - If there are multiple implementation options, consider creating a doc with pros and cons, to gather feedback.
  - Open an issue in kubernetes/enhancements
