### ISSUE TITLE
REQUEST: New Slack channel #gophercloud

### ISSUE THREAD

**Issue by pierreprinetti** [kubernetes/community#7326]
### GitHub Username

@pierreprinetti

### Slack Username

pierre

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

#gophercloud

### Description of Request

I am a maintainer of [Gophercloud](https://github.com/gophercloud/gophercloud), the Go SDK for OpenStack. In the context of Kubernetes, [cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) and [cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack) use Gophercloud to connect to the OpenStack API.

As a project, we currently lack a space for synchronous conversation. We use Github issues and discussions, but sometimes the informality of a chat is what you need to feel free to ask your question.

Do you think we can have a #gophercloud channel in the Kubernetes Slack workspace?

Thank you!

**Comment by coderanger** [comment]
As a project you are definitely Kubernetes-adjacent but not really Kubernetes-specific so I'm not sure this would be the most appropriate? We do support/allow channels from similar projects but they are generally for user-to-user support when there is a substantial Kubernetes-specific user case rather than being official project resources for everyone. Hopefully some other admins can chime in as this is definitely in a gray area but I think it's probably okay for me.

**Comment by pierreprinetti** [comment]
I am not sure if there's anything required of us at this time? Or shall we just wait?

**Comment by pierreprinetti** [comment]
If this can help the decision, we are seeing users starting threads in the #cluster-api-openstack channel to ask questions about Gophercloud.

**Comment by MadhavJivrajani** [comment]
Example PR: https://github.com/kubernetes/community/pull/7375

**Comment by mdbooth** [comment]
As a maintainer of cluster-api-provider-openstack and contributor to cloud-provider-openstack I would welcome this. Apart from somewhere obvious to go to discuss gophercloud myself, we occasionally end up getting gophercloud questions in other channels.

**Comment by pierreprinetti** [comment]
Thank you! Here's https://github.com/kubernetes/community/pull/7387
