### ISSUE TITLE
LoadBalancer external IP is not able to access

### ISSUE THREAD

**Issue by nagarajmmu** [kubernetes/community#7337]
### Describe the issue

Hi

I am new to kubernetes, I have deployed one application with one service in kubernetes, in Azure cloud.
Application is able to deploy successfully.

I am able to get service external IP, but not able to access my application, because external IP is not reachable.
I have used ingress also, but still same issue, please help me, if I am missing anything.

My Yaml is as follows-
_Note: Below Yaml is not formatted,_ 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdb-bundle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-duckdb-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-duckdb-bundle
    spec:   
      containers:
      - image: buntha/duckdb-bundle:0.0.3
        imagePullPolicy: Always
        name: duckdb-bundle
        ports:
        - containerPort: 8088

apiVersion: v1
kind: Service
metadata:
  name: duckdb-bundle
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-duckdb-bundle

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
        - path: /app
          pathType: Prefix
          backend:
            service:
                name: duckdb-bundle
                port:
                  number: 8088

Thanks in advance

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
