### ISSUE TITLE
Need support with Kubernetes Tutorial Video

### ISSUE THREAD

**Issue by iPhoenixEX** [kubernetes/community#7406]
### Describe the issue

Hello,

important infor in advance:
I am an absolute beginner in the subject of Kubernetes!
However, since I am interested in the topic, I watched the following video:

[https://www.youtube.com/watch?v=s_o8dwzRlu4&t=2168s](https://HERE)

So far I understood everything....but the problem is that when I run the command in min 1.04.27....

By executing the command

kubectl get pod --> in the Video, there is no pod running
Well in my case, there is a pod running called hellominikube (i guess thats the pod from the vm)

But the main issue I have is, that iam not able to execute the command:

kubectl apply -f mongo-config.yaml

Iam in the same folder, where the datas are stored but if i use powershell, i get following error message:

error: no objects passed to apply

How can I fix the problem?
Thanks

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
