### ISSUE TITLE
keepalived/haproxy configuration issue

### ISSUE THREAD

**Issue by ermingpei** [kubernetes/community#7524]
### Describe the issue

Hi,  in deploying keepalived/haproxy for a k8s cluster by following this instruction (https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability),
should we make the frontend bind server:port consistent with the control plane endpoint? (as shown in the instructionsudo kubeadm init --control-plane-endpoint "LOAD_BALANCER_DNS:LOAD_BALANCER_PORT" --upload-certs )
But I tried and it always failed when they are consistent with the following error:
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-6443]: Port 6443 is in use

**Comment by mrbobbytables** [comment]
/
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
