### ISSUE TITLE
"x509: certificate signed by unknown authority error" when trying to  pull images from a Private docker repo using secret.

### ISSUE THREAD

**Issue by gunjanmiglani** [kubernetes/community#760]

**Comment by gunjanmiglani** [comment]
Hi Guys,
I have a setup of kubernetes and want to deploy an image which should come from a private docker repo.
I have created the secrte with repo credentials for pulling the image but pod creation ends in error.

Failed to pull image "registry.<myip>.nip.io/ms-accounts:0.0.1": rpc error: code = 2 desc = Error response from daemon: {"message":"Get https://registry.<myip>.nip.io/v1/_ping: x509: certificate signed by unknown authority"} 
Error syncing pod, skipping: failed to "StartContainer" for "my-private-reg-container" with ErrImagePull: "rpc error: code = 2 desc = Error response from daemon: {\"message\":\"Get https://registry.<myip>.nip.io/v1/_ping: x509: certificate signed by unknown authority\"}"

What should I do?

**Comment by zhouhaibing089** [comment]
This requires that all the nodes in your cluster has `--insecure-registry` flag set.

**Comment by gunjanmiglani** [comment]
Thanks. But my kubeconfig has got certificates already so I cant add that flag.

The point is that this private docker registry is on another public host and not on any k8 mater or k8 nodes.

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
