### ISSUE TITLE
In AKS, unable to connect backend application thru frontend application using "service name"

### ISSUE THREAD

**Issue by KRISHNAKUMARU** [kubernetes/community#7655]
### Describe the issue

Hello all,
I am facing an issue on Azure Kubernetes. We have deployed Frontend and Backend applications in same namespace in AKS cluster. 
We are unable to connect backend application thru frontend application using service name like "<service_name>.<namespace_name>.svc.cluster.local:<port>", but able to connect successfully when we use Pod IP of backend service in frontend. 

Network type (plugin) is  Azure CNI.

can someone help to resolve this issue.

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
