### ISSUE TITLE
invalid capacity 0 on image filesystem

### ISSUE THREAD

**Issue by uepaki** [kubernetes/community#7809]
New to kubernetes. Installed it on ubuntu 22.04 using kubeadm on AWS bare metal instance. Facing this issue "invalid capacity 0 on image filesystem" from last night. df -h and all other commande shows almost 75% available space yet my master node isn't getting ready coz of this issue. Can anyone help?

Thanks in advance.

```[tasklist]
### Tasks
```

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
