### ISSUE TITLE
pod does not send any ARP request with self IP 

### ISSUE THREAD

**Issue by Davidrjx** [kubernetes/community#7918]
### Describe the issue

in k8s v1.23.13 cluster, on certain node(hostname) pod cannot traceroute to kubernetes svc ip but ping works
meanwhile,  on node traffic capture by nslookup kubernetes output like
```
...
09:47:34.625033 LLDP, length 221: <hostname>
09:47:36.285491 IP 172.18.88.13.58555 > 172.19.0.10.domain: 21926+ A? kubernetes.default.svc.cluster.local. (54)
09:47:41.286712 IP 172.18.88.13.58555 > 172.19.0.10.domain: 21926+ A? kubernetes.default.svc.cluster.local. (54)
09:47:41.318517 ARP, Request who-has 169.254.1.1 tell 172.18.88.13, length 28
09:47:41.318542 ARP, Reply 169.254.1.1 is-at ee:ee:ee:ee:ee:ee (oui Unknown), length 28
09:47:46.290649 IP 172.18.88.13.58555 > 172.19.0.10.domain: 21926+ A? kubernetes.default.svc.cluster.local. (54)
09:48:04.627400 LLDP, length 221: <hostname>
...
```
in contrast to normal node, found that an ARP request from pod self's IP missing on abnormal one
could someone please provide some clue? thanks

**Comment by mrbobbytables** [comment]
Please re-post your question to the [Kubernetes User Forum](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

Members of the Kubernetes community use the Forum to field support requests. Before posting a new question, please search there for answers to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team


---
/kind support
/close
