### ISSUE TITLE
SIGs list uses UTC, but the SIGs generally don't

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/community#841]
https://github.com/kubernetes/community/blob/master/sigs.yaml
lists times in UTC but approximately every SIG actually meets on local time, so the times listed here are wrong half of the year in locales that have Daylight Savings Time

Created issue for tracking/triage, reported by @davidopp

**Comment by xiangpengzhao** [comment]
I remember that the times once were listed on local time in https://github.com/kubernetes/community/blob/master/sig-list.md. They were mapped to my local time on google calender. That's convenient·

**Comment by xiangpengzhao** [comment]
See also: https://github.com/kubernetes/community/issues/724#issuecomment-308751868

**Comment by garethr** [comment]
This just hit me this week for SIG Apps and for the App Def working group. I'll use SIG Apps as an example but I don't think this the only one.

The SIG page on this site uses UTC, as do all of the SIG pages I had a quick look at: https://github.com/kubernetes/community/tree/master/sig-apps

However the agenda and minutes at https://docs.google.com/document/d/1LZLBGW2wRDwAfdBNHJjFfk9CFoyZPcIYGWU7R1PQ3ng/edit# state:

> Meetings are held via Zoom at 9am PST on Mondays,

@mattfarina is going to change the SIG Apps page to make it match reality, the SIG actually always meets at 9am PST, which means the time varies for non-US folks like me.

Note that the time varying is not, in my view, a problem. Due to the vagaries of timezones and daylight saving no time avoids this. The problem here is as stated in the title of this issue - and appears one of policy (the community repo template uses UTC) and reality (most of the SIGs don't).

**Comment by cblecker** [comment]
Yeah, this is confusing. Unless anyone has any objections, I'd be fine with moving this to use PST as the base time zone. I'm not sure what the best way to represent DST is though.. we'd have to clarify with the sigs if they'll be meeting at the same time or if it will shift for Daylight Savings. My guess is the latter.

cc: @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort

**Comment by lavalamp** [comment]
PDT = daylight adjusted PST

**Comment by cblecker** [comment]
Right, but there are currently no locations that are in PDT (UTC-7). Everything has transitioned over to PST (UTC-8). There are some locations that use [different dates for transitioning](https://en.wikipedia.org/wiki/Pacific_Time_Zone#Daylight_time), so it's possible to have both PST and PDT time zones on the same day.

**Comment by lavalamp** [comment]
How about we post both the local time, and summer/winter UTC times in the documentation?

**Comment by jbeda** [comment]
I'm fixing this now by letting SIGs specify time in whatever time zone they want.

**Comment by jbeda** [comment]
I just did cluster lifecycle but could update the rest to be the pacific equivalent and then let people fix it if they *don't* want to flow with DST.

God, I hate DST. And Time Zones.

**Comment by jbeda** [comment]
If someone here wants to jump on to #1350 and give it a LGTM, that'd be great.
